In [1]:
import pandas as pd
import copy
import datetime

In [2]:
df_allergies = pd.read_csv('allergies.csv')
df_careplans = pd.read_csv('careplans.csv')
df_conditions = pd.read_csv('conditions.csv')
df_devices = pd.read_csv('devices.csv')
df_encounters = pd.read_csv('encounters.csv')
df_imaging = pd.read_csv('imaging_studies.csv')
df_immunizations = pd.read_csv('immunizations.csv')
df_medications = pd.read_csv('medications.csv')
df_observations = pd.read_csv('observations.csv')
df_organizations = pd.read_csv('organizations.csv')
df_patients = pd.read_csv('patients.csv')
df_payer_trans = pd.read_csv('payer_transitions.csv')
df_payers = pd.read_csv('payers.csv')
df_procedures = pd.read_csv('procedures.csv')
df_providers = pd.read_csv('providers.csv')
df_supplies = pd.read_csv('supplies.csv')

In [3]:
df_conditions.PATIENT.nunique()

1152

In [4]:
df = copy.deepcopy(df_patients)

In [5]:
df = df[['Id', 'BIRTHDATE', 'DEATHDATE','MARITAL', 'RACE', 'ETHNICITY',
       'GENDER', 'BIRTHPLACE','HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE']]

In [6]:
df = df.fillna(0)

In [7]:
df['Age'] = 0
df['Alive'] = 1
df

,Id,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,1989-05-25,0,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,0,1
1,034e9e3b-2def-4559-bb2a-7850888ae060,1983-11-14,0,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,0,1
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,1992-06-02,0,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,0,1
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,1978-05-27,0,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,0,1
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,1996-10-18,0,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,1922-02-14,0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,0,1
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,1977-08-08,0,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,0,1
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,1914-09-05,2006-05-26,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,0,1
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,1914-09-05,1990-03-17,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,0,1
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,1914-09-05,0,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,0,1

In [8]:
for i in range(len(df)):
    if df.DEATHDATE[i] == 0 :
        today = datetime.date.today()
        birth = datetime.datetime.strptime(df.BIRTHDATE[i],"%Y-%m-%d").date()
        age = today.year - birth.year - ((today.month,today.day)<(birth.month,birth.day))         
    else:
        df.Alive[i] = 0
        birth = datetime.datetime.strptime(df.BIRTHDATE[i],"%Y-%m-%d").date()
        death = datetime.datetime.strptime(df.DEATHDATE[i],"%Y-%m-%d").date()
        age = today.year - birth.year - ((today.month,today.day)<(birth.month,birth.day))
    df.Age[i]= age

/tmp/ipykernel_25837/2876896380.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Age[i]= age
/tmp/ipykernel_25837/2876896380.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Alive[i] = 0

In [9]:
df.drop(['BIRTHDATE','DEATHDATE'],axis=1,inplace=True)

In [10]:
df_allergies.drop(['DESCRIPTION'],axis=1,inplace = True)

In [11]:
df_allergies['Allergy_Time'] = 0
df_allergies.fillna(0,inplace=True)

In [12]:
for i in range(len(df_allergies)):
    if df_allergies.STOP[i] == 0 :
        today = datetime.date.today()
        start = datetime.datetime.strptime(df_allergies.START[i],"%Y-%m-%d").date()
        age = today.year - start.year - ((today.month,today.day)<(start.month,start.day))         
    else:
        start = datetime.datetime.strptime(df_allergies.START[i],"%Y-%m-%d").date()
        stop = datetime.datetime.strptime(df_allergies.STOP[i],"%Y-%m-%d").date()
        age = stop.year - start.year - ((stop.month,stop.day)<(start.month,start.day))
    df_allergies.Allergy_Time[i] = age

/tmp/ipykernel_25837/1190346975.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_allergies.Allergy_Time[i] = age

In [13]:
df_allergies.drop(['START','STOP'],axis=1,inplace=True)

In [14]:
df_allergies.rename(columns={'ENCOUNTER':'ALLERGY_ENCOUNTER','CODE':'ALLERGY_CODE'},inplace=True)

In [15]:
df_allergies

,PATIENT,ALLERGY_ENCOUNTER,ALLERGY_CODE,Allergy_Time
0,76982e06-f8b8-4509-9ca3-65a99c8650fe,b896bf40-8b72-42b7-b205-142ee3a56b55,300916003,39
1,76982e06-f8b8-4509-9ca3-65a99c8650fe,b896bf40-8b72-42b7-b205-142ee3a56b55,300913006,39
2,71ba0469-f0cc-4177-ac70-ea07cb01c8b8,7be1a590-4239-4826-9872-031327f3c368,419474003,19
3,71ba0469-f0cc-4177-ac70-ea07cb01c8b8,7be1a590-4239-4826-9872-031327f3c368,232347008,19
4,71ba0469-f0cc-4177-ac70-ea07cb01c8b8,7be1a590-4239-4826-9872-031327f3c368,418689008,19
...,...,...,...,...
592,e6ff4bf9-09c2-4976-aa84-cca142207cf8,6c760807-a6b7-4af4-8d50-f32325803448,418689008,21
593,e6ff4bf9-09c2-4976-aa84-cca142207cf8,6c760807-a6b7-4af4-8d50-f32325803448,419263009,21
594,e6ff4bf9-09c2-4976-aa84-cca142207cf8,6c760807-a6b7-4af4-8d50-f32325803448,91930004,21
595,e6ff4bf9-09c2-4976-aa84-cca142207cf8,6c760807-a6b7-4af4-8d50-f32325803448,91935009,21
596,13b9a676-7cfd-4b7c-bdb6-43ec52b7c919,bbd17366-0801-45ee-8589-0f3eb31c7d0d,419474003,106

In [16]:
prev = 0 
dict1 = {}
dict2 = {}
val=0
for i in range(1,len(df_allergies)):
    if df_allergies.PATIENT[i] == df_allergies.PATIENT[prev] :
        #print(i)
        continue
    else :
        list1 = df_allergies.ALLERGY_CODE[prev:i].values
        list2 = df_allergies.Allergy_Time[prev:i].values
        dict1[df_allergies.PATIENT[prev]] = list1
        dict2[df_allergies.PATIENT[prev]] = list2
        prev = i
        if i == len(df_allergies)-1 :
            val=1
if val==1:
    list1 = [df_allergies.ALLERGY_CODE[prev]]
    list2 = [df_allergies.Allergy_Time[prev]]
    dict1[df_allergies.PATIENT[prev]] = list1
    dict2[df_allergies.PATIENT[prev]] = list2

In [17]:
prev = 0
for i in range(1,len(df_allergies)):
    if df_allergies.PATIENT[i] == df_allergies.PATIENT[prev] :
        df_allergies.drop(i,axis=0,inplace=True)
    else:
        prev=i

In [18]:
df_allergies['ALLERGY_CODE'] = df_allergies['ALLERGY_CODE'].astype(object)
df_allergies['Allergy_Time'] = df_allergies['Allergy_Time'].astype(object)

In [19]:
df_allergies.reset_index(inplace=True)

In [20]:
df_allergies

,index,PATIENT,ALLERGY_ENCOUNTER,ALLERGY_CODE,Allergy_Time
0,0,76982e06-f8b8-4509-9ca3-65a99c8650fe,b896bf40-8b72-42b7-b205-142ee3a56b55,300916003,39
1,2,71ba0469-f0cc-4177-ac70-ea07cb01c8b8,7be1a590-4239-4826-9872-031327f3c368,419474003,19
2,8,2f43a131-a43a-4c8c-a723-cc261adb9cc6,dbbace5a-29c8-458d-805b-2c3f7cbed818,419474003,3
3,14,bf35e4fa-ea4f-40a4-8fe6-1f2f26e0aa45,a61f97fa-70c3-4366-90e1-7c6fdcba5cbb,300916003,19
4,24,ad7c452d-c8e9-40ae-a5ed-90b7bd93d2ac,4c7ed821-8753-40f3-a18e-31feef7074ef,419474003,33
...,...,...,...,...,...
136,578,8bf8631f-2fd4-4dc7-af2b-c400499fedfc,90ea604b-e2bf-4ca0-a46b-dc480f2f2a03,419474003,18
137,580,c5d6bdfa-5554-4927-8fa8-794e5514cb56,e42aa828-ad33-404f-af29-f1f9f17bd7f5,417532002,42
138,581,2a6d1e58-88eb-4be0-b6b4-59a471257c2e,f7ff5032-50cc-480e-90ca-848c85d6d014,419474003,56
139,588,e6ff4bf9-09c2-4976-aa84-cca142207cf8,6c760807-a6b7-4af4-8d50-f32325803448,300916003,16
140,596,13b9a676-7cfd-4b7c-bdb6-43ec52b7c919,bbd17366-0801-45ee-8589-0f3eb31c7d0d,419474003,106

In [21]:
for i in range(len(df_allergies)) :
    print(df_allergies.PATIENT[i])
for j in dict1 :
    print(j)

76982e06-f8b8-4509-9ca3-65a99c8650fe
71ba0469-f0cc-4177-ac70-ea07cb01c8b8
2f43a131-a43a-4c8c-a723-cc261adb9cc6
bf35e4fa-ea4f-40a4-8fe6-1f2f26e0aa45
ad7c452d-c8e9-40ae-a5ed-90b7bd93d2ac
e20fb002-6dc6-4cea-ba4b-7f528ccf6572
e3af2463-f4c9-4dbb-a8d2-d6a08c5b1460
ddfa05a6-b8a6-4208-b609-28f9a6a8d79e
47a91815-0dca-49df-b1dc-8bb88d8c1b38
28f36cfa-7696-4f73-ac4f-427e802199d9
df91aedf-3e17-44c3-b273-62e35f518475
d1639077-59f3-401f-a058-2ad70502f93f
0c5aa52a-3b1d-4289-af16-29f7a2d07fec
2a88cb57-86fa-4259-93bf-3956e91b07f4
e061409e-4b85-4ec1-b1f7-02677d51f763
71e13815-55fb-4734-bcac-6079160d82a0
852f4588-ba8f-4eeb-94fe-5c3c974ab114
6ca038f1-a3f6-4c2d-848e-bab8e7ae7101
cd900636-aee9-41b1-acf1-557efa0fd9cd
09616ead-22c8-4210-8cb9-2fdc28e043ca
33454fc9-b2ea-407a-9a9d-64897cf44093
1fd5b5d7-4514-44b8-a06b-767d1be8fb97
10c64243-1b39-4f8d-8add-6c767a2f2e50
f7d7b580-e670-4921-bc67-550ec468d506
ca3330c5-bbbc-47e7-addb-302f2e069986
24bca5cf-ba55-457f-8e80-49690202443c
f36775e8-bf5a-40a2-a223-679c05b46004
e6a843e8-10db-454b-a39c-d133a7a75a62
8be68b2d-8054-4882-8715-65297d36767a
2335bebd-0843-4322-9585-8ab90f49def3
45ad6c75-7808-4f70-9c80-0db44f681e55
59669e7c-0190-4cbf-9e27-4898f1a35d03
4b92e3f1-b92b-48ec-9baa-2905409d1743
9fda53d4-6fcc-4ef5-a1fe-16e007182ec2
de767c9e-3131-4d1a-9eed-fdd86a15d459
affb8a9e-4a9a-46e7-a94b-e9c90b25f444
8ba79a69-6f3f-4aa5-be2a-dfbd0119d3ea
128d5c93-dfce-49a1-8d08-e9b24abcb4db
eba0f292-1951-4af9-9f14-9d6e9db8e480
5846c531-ad71-4b34-9607-3a1022cddffa
d00fc5dd-be0e-47aa-a52a-5cf9ee3a78b5
7e4e6d32-15cd-4d5f-a4cc-e5c95ab35eb0
841095eb-d29f-4492-8f0e-08011321e85d
171508e4-8de0-4f33-b7d0-87b7ac4a8008
ee7f6c74-a8ed-4147-b8e2-4879c8657b0f
e112cedd-a98e-489e-abb0-875420d40397
f1462368-c891-4ede-9a2f-782da4386bcf
6e239b88-5153-4098-85ab-27bd7539cd0e
0c5a6873-0823-497d-b5cb-57f28a11bf62
ab6a2662-f6d1-4da6-b3ce-3929d68650d7
f830d725-640c-4c94-972a-61207b748347
c844d8ac-d5bf-45eb-b8cf-84327c9a4e97
ca24f616-30cc-4351-aca9-1b49297de076
22da6290-e240-4875-97ec-0c2372ff45e5
cbec03bf-d54a-41ec-9090-bb36a70028b0
c4f221f2-611b-4cdd-a0b6-958bbbfcf346
77a0cd86-92bb-4c6d-a91a-49ee66e353b9
ea8e6623-5590-4d01-bfc1-25d86b1b4491
4440ff11-69ec-440b-a2bd-dc1c14105e8e
1aa71b23-790e-4d22-92da-c689682c8993
a263f1fb-ffb1-4913-997f-455b6c6ab81e
1a289f28-b73b-4d3a-83ef-2216e8837bad
2f423855-1f84-4faa-9218-cd593bef6fe1
ba2c1e9f-16e0-427b-97db-dc639daeaaee
33c2184c-bda1-4d31-b0cb-4f18c46822da
5f1c9186-80b0-405f-9f74-c4e26beb1d01
317ccdcf-cb9c-488c-901c-a5d61c249919
ca8803ac-66ef-4895-a8c4-290313fcee6f
ed6fb8d6-c14d-4e34-a029-2dab33855ddd
9ec6d974-df2b-44ec-acc2-77d96725f4f4
78ddb775-9cd7-46c6-87b9-277a2a92c72b
45840f9a-a735-45e4-beb0-b750fc9a712e
bab51ea9-2945-4f8a-8015-e430f80a908e
1d4f63d2-ddc0-47bc-b2cc-6f58068a5901
734dfbb9-6320-4fee-b21a-175d3f2f14ba
dc00fea9-2f95-46f9-ba8e-d382489c6e6a
2174522f-1d23-47cf-b56c-4ce3193c5bab
5c520448-6728-42cb-8cf2-457bc7c2b1f1
9b50f7b9-c67c-4044-aad0-594ee95b0c29
a694ecfc-e39e-46dc-876e-029b32ba0135
b88dac97-2026-43e9-b40f-71fc0f888ce7
d7d1f837-a2c8-4648-b498-a02278b91a08
8b119fdd-0fea-46dd-9106-b5c7813e7260
848e0227-5d5d-4bdf-8603-207cdea72e2a
eafd1fd3-3778-423a-ba79-4584bd310eb4
25f2b770-8821-48f0-a7fe-460dfe3b15b8
2e4df8c7-8b04-4165-a1fb-e4234d8aebe7
26ca976d-0b5b-4662-af41-535ff670dd5a
65243e61-da11-42a6-826e-a43d960d1e84
199946d9-69de-43e1-9ce6-d6b646b84955
4be910c3-22ae-4868-9dbe-667aec6e5342
08ea9043-5f84-46ab-9815-81d90024169a
2950e244-0ba6-4afe-ac30-e0d5529d1d1b
a3abc11b-0fd1-4eb9-a69a-9075b4737612
f23e12d9-2ec6-4006-b041-ea78d374e9c9
0288abb6-633c-40c3-ba0c-66c7d957727e
5a1848d9-9b49-4529-94f1-e463b502c73b
f504b982-e99b-4064-ad25-9e5480e769cd
097079b1-ff8f-4ee0-8ce3-0ea744ecfa21
7ea0b41a-3459-4623-a288-0ac335319244
076688b0-f0d5-4c45-8bc6-b206684fa9ac
78a9a8d6-b3b2-47dc-b4a0-867abec7c78f
380e2738-59f4-4f03-a9f7-11d73c648e34
7525003c-806f-401a-a6ae-751c39112c56
756c201c-d61c-4495-afc0-09ca95c673a4
8aeeef59-43b3-4983-8f1d-54f3e8d5ea92
13db4bb8-d1dc-4158-a820-d2d1b7084fc4
c05478a7-a4df-4fd3-8d68-60b9452d4781
5dccb2e6-668f-41b4-add4-4020617610b3
e188fafe-c1bb-45dc-9627-4ff4e4bc0ec0
a0a64d10-5b1e-4e17-953a-efccb0c860da
f0f6572b-1588-4828-bb8b-e3148692e536
a0fa2ed6-1b9a-4e35-9126-7d8a5c891f42
b4d1167c-9adf-40e0-8295-4c3f25fdb3b4
a4222dad-09bb-4049-b3dc-01b79f41012f
4f9dcdaa-fb47-412b-8288-03f8cbbc321e
51ab042b-d75e-45f9-ad85-019be3a051bf
b16ca449-bc14-4619-a936-07f6f3db7119
0e1ad739-81d1-4170-841d-414ddc97c93a
13c98b78-98e9-41fb-a29a-686d005d98f7
1e52e4fe-13c7-41ad-8b3e-5933fdd553c4
92709d5b-63d2-4e47-b857-dccb09724ea3
22415347-d2fb-4357-aaeb-ddba23e5cdf0
8db0d104-4c3f-40d3-bcf5-f5eb81b7308f
1030d86d-86f5-4195-962a-48895ca085ab
703e4c46-ded2-4797-97fe-57fedda2825f
b37c9b35-6fea-4570-b7f6-379baf4c9399
b1b10f6e-e97a-426a-9581-f1a5c29b6e05
0aaa2164-8de6-4152-8674-14d254aae13a
96942a16-75bc-4026-bd63-e985b0ca1d6d
55506d51-2c6a-4608-aae3-7cb2f111c926
df7c1d66-eac2-49bd-9d12-ee17e8758f68
68878f91-5962-4ef2-83e7-43b8298c1708
6c7a3894-fa93-418f-b086-4bf001b94a50
1c2aa038-9366-4c7d-9a3e-52cb753a670f
8d202c65-427d-4190-8c28-3aa27e1a9f4c
8bf8631f-2fd4-4dc7-af2b-c400499fedfc
c5d6bdfa-5554-4927-8fa8-794e5514cb56
2a6d1e58-88eb-4be0-b6b4-59a471257c2e
e6ff4bf9-09c2-4976-aa84-cca142207cf8
13b9a676-7cfd-4b7c-bdb6-43ec52b7c919
76982e06-f8b8-4509-9ca3-65a99c8650fe
71ba0469-f0cc-4177-ac70-ea07cb01c8b8
2f43a131-a43a-4c8c-a723-cc261adb9cc6
bf35e4fa-ea4f-40a4-8fe6-1f2f26e0aa45
ad7c452d-c8e9-40ae-a5ed-90b7bd93d2ac
e20fb002-6dc6-4cea-ba4b-7f528ccf6572
e3af2463-f4c9-4dbb-a8d2-d6a08c5b1460
ddfa05a6-b8a6-4208-b609-28f9a6a8d79e
47a91815-0dca-49df-b1dc-8bb88d8c1b38
28f36cfa-7696-4f73-ac4f-427e802199d9
df91aedf-3e17-44c3-b273-62e35f518475
d1639077-59f3-401f-a058-2ad70502f93f
0c5aa52a-3b1d-4289-af16-29f7a2d07fec
2a88cb57-86fa-4259-93bf-3956e91b07f4
e061409e-4b85-4ec1-b1f7-02677d51f763
71e13815-55fb-4734-bcac-6079160d82a0
852f4588-ba8f-4eeb-94fe-5c3c974ab114
6ca038f1-a3f6-4c2d-848e-bab8e7ae7101
cd900636-aee9-41b1-acf1-557efa0fd9cd
09616ead-22c8-4210-8cb9-2fdc28e043ca
33454fc9-b2ea-407a-9a9d-64897cf44093
1fd5b5d7-4514-44b8-a06b-767d1be8fb97
10c64243-1b39-4f8d-8add-6c767a2f2e50
f7d7b580-e670-4921-bc67-550ec468d506
ca3330c5-bbbc-47e7-addb-302f2e069986
24bca5cf-ba55-457f-8e80-49690202443c
f36775e8-bf5a-40a2-a223-679c05b46004
e6a843e8-10db-454b-a39c-d133a7a75a62
8be68b2d-8054-4882-8715-65297d36767a
2335bebd-0843-4322-9585-8ab90f49def3
45ad6c75-7808-4f70-9c80-0db44f681e55
59669e7c-0190-4cbf-9e27-4898f1a35d03
4b92e3f1-b92b-48ec-9baa-2905409d1743
9fda53d4-6fcc-4ef5-a1fe-16e007182ec2
de767c9e-3131-4d1a-9eed-fdd86a15d459
affb8a9e-4a9a-46e7-a94b-e9c90b25f444
8ba79a69-6f3f-4aa5-be2a-dfbd0119d3ea
128d5c93-dfce-49a1-8d08-e9b24abcb4db
eba0f292-1951-4af9-9f14-9d6e9db8e480
5846c531-ad71-4b34-9607-3a1022cddffa
d00fc5dd-be0e-47aa-a52a-5cf9ee3a78b5
7e4e6d32-15cd-4d5f-a4cc-e5c95ab35eb0
841095eb-d29f-4492-8f0e-08011321e85d
171508e4-8de0-4f33-b7d0-87b7ac4a8008
ee7f6c74-a8ed-4147-b8e2-4879c8657b0f
e112cedd-a98e-489e-abb0-875420d40397
f1462368-c891-4ede-9a2f-782da4386bcf
6e239b88-5153-4098-85ab-27bd7539cd0e
0c5a6873-0823-497d-b5cb-57f28a11bf62
ab6a2662-f6d1-4da6-b3ce-3929d68650d7
f830d725-640c-4c94-972a-61207b748347
c844d8ac-d5bf-45eb-b8cf-84327c9a4e97
ca24f616-30cc-4351-aca9-1b49297de076
22da6290-e240-4875-97ec-0c2372ff45e5
cbec03bf-d54a-41ec-9090-bb36a70028b0
c4f221f2-611b-4cdd-a0b6-958bbbfcf346
77a0cd86-92bb-4c6d-a91a-49ee66e353b9
ea8e6623-5590-4d01-bfc1-25d86b1b4491
4440ff11-69ec-440b-a2bd-dc1c14105e8e
1aa71b23-790e-4d22-92da-c689682c8993
a263f1fb-ffb1-4913-997f-455b6c6ab81e
1a289f28-b73b-4d3a-83ef-2216e8837bad
2f423855-1f84-4faa-9218-cd593bef6fe1
ba2c1e9f-16e0-427b-97db-dc639daeaaee
33c2184c-bda1-4d31-b0cb-4f18c46822da
5f1c9186-80b0-405f-9f74-c4e26beb1d01
317ccdcf-cb9c-488c-901c-a5d61c249919
ca8803ac-66ef-4895-a8c4-290313fcee6f
ed6fb8d6-c14d-4e34-a029-2dab33855ddd
9ec6d974-df2b-44ec-acc2-77d96725f4f4
78ddb775-9cd7-46c6-87b9-277a2a92c72b
45840f9a-a735-45e4-beb0-b750fc9a712e
bab51ea9-2945-4f8a-8015-e430f80a908e
1d4f63d2-ddc0-47bc-b2cc-6f58068a5901
734dfbb9-6320-4fee-b21a-175d3f2f14ba
dc00fea9-2f95-46f9-ba8e-d382489c6e6a
2174522f-1d23-47cf-b56c-4ce3193c5bab
5c520448-6728-42cb-8cf2-457bc7c2b1f1
9b50f7b9-c67c-4044-aad0-594ee95b0c29
a694ecfc-e39e-46dc-876e-029b32ba0135
b88dac97-2026-43e9-b40f-71fc0f888ce7
d7d1f837-a2c8-4648-b498-a02278b91a08
8b119fdd-0fea-46dd-9106-b5c7813e7260
848e0227-5d5d-4bdf-8603-207cdea72e2a
eafd1fd3-3778-423a-ba79-4584bd310eb4
25f2b770-8821-48f0-a7fe-460dfe3b15b8
2e4df8c7-8b04-4165-a1fb-e4234d8aebe7
26ca976d-0b5b-4662-af41-535ff670dd5a
65243e61-da11-42a6-826e-a43d960d1e84
199946d9-69de-43e1-9ce6-d6b646b84955
4be910c3-22ae-4868-9dbe-667aec6e5342
08ea9043-5f84-46ab-9815-81d90024169a
2950e244-0ba6-4afe-ac30-e0d5529d1d1b
a3abc11b-0fd1-4eb9-a69a-9075b4737612
f23e12d9-2ec6-4006-b041-ea78d374e9c9
0288abb6-633c-40c3-ba0c-66c7d957727e
5a1848d9-9b49-4529-94f1-e463b502c73b
f504b982-e99b-4064-ad25-9e5480e769cd
097079b1-ff8f-4ee0-8ce3-0ea744ecfa21
7ea0b41a-3459-4623-a288-0ac335319244
076688b0-f0d5-4c45-8bc6-b206684fa9ac
78a9a8d6-b3b2-47dc-b4a0-867abec7c78f
380e2738-59f4-4f03-a9f7-11d73c648e34
7525003c-806f-401a-a6ae-751c39112c56
756c201c-d61c-4495-afc0-09ca95c673a4
8aeeef59-43b3-4983-8f1d-54f3e8d5ea92
13db4bb8-d1dc-4158-a820-d2d1b7084fc4
c05478a7-a4df-4fd3-8d68-60b9452d4781
5dccb2e6-668f-41b4-add4-4020617610b3
e188fafe-c1bb-45dc-9627-4ff4e4bc0ec0
a0a64d10-5b1e-4e17-953a-efccb0c860da
f0f6572b-1588-4828-bb8b-e3148692e536
a0fa2ed6-1b9a-4e35-9126-7d8a5c891f42
b4d1167c-9adf-40e0-8295-4c3f25fdb3b4
a4222dad-09bb-4049-b3dc-01b79f41012f
4f9dcdaa-fb47-412b-8288-03f8cbbc321e
51ab042b-d75e-45f9-ad85-019be3a051bf
b16ca449-bc14-4619-a936-07f6f3db7119
0e1ad739-81d1-4170-841d-414ddc97c93a
13c98b78-98e9-41fb-a29a-686d005d98f7
1e52e4fe-13c7-41ad-8b3e-5933fdd553c4
92709d5b-63d2-4e47-b857-dccb09724ea3
22415347-d2fb-4357-aaeb-ddba23e5cdf0
8db0d104-4c3f-40d3-bcf5-f5eb81b7308f
1030d86d-86f5-4195-962a-48895ca085ab
703e4c46-ded2-4797-97fe-57fedda2825f
b37c9b35-6fea-4570-b7f6-379baf4c9399
b1b10f6e-e97a-426a-9581-f1a5c29b6e05
0aaa2164-8de6-4152-8674-14d254aae13a
96942a16-75bc-4026-bd63-e985b0ca1d6d
55506d51-2c6a-4608-aae3-7cb2f111c926
df7c1d66-eac2-49bd-9d12-ee17e8758f68
68878f91-5962-4ef2-83e7-43b8298c1708
6c7a3894-fa93-418f-b086-4bf001b94a50
1c2aa038-9366-4c7d-9a3e-52cb753a670f
8d202c65-427d-4190-8c28-3aa27e1a9f4c
8bf8631f-2fd4-4dc7-af2b-c400499fedfc
c5d6bdfa-5554-4927-8fa8-794e5514cb56
2a6d1e58-88eb-4be0-b6b4-59a471257c2e
e6ff4bf9-09c2-4976-aa84-cca142207cf8
13b9a676-7cfd-4b7c-bdb6-43ec52b7c919

In [22]:
for i in range(len(df_allergies)):
    df_allergies.ALLERGY_CODE[i]= dict1[df_allergies.PATIENT[i]]
    df_allergies.Allergy_Time[i] = dict2[df_allergies.PATIENT[i]]

/tmp/ipykernel_25837/3684327797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_allergies.ALLERGY_CODE[i]= dict1[df_allergies.PATIENT[i]]
/tmp/ipykernel_25837/3684327797.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_allergies.Allergy_Time[i] = dict2[df_allergies.PATIENT[i]]

In [23]:
df_allergies

,index,PATIENT,ALLERGY_ENCOUNTER,ALLERGY_CODE,Allergy_Time
0,0,76982e06-f8b8-4509-9ca3-65a99c8650fe,b896bf40-8b72-42b7-b205-142ee3a56b55,"[300916003, 300913006]","[39, 39]"
1,2,71ba0469-f0cc-4177-ac70-ea07cb01c8b8,7be1a590-4239-4826-9872-031327f3c368,"[419474003, 232347008, 418689008, 419263009, 7...","[19, 19, 19, 19, 19, 19]"
2,8,2f43a131-a43a-4c8c-a723-cc261adb9cc6,dbbace5a-29c8-458d-805b-2c3f7cbed818,"[419474003, 232350006, 232347008, 418689008, 4...","[3, 3, 3, 3, 3, 3]"
3,14,bf35e4fa-ea4f-40a4-8fe6-1f2f26e0aa45,a61f97fa-70c3-4366-90e1-7c6fdcba5cbb,"[300916003, 419474003, 232350006, 232347008, 4...","[19, 19, 19, 19, 19, 19, 19, 19, 19, 19]"
4,24,ad7c452d-c8e9-40ae-a5ed-90b7bd93d2ac,4c7ed821-8753-40f3-a18e-31feef7074ef,"[419474003, 232350006, 232347008, 418689008, 4...","[33, 33, 33, 33, 33]"
...,...,...,...,...,...
136,578,8bf8631f-2fd4-4dc7-af2b-c400499fedfc,90ea604b-e2bf-4ca0-a46b-dc480f2f2a03,"[419474003, 300913006]","[18, 18]"
137,580,c5d6bdfa-5554-4927-8fa8-794e5514cb56,e42aa828-ad33-404f-af29-f1f9f17bd7f5,[417532002],[42]
138,581,2a6d1e58-88eb-4be0-b6b4-59a471257c2e,f7ff5032-50cc-480e-90ca-848c85d6d014,"[419474003, 232347008, 418689008, 419263009, 4...","[56, 56, 56, 56, 56, 56, 56]"
139,588,e6ff4bf9-09c2-4976-aa84-cca142207cf8,6c760807-a6b7-4af4-8d50-f32325803448,"[300916003, 419474003, 232350006, 232347008, 4...","[16, 21, 21, 21, 21, 21, 21, 21]"
140,596,13b9a676-7cfd-4b7c-bdb6-43ec52b7c919,bbd17366-0801-45ee-8589-0f3eb31c7d0d,[419474003],[106]

In [24]:
df = pd.merge(df,df_allergies,how = 'outer',left_on='Id',right_on='PATIENT')

In [25]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,index,PATIENT,ALLERGY_ENCOUNTER,ALLERGY_CODE,Allergy_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,NaN,NaN,NaN,NaN,NaN
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,NaN,NaN,NaN,NaN,NaN
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,NaN,NaN,NaN,NaN,NaN
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,NaN,NaN,NaN,NaN,NaN
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,NaN,NaN,NaN,NaN,NaN
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,NaN,NaN,NaN,NaN,NaN
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,NaN,NaN,NaN,NaN,NaN
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,NaN,NaN,NaN,NaN,NaN
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,NaN,NaN,NaN,NaN,NaN

In [26]:
df.drop(columns= ['index'],axis=1,inplace=True)

In [27]:
df.drop(columns= ['PATIENT'],axis=1,inplace=True)

In [28]:
df.fillna(0,inplace=True)

In [29]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,ALLERGY_ENCOUNTER,ALLERGY_CODE,Allergy_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,0,0,0
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,0,0,0
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,0,0,0
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,0,0,0
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,0,0,0
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,0,0,0
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,0,0,0
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,0,0,0
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,0,0,0

In [30]:
df_careplans

,Id,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,REASONCODE,REASONDESCRIPTION
0,d2500b8c-e830-433a-8b9d-368d30741520,2010-01-23,2012-01-23,034e9e3b-2def-4559-bb2a-7850888ae060,d0c40d10-8d87-447e-836e-99d26ad52ea5,53950000,Respiratory therapy,10509002.0,Acute bronchitis (disorder)
1,07d9ddd8-dfa1-4e43-9bfe-39f63f4ace15,2011-05-13,2011-08-02,10339b10-3cd1-4ac3-ac13-ec26728cb592,e1ab4933-07a1-49f0-b4bd-05500919061d,53950000,Respiratory therapy,10509002.0,Acute bronchitis (disorder)
2,a3bb6e99-3b99-44b3-974c-e230b4511b5c,2011-12-31,2012-11-30,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,16300c56-a035-4126-a656-68c093da6dfc,53950000,Respiratory therapy,10509002.0,Acute bronchitis (disorder)
3,9f5284b7-425a-486a-b36e-ab818c018f2f,2016-12-29,2017-01-05,034e9e3b-2def-4559-bb2a-7850888ae060,3b639086-5fbc-4720-8c31-e8c8c0f1d660,53950000,Respiratory therapy,10509002.0,Acute bronchitis (disorder)
4,47ede16c-c216-4f81-a16b-0e858de9cdc3,2017-01-22,2017-02-12,10339b10-3cd1-4ac3-ac13-ec26728cb592,4ec8d55b-05fc-42a5-bfa3-1e233874a362,225358003,Wound care,284551006.0,Laceration of foot
...,...,...,...,...,...,...,...,...,...
3478,5998d466-9922-4a35-9277-7a902352ce48,1983-09-08,1983-09-29,fca3178e-fb68-41c3-8598-702d3ca68b96,9e9670e5-da7f-4111-98a6-21d5e0aadd86,91251008,Physical therapy procedure,70704007.0,Sprain of wrist
3479,3de3b598-ca98-4b98-947a-34e3e86630e6,1984-09-23,1984-11-22,fca3178e-fb68-41c3-8598-702d3ca68b96,8d7d70be-467d-430f-8497-25aa2c1276b8,385691007,Fracture care,263102004.0,Fracture subluxation of wrist
3480,6f02c458-e04f-429d-99ce-72626d87952d,1987-09-27,NaN,fca3178e-fb68-41c3-8598-702d3ca68b96,48ea35a8-37cd-41d2-86c1-7785b514c453,735984001,Heart failure self management plan,88805009.0,Chronic congestive heart failure (disorder)
3481,243de451-1e53-40fc-b4ae-e0ea730e4a0d,1990-03-15,NaN,fca3178e-fb68-41c3-8598-702d3ca68b96,aaee3543-3edb-40af-a276-3bb027cac0dc,736353004,Inpatient care plan (record artifact),NaN,NaN
3482,f7b75d85-fd8f-4c1b-bcfd-775e63a12490,1957-08-25,NaN,fc817953-cc8b-45db-9c85-7c0ced8fa90d,67960f0e-b9ac-4385-b739-b62c9bf5e67d,408869004,Musculoskeletal care,239873007.0,Osteoarthritis of knee

In [31]:
df_careplans.drop(['DESCRIPTION','REASONDESCRIPTION','Id','ENCOUNTER'],axis=1,inplace=True)

In [32]:
df_careplans

,START,STOP,PATIENT,CODE,REASONCODE
0,2010-01-23,2012-01-23,034e9e3b-2def-4559-bb2a-7850888ae060,53950000,10509002.0
1,2011-05-13,2011-08-02,10339b10-3cd1-4ac3-ac13-ec26728cb592,53950000,10509002.0
2,2011-12-31,2012-11-30,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,53950000,10509002.0
3,2016-12-29,2017-01-05,034e9e3b-2def-4559-bb2a-7850888ae060,53950000,10509002.0
4,2017-01-22,2017-02-12,10339b10-3cd1-4ac3-ac13-ec26728cb592,225358003,284551006.0
...,...,...,...,...,...
3478,1983-09-08,1983-09-29,fca3178e-fb68-41c3-8598-702d3ca68b96,91251008,70704007.0
3479,1984-09-23,1984-11-22,fca3178e-fb68-41c3-8598-702d3ca68b96,385691007,263102004.0
3480,1987-09-27,NaN,fca3178e-fb68-41c3-8598-702d3ca68b96,735984001,88805009.0
3481,1990-03-15,NaN,fca3178e-fb68-41c3-8598-702d3ca68b96,736353004,NaN
3482,1957-08-25,NaN,fc817953-cc8b-45db-9c85-7c0ced8fa90d,408869004,239873007.0

In [33]:
df_careplans.fillna(0,inplace=True)

In [34]:
df_careplans['Careplan_Time'] = 0.0

In [35]:
for i in range(len(df_careplans)):
    if df_careplans.STOP[i] == 0 :
        today = datetime.date.today()
        start = datetime.datetime.strptime(df_careplans.START[i],"%Y-%m-%d").date()
        age = today.year - start.year - ((today.month,today.day)<(start.month,start.day))
        if today.month>start.month :
            age = age + (today.month - start.month)/12
        else :
            age = age + (12 + today.month  - start.month)/12         
    else:
        start = datetime.datetime.strptime(df_careplans.START[i],"%Y-%m-%d").date()
        stop = datetime.datetime.strptime(df_careplans.STOP[i],"%Y-%m-%d").date()
        age = stop.year - start.year - ((stop.month,stop.day)<(start.month,start.day))
        if stop.month>start.month :
            age = age + (stop.month - start.month)/12
        else :
            age = age + (12 + stop.month - start.month)/12 
    df_careplans.Careplan_Time[i] = age

/tmp/ipykernel_25837/2468471441.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_careplans.Careplan_Time[i] = age

In [36]:
df_careplans.drop(['START','STOP'],axis=1,inplace=True)

In [37]:
df_careplans.sort_values('PATIENT',inplace = True)

In [38]:
df_careplans.reset_index(inplace=True)

In [39]:
df_careplans

,index,PATIENT,CODE,REASONCODE,Careplan_Time
0,2086,0042862c-9889-4a2e-b782-fac1e540ecb4,53950000,10509002.0,1.000000
1,3244,0047123f-12e7-486c-82df-53b3a450e365,53950000,10509002.0,1.000000
2,502,010d4a3a-2316-45ed-ae15-16f01c611674,443402002,59621000.0,5.333333
3,936,0149d553-f571-4e99-867e-fcb9625d07c2,133901003,403190006.0,0.083333
4,935,0149d553-f571-4e99-867e-fcb9625d07c2,134435003,72892002.0,0.583333
...,...,...,...,...,...
3478,2275,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,134435003,72892002.0,0.583333
3479,2886,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,134435003,72892002.0,0.583333
3480,2885,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,134435003,72892002.0,0.583333
3481,2497,ffcfa457-00c2-4405-9837-ac2781549c7e,53950000,10509002.0,1.000000
3482,2498,ffcfa457-00c2-4405-9837-ac2781549c7e,91251008,70704007.0,0.083333

In [40]:
prev = 0 
dict1 = {}
dict2 = {}
val=0
for i in range(1,len(df_careplans)):
    if df_careplans.PATIENT[i] == df_careplans.PATIENT[prev] :
        #print(i)
        continue
    else :
        list1 = df_careplans.REASONCODE[prev:i].values
        list2 = df_careplans.Careplan_Time[prev:i].values
        dict1[df_careplans.PATIENT[prev]] = list1
        dict2[df_careplans.PATIENT[prev]] = list2
        prev = i
        if i == len(df_careplans)-1 :
            val=1
if val==1:
    list1 = [df_careplans.REASONCODE[prev]]
    list2 = [df_careplans.Careplan_Time[prev]]
    dict1[df_careplans.PATIENT[prev]] = list1
    dict2[df_careplans.PATIENT[prev]] = list2
else :
    list1 = [df_careplans.REASONCODE[prev:len(df_careplans)]]
    list2 = [df_careplans.Careplan_Time[prev:len(df_careplans)]]
    dict1[df_careplans.PATIENT[prev]] = list1
    dict2[df_careplans.PATIENT[prev]] = list2

In [41]:
prev = 0
for i in range(1,len(df_careplans)):
    if df_careplans.PATIENT[i] == df_careplans.PATIENT[prev] :
        df_careplans.drop(i,axis=0,inplace=True)
    else:
        prev=i

In [42]:
df_careplans['REASONCODE'] = df_careplans['REASONCODE'].astype(object)
df_careplans['Careplan_Time'] = df_careplans['Careplan_Time'].astype(object)

In [43]:
df_careplans.reset_index(inplace=True)

In [44]:
for i in range(len(df_careplans)):
    df_careplans.REASONCODE[i]= dict1[df_careplans.PATIENT[i]]
    df_careplans.Careplan_Time[i] = dict2[df_careplans.PATIENT[i]]

/tmp/ipykernel_25837/3418505343.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_careplans.REASONCODE[i]= dict1[df_careplans.PATIENT[i]]
/tmp/ipykernel_25837/3418505343.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_careplans.Careplan_Time[i] = dict2[df_careplans.PATIENT[i]]

In [45]:
df_careplans.rename(columns = {'CODE':'Careplan_CODE', 'REASONCODE':'Careplan_REASONCODE'}, inplace = True)

In [46]:
df_careplans

,level_0,index,PATIENT,Careplan_CODE,Careplan_REASONCODE,Careplan_Time
0,0,2086,0042862c-9889-4a2e-b782-fac1e540ecb4,53950000,[10509002.0],[1.0]
1,1,3244,0047123f-12e7-486c-82df-53b3a450e365,53950000,[10509002.0],[1.0]
2,2,502,010d4a3a-2316-45ed-ae15-16f01c611674,443402002,[59621000.0],[5.333333333333333]
3,3,936,0149d553-f571-4e99-867e-fcb9625d07c2,133901003,"[403190006.0, 72892002.0, 15777000.0]","[0.08333333333333333, 0.5833333333333334, 20.25]"
4,6,251,01e1f394-7219-4189-bceb-3cbd90cff90b,134435003,"[72892002.0, 15777000.0, 403191005.0, 72892002.0]","[0.5833333333333334, 17.083333333333332, 0.083..."
...,...,...,...,...,...,...
1049,3468,2377,ff02f237-fedb-453b-85b1-ebfc2609c312,443402002,"[59621000.0, 284551006.0, 403190006.0]","[4.083333333333333, 1.0, 0.08333333333333333]"
1050,3471,1169,ff3714ac-c7e3-4910-905e-2a321eb28144,91251008,"[44465007.0, 59621000.0]","[0.08333333333333333, 6.333333333333333]"
1051,3473,2277,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,225358003,"[370247008.0, 10509002.0, 55680006.0, 72892002...","[0.08333333333333333, 0.08333333333333333, 13...."
1052,3479,2886,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,134435003,"[72892002.0, 72892002.0]","[0.5833333333333334, 0.5833333333333334]"
1053,3481,2497,ffcfa457-00c2-4405-9837-ac2781549c7e,53950000,"[[10509002.0, 70704007.0]]","[[1.0, 0.08333333333333333]]"

In [47]:
df_careplans.drop(['level_0','index'],axis=1,inplace=True)

In [48]:
df_careplans

,PATIENT,Careplan_CODE,Careplan_REASONCODE,Careplan_Time
0,0042862c-9889-4a2e-b782-fac1e540ecb4,53950000,[10509002.0],[1.0]
1,0047123f-12e7-486c-82df-53b3a450e365,53950000,[10509002.0],[1.0]
2,010d4a3a-2316-45ed-ae15-16f01c611674,443402002,[59621000.0],[5.333333333333333]
3,0149d553-f571-4e99-867e-fcb9625d07c2,133901003,"[403190006.0, 72892002.0, 15777000.0]","[0.08333333333333333, 0.5833333333333334, 20.25]"
4,01e1f394-7219-4189-bceb-3cbd90cff90b,134435003,"[72892002.0, 15777000.0, 403191005.0, 72892002.0]","[0.5833333333333334, 17.083333333333332, 0.083..."
...,...,...,...,...
1049,ff02f237-fedb-453b-85b1-ebfc2609c312,443402002,"[59621000.0, 284551006.0, 403190006.0]","[4.083333333333333, 1.0, 0.08333333333333333]"
1050,ff3714ac-c7e3-4910-905e-2a321eb28144,91251008,"[44465007.0, 59621000.0]","[0.08333333333333333, 6.333333333333333]"
1051,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,225358003,"[370247008.0, 10509002.0, 55680006.0, 72892002...","[0.08333333333333333, 0.08333333333333333, 13...."
1052,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,134435003,"[72892002.0, 72892002.0]","[0.5833333333333334, 0.5833333333333334]"
1053,ffcfa457-00c2-4405-9837-ac2781549c7e,53950000,"[[10509002.0, 70704007.0]]","[[1.0, 0.08333333333333333]]"

In [49]:
df = pd.merge(df,df_careplans,how = 'outer',left_on='Id',right_on='PATIENT')

In [50]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,ALLERGY_ENCOUNTER,ALLERGY_CODE,Allergy_Time,PATIENT,Careplan_CODE,Careplan_REASONCODE,Careplan_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,0,0,0,NaN,NaN,NaN,NaN
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,0,0,0,034e9e3b-2def-4559-bb2a-7850888ae060,53950000.0,"[10509002.0, 10509002.0]","[3.0, 0.08333333333333333]"
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,0,0,0,10339b10-3cd1-4ac3-ac13-ec26728cb592,225358003.0,"[284551006.0, 10509002.0, 10509002.0]","[0.08333333333333333, 0.25, 0.08333333333333333]"
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,0,0,0,NaN,NaN,NaN,NaN
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,0,0,0,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,53950000.0,[10509002.0],[0.9166666666666666]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,0,0,0,023a7d29-32b3-4db5-89c8-b88bd7582ec0,53950000.0,"[10509002.0, 55822004.0, 15777000.0]","[0.16666666666666666, 57.666666666666664, 62.5]"
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,0,0,0,NaN,NaN,NaN,NaN
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,0,0,0,6d048a56-edb8-4f29-891d-7a84d75a8e78,386257007.0,"[26929004.0, 233678006.0, 15777000.0, 10509002.0]","[27.083333333333332, 103.16666666666667, 62.66..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,0,0,0,fca3178e-fb68-41c3-8598-702d3ca68b96,736353004.0,"[0.0, 88805009.0, 263102004.0, 15777000.0, 707...","[31.666666666666668, 34.166666666666664, 0.166..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,0,0,0,fc817953-cc8b-45db-9c85-7c0ced8fa90d,408869004.0,[239873007.0],[64.25]

In [51]:
df.drop(columns = ['PATIENT'],axis=1,inplace=True)
df.fillna(0,inplace=True)

In [52]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,ALLERGY_ENCOUNTER,ALLERGY_CODE,Allergy_Time,Careplan_CODE,Careplan_REASONCODE,Careplan_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,0,0,0,0.0,0,0
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,0,0,0,53950000.0,"[10509002.0, 10509002.0]","[3.0, 0.08333333333333333]"
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,0,0,0,225358003.0,"[284551006.0, 10509002.0, 10509002.0]","[0.08333333333333333, 0.25, 0.08333333333333333]"
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,0,0,0,0.0,0,0
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,0,0,0,53950000.0,[10509002.0],[0.9166666666666666]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,0,0,0,53950000.0,"[10509002.0, 55822004.0, 15777000.0]","[0.16666666666666666, 57.666666666666664, 62.5]"
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,0,0,0,0.0,0,0
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,0,0,0,386257007.0,"[26929004.0, 233678006.0, 15777000.0, 10509002.0]","[27.083333333333332, 103.16666666666667, 62.66..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,0,0,0,736353004.0,"[0.0, 88805009.0, 263102004.0, 15777000.0, 707...","[31.666666666666668, 34.166666666666664, 0.166..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,0,0,0,408869004.0,[239873007.0],[64.25]

In [53]:
df_conditions

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION
0,2001-05-01,NaN,1d604da9-9a81-4ba9-80c2-de3375d59b40,8f104aa7-4ca9-4473-885a-bba2437df588,40055000,Chronic sinusitis (disorder)
1,2011-08-09,2011-08-16,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,9d35ec9f-352a-4629-92ef-38eae38437e7,444814009,Viral sinusitis (disorder)
2,2011-11-16,2011-11-26,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,ae7555a9-eaff-4c09-98a7-21bc6ed1b1fd,195662009,Acute viral pharyngitis (disorder)
3,2011-05-13,2011-05-27,10339b10-3cd1-4ac3-ac13-ec26728cb592,e1ab4933-07a1-49f0-b4bd-05500919061d,10509002,Acute bronchitis (disorder)
4,2011-02-06,2011-02-14,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,b8f76eba-7795-4dcd-a544-f27ac2ef3d46,195662009,Acute viral pharyngitis (disorder)
...,...,...,...,...,...,...
8371,1984-12-29,NaN,fc817953-cc8b-45db-9c85-7c0ced8fa90d,87cfa8a4-126e-4c58-a839-e8b725828d0f,64859006,Osteoporosis (disorder)
8372,1988-08-24,NaN,fc817953-cc8b-45db-9c85-7c0ced8fa90d,97c0226c-92b4-4e78-b81f-4225d8473ba3,40055000,Chronic sinusitis (disorder)
8373,2009-08-08,NaN,fc817953-cc8b-45db-9c85-7c0ced8fa90d,1c91f459-adf0-4fe6-abdb-d248a91b9d85,230690007,Stroke
8374,2010-11-18,2010-11-25,fc817953-cc8b-45db-9c85-7c0ced8fa90d,8aabb13d-f4ac-4037-95ab-00e0e48a1b34,444814009,Viral sinusitis (disorder)
8375,2012-04-23,2012-05-14,fc817953-cc8b-45db-9c85-7c0ced8fa90d,eab80b1b-de1d-4281-9dae-e8a7036a815f,444814009,Viral sinusitis (disorder)

In [54]:
df_conditions.fillna(0,inplace=True)

In [55]:
df_conditions.drop(['ENCOUNTER'],axis=1,inplace=True)

In [56]:
df_conditions['Condition_Time'] = 0.0

In [57]:
df_conditions.PATIENT.nunique()

1152

In [58]:
for i in range(len(df_conditions)):
    if df_conditions.STOP[i] == 0 :
        today = datetime.date.today()
        start = datetime.datetime.strptime(df_conditions.START[i],"%Y-%m-%d").date()
        age = today.year - start.year - ((today.month,today.day)<(start.month,start.day))
        if today.month>start.month :
            age = age + (today.month - start.month)/12
        else :
            age = age + (12 + today.month  - start.month)/12         
    else:
        start = datetime.datetime.strptime(df_conditions.START[i],"%Y-%m-%d").date()
        stop = datetime.datetime.strptime(df_conditions.STOP[i],"%Y-%m-%d").date()
        age = stop.year - start.year - ((stop.month,stop.day)<(start.month,start.day))
        if stop.month>start.month :
            age = age + (stop.month - start.month)/12
        else :
            age = age + (12 + stop.month - start.month)/12 
    df_conditions.Condition_Time[i] = age

/tmp/ipykernel_25837/1522751482.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_conditions.Condition_Time[i] = age

In [59]:
df_conditions.drop(['START','STOP'],axis=1,inplace=True)

In [60]:
df_conditions

,PATIENT,CODE,DESCRIPTION,Condition_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,40055000,Chronic sinusitis (disorder),20.500000
1,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,444814009,Viral sinusitis (disorder),1.000000
2,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,195662009,Acute viral pharyngitis (disorder),1.000000
3,10339b10-3cd1-4ac3-ac13-ec26728cb592,10509002,Acute bronchitis (disorder),1.000000
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,195662009,Acute viral pharyngitis (disorder),1.000000
...,...,...,...,...
8371,fc817953-cc8b-45db-9c85-7c0ced8fa90d,64859006,Osteoporosis (disorder),36.916667
8372,fc817953-cc8b-45db-9c85-7c0ced8fa90d,40055000,Chronic sinusitis (disorder),33.250000
8373,fc817953-cc8b-45db-9c85-7c0ced8fa90d,230690007,Stroke,12.250000
8374,fc817953-cc8b-45db-9c85-7c0ced8fa90d,444814009,Viral sinusitis (disorder),1.000000
8375,fc817953-cc8b-45db-9c85-7c0ced8fa90d,444814009,Viral sinusitis (disorder),0.083333

In [62]:
prev = 0 
dict1 = {}
dict2 = {}
dict3 = {}
val=0
for i in range(1,len(df_conditions)):
    if df_conditions.PATIENT[i] == df_conditions.PATIENT[prev] :
        #print(i)
        continue
    else :
        list1 = df_conditions.CODE[prev:i].values
        list2 = df_conditions.Condition_Time[prev:i].values
        list3 = df_conditions.DESCRIPTION[prev:i].values
        dict1[df_conditions.PATIENT[prev]] = list1
        dict2[df_conditions.PATIENT[prev]] = list2
        dict3[df_conditions.PATIENT[prev]] = list3
        prev = i
        if i == len(df_conditions)-1 :
            val=1
if val==1:
    list1 = [df_conditions.CODE[prev]]
    list2 = [df_conditions.Condition_Time[prev]]
    list3 = [df_conditions.DESCRIPTION[prev]]
    dict1[df_conditions.PATIENT[prev]] = list1
    dict2[df_conditions.PATIENT[prev]] = list2
    dict3[df_conditions.PATIENT[prev]] = list3
else :
    list1 = [df_conditions.CODE[prev:len(df_conditions)]]
    list2 = [df_conditions.Condition_Time[prev:len(df_conditions)]]
    list3 = [df_conditions.DESCRIPTION[prev:len(df_conditions)]]
    dict1[df_conditions.PATIENT[prev]] = list1
    dict2[df_conditions.PATIENT[prev]] = list2
    dict3[df_conditions.PATIENT[prev]] = list3

In [63]:
len(dict2)

1152

In [64]:
prev = 0
for i in range(1,len(df_conditions)):
    if df_conditions.PATIENT[i] == df_conditions.PATIENT[prev] :
        df_conditions.drop(i,axis=0,inplace=True)
    else:
        prev=i

In [65]:
df_conditions.sort_values('PATIENT',inplace=True)

In [66]:
df_conditions

,PATIENT,CODE,DESCRIPTION,Condition_Time
5451,00185faa-2760-4218-9bf5-db301acf8274,195662009,Acute viral pharyngitis (disorder),1.000000
5075,0042862c-9889-4a2e-b782-fac1e540ecb4,195662009,Acute viral pharyngitis (disorder),0.083333
7800,0047123f-12e7-486c-82df-53b3a450e365,444814009,Viral sinusitis (disorder),0.083333
7804,0047123f-12e7-486c-82df-53b3a450e365,428251008,History of appendectomy,8.833333
1222,010d4a3a-2316-45ed-ae15-16f01c611674,195662009,Acute viral pharyngitis (disorder),0.083333
...,...,...,...,...
5770,ff02f237-fedb-453b-85b1-ebfc2609c312,444814009,Viral sinusitis (disorder),0.083333
2881,ff3714ac-c7e3-4910-905e-2a321eb28144,128613002,Seizure disorder,24.500000
5504,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,40055000,Chronic sinusitis (disorder),39.416667
6985,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,74400008,Appendicitis,45.083333
6054,ffcfa457-00c2-4405-9837-ac2781549c7e,195662009,Acute viral pharyngitis (disorder),1.000000

In [67]:
df_conditions['CODE'] = df_conditions['CODE'].astype(object)
df_conditions['Condition_Time'] = df_conditions['Condition_Time'].astype(object) 
df_conditions['DESCRIPTION'] = df_conditions['DESCRIPTION'].astype(object)

In [68]:
df_conditions.reset_index(inplace=True)

In [69]:
prev = 0
for i in range(1,len(df_conditions)):
    if df_conditions.PATIENT[i] == df_conditions.PATIENT[prev] :
        df_conditions.drop(i,axis=0,inplace=True)
    else:
        prev=i

In [70]:
df_conditions

,index,PATIENT,CODE,DESCRIPTION,Condition_Time
0,5451,00185faa-2760-4218-9bf5-db301acf8274,195662009,Acute viral pharyngitis (disorder),1.0
1,5075,0042862c-9889-4a2e-b782-fac1e540ecb4,195662009,Acute viral pharyngitis (disorder),0.083333
2,7800,0047123f-12e7-486c-82df-53b3a450e365,444814009,Viral sinusitis (disorder),0.083333
4,1222,010d4a3a-2316-45ed-ae15-16f01c611674,195662009,Acute viral pharyngitis (disorder),0.083333
5,2268,0149d553-f571-4e99-867e-fcb9625d07c2,162864005,Body mass index 30+ - obesity (finding),33.416667
...,...,...,...,...,...
1395,5770,ff02f237-fedb-453b-85b1-ebfc2609c312,444814009,Viral sinusitis (disorder),0.083333
1396,2881,ff3714ac-c7e3-4910-905e-2a321eb28144,128613002,Seizure disorder,24.5
1397,5504,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,40055000,Chronic sinusitis (disorder),39.416667
1398,6985,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,74400008,Appendicitis,45.083333
1399,6054,ffcfa457-00c2-4405-9837-ac2781549c7e,195662009,Acute viral pharyngitis (disorder),1.0

In [71]:
df_conditions.reset_index(inplace=True)

In [72]:
for i in range(len(df_conditions)):
    df_conditions.CODE[i]= dict1[df_conditions.PATIENT[i]]
    df_conditions.Condition_Time[i] = dict2[df_conditions.PATIENT[i]]
    df_conditions.DESCRIPTION[i] = dict3[df_conditions.PATIENT[i]]

/tmp/ipykernel_25837/3415871571.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_conditions.CODE[i]= dict1[df_conditions.PATIENT[i]]
/tmp/ipykernel_25837/3415871571.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_conditions.Condition_Time[i] = dict2[df_conditions.PATIENT[i]]
/tmp/ipykernel_25837/3415871571.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_conditions.DESCRIPTION[i] = dict3[df_conditions.PATIENT[i]]

In [73]:
df_conditions

,level_0,index,PATIENT,CODE,DESCRIPTION,Condition_Time
0,0,5451,00185faa-2760-4218-9bf5-db301acf8274,"[195662009, 43878008, 82423001, 12417100011910...","[Acute viral pharyngitis (disorder), Streptoco...","[1.0, 1.0, 3.9166666666666665, 3.0833333333333..."
1,1,5075,0042862c-9889-4a2e-b782-fac1e540ecb4,"[195662009, 195662009, 65363002, 10509002]","[Acute viral pharyngitis (disorder), Acute vir...","[0.08333333333333333, 1.0, 1.0, 1.0]"
2,2,7800,0047123f-12e7-486c-82df-53b3a450e365,"[428251008, 444814009, 444814009]","[History of appendectomy, Viral sinusitis (dis...","[8.833333333333334, 0.08333333333333333, 1.0]"
3,4,1222,010d4a3a-2316-45ed-ae15-16f01c611674,"[195662009, 59621000, 195662009]","[Acute viral pharyngitis (disorder), Hypertens...","[0.08333333333333333, 5.333333333333333, 1.0]"
4,5,2268,0149d553-f571-4e99-867e-fcb9625d07c2,"[162864005, 408512008, 15777000, 271737000, 72...","[Body mass index 30+ - obesity (finding), Body...","[33.416666666666664, 27.333333333333332, 20.25..."
...,...,...,...,...,...,...
1147,1395,5770,ff02f237-fedb-453b-85b1-ebfc2609c312,"[444814009, 403190006, 284551006, 59621000]","[Viral sinusitis (disorder), First degree burn...","[0.08333333333333333, 0.08333333333333333, 1.0..."
1148,1396,2881,ff3714ac-c7e3-4910-905e-2a321eb28144,"[128613002, 703151001, 444814009, 59621000, 44...","[Seizure disorder, History of single seizure (...","[24.5, 24.5, 1.0, 6.333333333333333, 0.0833333..."
1149,1397,5504,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,"[40055000, 196416002, 124171000119105, 8242300...","[Chronic sinusitis (disorder), Impacted molars...","[39.416666666666664, 30.333333333333332, 30.08..."
1150,1398,6985,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,"[74400008, 428251008, 162864005, 72892002, 728...","[Appendicitis, History of appendectomy, Body m...","[45.083333333333336, 45.083333333333336, 37.91..."
1151,1399,6054,ffcfa457-00c2-4405-9837-ac2781549c7e,"[195662009, 10509002, 70704007, 65363002, 4448...","[Acute viral pharyngitis (disorder), Acute bro...","[1.0, 1.0, 0.08333333333333333, 0.25, 1.0]"

In [74]:
df_conditions.drop(['index','level_0'],axis=1,inplace=True)
df_conditions.rename(columns={'CODE':'Condition_CODE','DESCRIPTION':'Condition_DESCRIPTION'},inplace=True)

In [75]:
df = pd.merge(df,df_conditions,how = 'outer',left_on='Id',right_on='PATIENT')

In [76]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,ALLERGY_ENCOUNTER,ALLERGY_CODE,Allergy_Time,Careplan_CODE,Careplan_REASONCODE,Careplan_Time,PATIENT,Condition_CODE,Condition_DESCRIPTION,Condition_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,0,0,0,0.0,0,0,1d604da9-9a81-4ba9-80c2-de3375d59b40,[444814009],[Viral sinusitis (disorder)],[0.08333333333333333]
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,0,0,0,53950000.0,"[10509002.0, 10509002.0]","[3.0, 0.08333333333333333]",034e9e3b-2def-4559-bb2a-7850888ae060,[10509002],[Acute bronchitis (disorder)],[0.08333333333333333]
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,0,0,0,225358003.0,"[284551006.0, 10509002.0, 10509002.0]","[0.08333333333333333, 0.25, 0.08333333333333333]",10339b10-3cd1-4ac3-ac13-ec26728cb592,"[284551006, 10509002]","[Laceration of foot, Acute bronchitis (disorder)]","[0.08333333333333333, 0.08333333333333333]"
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,0,0,0,0.0,0,0,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,[43878008],[Streptococcal sore throat (disorder)],[1.0]
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,0,0,0,53950000.0,[10509002.0],[0.9166666666666666],f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,[195662009],[Acute viral pharyngitis (disorder)],[1.0]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,0,0,0,53950000.0,"[10509002.0, 55822004.0, 15777000.0]","[0.16666666666666666, 57.666666666666664, 62.5]",023a7d29-32b3-4db5-89c8-b88bd7582ec0,"[15777000, 271737000, 55822004, 40055000, 4943...","[Prediabetes, Anemia (disorder), Hyperlipidemi...","[62.5, 62.5, 57.75, 48.75, 36.583333333333336,..."
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,0,0,0,0.0,0,0,1fc8dafd-90e5-44d6-9179-81156c0ea083,"[444814009, 444814009, 43878008]","[Viral sinusitis (disorder), Viral sinusitis (...","[1.0, 1.0, 1.0]"
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,0,0,0,386257007.0,"[26929004.0, 233678006.0, 15777000.0, 10509002.0]","[27.083333333333332, 103.16666666666667, 62.66...",6d048a56-edb8-4f29-891d-7a84d75a8e78,"[19169002, 162864005, 79586000, 15777000, 2548...","[Miscarriage in first trimester, Body mass ind...","[76.83333333333333, 75.83333333333333, 74.3333..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,0,0,0,736353004.0,"[0.0, 88805009.0, 263102004.0, 15777000.0, 707...","[31.666666666666668, 34.166666666666664, 0.166...",fca3178e-fb68-41c3-8598-702d3ca68b96,"[19169002, 162864005, 40055000, 15777000, 2717...","[Miscarriage in first trimester, Body mass ind...","[86.25, 82.0, 71.5, 56.166666666666664, 55.166..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,0,0,0,408869004.0,[239873007.0],[64.25],fc817953-cc8b-45db-9c85-7c0ced8fa90d,"[[19169002, 239873007, 64859006, 40055000, 230...","[[Miscarriage in first trimester, Osteoarthrit...","[[64.83333333333333, 64.25, 36.916666666666664..."

In [77]:
df.drop(['PATIENT'],axis=1,inplace=True)

In [78]:
df.fillna(0,inplace=True)

In [79]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,ALLERGY_ENCOUNTER,ALLERGY_CODE,Allergy_Time,Careplan_CODE,Careplan_REASONCODE,Careplan_Time,Condition_CODE,Condition_DESCRIPTION,Condition_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,0,0,0,0.0,0,0,[444814009],[Viral sinusitis (disorder)],[0.08333333333333333]
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,0,0,0,53950000.0,"[10509002.0, 10509002.0]","[3.0, 0.08333333333333333]",[10509002],[Acute bronchitis (disorder)],[0.08333333333333333]
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,0,0,0,225358003.0,"[284551006.0, 10509002.0, 10509002.0]","[0.08333333333333333, 0.25, 0.08333333333333333]","[284551006, 10509002]","[Laceration of foot, Acute bronchitis (disorder)]","[0.08333333333333333, 0.08333333333333333]"
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,0,0,0,0.0,0,0,[43878008],[Streptococcal sore throat (disorder)],[1.0]
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,0,0,0,53950000.0,[10509002.0],[0.9166666666666666],[195662009],[Acute viral pharyngitis (disorder)],[1.0]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,0,0,0,53950000.0,"[10509002.0, 55822004.0, 15777000.0]","[0.16666666666666666, 57.666666666666664, 62.5]","[15777000, 271737000, 55822004, 40055000, 4943...","[Prediabetes, Anemia (disorder), Hyperlipidemi...","[62.5, 62.5, 57.75, 48.75, 36.583333333333336,..."
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,0,0,0,0.0,0,0,"[444814009, 444814009, 43878008]","[Viral sinusitis (disorder), Viral sinusitis (...","[1.0, 1.0, 1.0]"
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,0,0,0,386257007.0,"[26929004.0, 233678006.0, 15777000.0, 10509002.0]","[27.083333333333332, 103.16666666666667, 62.66...","[19169002, 162864005, 79586000, 15777000, 2548...","[Miscarriage in first trimester, Body mass ind...","[76.83333333333333, 75.83333333333333, 74.3333..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,0,0,0,736353004.0,"[0.0, 88805009.0, 263102004.0, 15777000.0, 707...","[31.666666666666668, 34.166666666666664, 0.166...","[19169002, 162864005, 40055000, 15777000, 2717...","[Miscarriage in first trimester, Body mass ind...","[86.25, 82.0, 71.5, 56.166666666666664, 55.166..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,0,0,0,408869004.0,[239873007.0],[64.25],"[[19169002, 239873007, 64859006, 40055000, 230...","[[Miscarriage in first trimester, Osteoarthrit...","[[64.83333333333333, 64.25, 36.916666666666664..."

In [80]:
df_devices.PATIENT.nunique()

74

In [81]:
df_devices

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,UDI
0,2001-07-04T08:42:44Z,NaN,d49f748f-928d-40e8-92c8-73e4c5679711,2500b8bd-dc98-44ef-a252-22dc4f81d61b,72506001,Implantable defibrillator device (physical ob...,(01)67677988606464(11)010613(17)260628(10)2882...
1,2010-10-24T05:28:51Z,NaN,e05dd037-e45f-434a-946d-5c9076a2f596,83cda5b1-4653-4327-a81c-14c4af434e95,72506001,Implantable defibrillator device (physical ob...,(01)20180595258346(11)101003(17)351018(10)1391...
2,2017-06-04T11:11:47Z,NaN,0f5646bc-a156-4ec0-9252-5b592e3d3184,7302a9ce-5845-456d-af2e-bca7a1fc387f,72506001,Implantable defibrillator device (physical ob...,(01)87988924478445(11)170514(17)420529(10)4143...
3,1989-01-17T18:12:03Z,NaN,44c8b4c8-4457-4ba0-94b6-285ef327a249,7db01f61-e637-4e41-9067-0168524c991f,705643001,Coronary artery stent (physical object),(01)30831895165484(11)881227(17)140111(10)7597...
4,1973-07-19T04:25:46Z,NaN,89752052-a38b-45f0-a590-3950bbb67bec,e73fe5e1-1b13-4368-b52f-673cbf1f3540,72506001,Implantable defibrillator device (physical ob...,(01)71767722231489(11)730628(17)980713(10)6519...
...,...,...,...,...,...,...,...
73,1997-01-27T14:31:51Z,NaN,9bebd912-a12b-4a83-a02c-f510587246df,b9bca2fc-a297-49e8-a030-75cff5d83737,72506001,Implantable defibrillator device (physical ob...,(01)18759008756217(11)970106(17)220121(10)5934...
74,1994-02-08T13:04:22Z,NaN,9c4c1885-35af-48b9-a09f-4ea448d40d75,c399d6f4-b549-46c6-b0e8-a8c0398f6db9,706004007,Implantable cardiac pacemaker (physical object),(01)78045789271756(11)940118(17)190202(10)5321...
75,2018-11-04T07:02:15Z,NaN,2f76733b-933c-4cc5-aea2-53799158c8cc,86dd4b03-b0ca-41ee-824c-7fb1e9da953e,706004007,Implantable cardiac pacemaker (physical object),(01)77289394758969(11)181014(17)431029(10)3787...
76,1955-02-01T13:04:22Z,NaN,87f05059-de42-4630-a35b-edb53d880640,231bb53a-7698-454f-b348-bebc2cc17427,705643001,Coronary artery stent (physical object),(01)81833763907543(11)550111(17)800126(10)1912...
77,1988-05-17T13:04:22Z,NaN,023a7d29-32b3-4db5-89c8-b88bd7582ec0,f28bf78b-4159-49e9-81f9-65d36e26c5a7,706004007,Implantable cardiac pacemaker (physical object),(01)23971141656665(11)880426(17)130511(10)7167...

In [82]:
df_devices.fillna(0,inplace=True)

In [83]:
df_devices.drop(['ENCOUNTER','DESCRIPTION'],axis=1,inplace=True)

In [84]:
df_devices

,START,STOP,PATIENT,CODE,UDI
0,2001-07-04T08:42:44Z,0.0,d49f748f-928d-40e8-92c8-73e4c5679711,72506001,(01)67677988606464(11)010613(17)260628(10)2882...
1,2010-10-24T05:28:51Z,0.0,e05dd037-e45f-434a-946d-5c9076a2f596,72506001,(01)20180595258346(11)101003(17)351018(10)1391...
2,2017-06-04T11:11:47Z,0.0,0f5646bc-a156-4ec0-9252-5b592e3d3184,72506001,(01)87988924478445(11)170514(17)420529(10)4143...
3,1989-01-17T18:12:03Z,0.0,44c8b4c8-4457-4ba0-94b6-285ef327a249,705643001,(01)30831895165484(11)881227(17)140111(10)7597...
4,1973-07-19T04:25:46Z,0.0,89752052-a38b-45f0-a590-3950bbb67bec,72506001,(01)71767722231489(11)730628(17)980713(10)6519...
...,...,...,...,...,...
73,1997-01-27T14:31:51Z,0.0,9bebd912-a12b-4a83-a02c-f510587246df,72506001,(01)18759008756217(11)970106(17)220121(10)5934...
74,1994-02-08T13:04:22Z,0.0,9c4c1885-35af-48b9-a09f-4ea448d40d75,706004007,(01)78045789271756(11)940118(17)190202(10)5321...
75,2018-11-04T07:02:15Z,0.0,2f76733b-933c-4cc5-aea2-53799158c8cc,706004007,(01)77289394758969(11)181014(17)431029(10)3787...
76,1955-02-01T13:04:22Z,0.0,87f05059-de42-4630-a35b-edb53d880640,705643001,(01)81833763907543(11)550111(17)800126(10)1912...
77,1988-05-17T13:04:22Z,0.0,023a7d29-32b3-4db5-89c8-b88bd7582ec0,706004007,(01)23971141656665(11)880426(17)130511(10)7167...

In [85]:
df_devices['Device_Time'] = 0.0

In [86]:
for i in range(len(df_devices)):
    str1 = df_devices.START[i]
    df_devices.START[i] = str1[:10]

/tmp/ipykernel_25837/4118234089.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_devices.START[i] = str1[:10]

In [87]:
df_devices

,START,STOP,PATIENT,CODE,UDI,Device_Time
0,2001-07-04,0.0,d49f748f-928d-40e8-92c8-73e4c5679711,72506001,(01)67677988606464(11)010613(17)260628(10)2882...,0.0
1,2010-10-24,0.0,e05dd037-e45f-434a-946d-5c9076a2f596,72506001,(01)20180595258346(11)101003(17)351018(10)1391...,0.0
2,2017-06-04,0.0,0f5646bc-a156-4ec0-9252-5b592e3d3184,72506001,(01)87988924478445(11)170514(17)420529(10)4143...,0.0
3,1989-01-17,0.0,44c8b4c8-4457-4ba0-94b6-285ef327a249,705643001,(01)30831895165484(11)881227(17)140111(10)7597...,0.0
4,1973-07-19,0.0,89752052-a38b-45f0-a590-3950bbb67bec,72506001,(01)71767722231489(11)730628(17)980713(10)6519...,0.0
...,...,...,...,...,...,...
73,1997-01-27,0.0,9bebd912-a12b-4a83-a02c-f510587246df,72506001,(01)18759008756217(11)970106(17)220121(10)5934...,0.0
74,1994-02-08,0.0,9c4c1885-35af-48b9-a09f-4ea448d40d75,706004007,(01)78045789271756(11)940118(17)190202(10)5321...,0.0
75,2018-11-04,0.0,2f76733b-933c-4cc5-aea2-53799158c8cc,706004007,(01)77289394758969(11)181014(17)431029(10)3787...,0.0
76,1955-02-01,0.0,87f05059-de42-4630-a35b-edb53d880640,705643001,(01)81833763907543(11)550111(17)800126(10)1912...,0.0
77,1988-05-17,0.0,023a7d29-32b3-4db5-89c8-b88bd7582ec0,706004007,(01)23971141656665(11)880426(17)130511(10)7167...,0.0

In [88]:
for i in range(len(df_devices)):
    if df_devices.STOP[i] == 0 :
        today = datetime.date.today()
        start = datetime.datetime.strptime(df_devices.START[i],"%Y-%m-%d").date()
        age = today.year - start.year - ((today.month,today.day)<(start.month,start.day))
        if today.month>start.month :
            age = age + (today.month - start.month)/12
        else :
            age = age + (12 + today.month  - start.month)/12         
    else:
        start = datetime.datetime.strptime(df_devices.START[i],"%Y-%m-%d").date()
        stop = datetime.datetime.strptime(df_devices.STOP[i],"%Y-%m-%d").date()
        age = stop.year - start.year - ((stop.month,stop.day)<(start.month,start.day))
        if stop.month>start.month :
            age = age + (stop.month - start.month)/12
        else :
            age = age + (12 + stop.month - start.month)/12 
    df_devices.Device_Time[i] = age

/tmp/ipykernel_25837/1582467949.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_devices.Device_Time[i] = age

In [89]:
df_devices

,START,STOP,PATIENT,CODE,UDI,Device_Time
0,2001-07-04,0.0,d49f748f-928d-40e8-92c8-73e4c5679711,72506001,(01)67677988606464(11)010613(17)260628(10)2882...,20.333333
1,2010-10-24,0.0,e05dd037-e45f-434a-946d-5c9076a2f596,72506001,(01)20180595258346(11)101003(17)351018(10)1391...,11.083333
2,2017-06-04,0.0,0f5646bc-a156-4ec0-9252-5b592e3d3184,72506001,(01)87988924478445(11)170514(17)420529(10)4143...,4.416667
3,1989-01-17,0.0,44c8b4c8-4457-4ba0-94b6-285ef327a249,705643001,(01)30831895165484(11)881227(17)140111(10)7597...,32.833333
4,1973-07-19,0.0,89752052-a38b-45f0-a590-3950bbb67bec,72506001,(01)71767722231489(11)730628(17)980713(10)6519...,48.333333
...,...,...,...,...,...,...
73,1997-01-27,0.0,9bebd912-a12b-4a83-a02c-f510587246df,72506001,(01)18759008756217(11)970106(17)220121(10)5934...,24.833333
74,1994-02-08,0.0,9c4c1885-35af-48b9-a09f-4ea448d40d75,706004007,(01)78045789271756(11)940118(17)190202(10)5321...,27.750000
75,2018-11-04,0.0,2f76733b-933c-4cc5-aea2-53799158c8cc,706004007,(01)77289394758969(11)181014(17)431029(10)3787...,4.000000
76,1955-02-01,0.0,87f05059-de42-4630-a35b-edb53d880640,705643001,(01)81833763907543(11)550111(17)800126(10)1912...,66.750000
77,1988-05-17,0.0,023a7d29-32b3-4db5-89c8-b88bd7582ec0,706004007,(01)23971141656665(11)880426(17)130511(10)7167...,33.500000

In [90]:
df_devices.drop(['START','STOP'],axis=1,inplace=True)

In [91]:
prev = 0 
dict1 = {}
dict2 = {}
dict3 = {}
val=0
for i in range(1,len(df_devices)):
    if df_devices.PATIENT[i] == df_devices.PATIENT[prev] :
        #print(i)
        continue
    else :
        list1 = df_devices.CODE[prev:i].values
        list2 = df_devices.Device_Time[prev:i].values
        list3 = df_devices.Device_Time[prev:i].values
        dict1[df_devices.PATIENT[prev]] = list1
        dict2[df_devices.PATIENT[prev]] = list2
        dict3[df_devices.PATIENT[prev]] = list3
        prev = i
        if i == len(df_devices)-1 :
            val=1
if val==1:
    list1 = [df_devices.CODE[prev]]
    list2 = [df_devices.Device_Time[prev]]
    list3 = [df_devices.Device_Time[prev]]
    dict1[df_devices.PATIENT[prev]] = list1
    dict2[df_devices.PATIENT[prev]] = list2
    dict3[df_devices.PATIENT[prev]] = list3
else :
    list1 = [df_devices.CODE[prev:len(df_devices)]]
    list2 = [df_devices.Device_Time[prev:len(df_devices)]]
    list3 = [df_devices.Device_Time[prev:len(df_devices)]]
    dict1[df_devices.PATIENT[prev]] = list1
    dict2[df_devices.PATIENT[prev]] = list2
    dict3[df_devices.PATIENT[prev]] = list3

In [92]:
prev = 0
for i in range(1,len(df_devices)):
    if df_devices.PATIENT[i] == df_devices.PATIENT[prev] :
        df_devices.drop(i,axis=0,inplace=True)
    else:
        prev=i

In [93]:
df_devices.reset_index(inplace=True)

In [94]:
df_devices

,index,PATIENT,CODE,UDI,Device_Time
0,0,d49f748f-928d-40e8-92c8-73e4c5679711,72506001,(01)67677988606464(11)010613(17)260628(10)2882...,20.333333
1,1,e05dd037-e45f-434a-946d-5c9076a2f596,72506001,(01)20180595258346(11)101003(17)351018(10)1391...,11.083333
2,2,0f5646bc-a156-4ec0-9252-5b592e3d3184,72506001,(01)87988924478445(11)170514(17)420529(10)4143...,4.416667
3,3,44c8b4c8-4457-4ba0-94b6-285ef327a249,705643001,(01)30831895165484(11)881227(17)140111(10)7597...,32.833333
4,4,89752052-a38b-45f0-a590-3950bbb67bec,72506001,(01)71767722231489(11)730628(17)980713(10)6519...,48.333333
...,...,...,...,...,...
69,73,9bebd912-a12b-4a83-a02c-f510587246df,72506001,(01)18759008756217(11)970106(17)220121(10)5934...,24.833333
70,74,9c4c1885-35af-48b9-a09f-4ea448d40d75,706004007,(01)78045789271756(11)940118(17)190202(10)5321...,27.750000
71,75,2f76733b-933c-4cc5-aea2-53799158c8cc,706004007,(01)77289394758969(11)181014(17)431029(10)3787...,4.000000
72,76,87f05059-de42-4630-a35b-edb53d880640,705643001,(01)81833763907543(11)550111(17)800126(10)1912...,66.750000
73,77,023a7d29-32b3-4db5-89c8-b88bd7582ec0,706004007,(01)23971141656665(11)880426(17)130511(10)7167...,33.500000

In [95]:
len(dict1)

74

In [96]:
df_devices['CODE'] = df_devices['CODE'].astype(object)
df_devices['Device_Time'] = df_devices['Device_Time'].astype(object) 
df_devices['UDI'] = df_devices['UDI'].astype(object)

In [97]:
for i in range(len(df_devices)):
    df_devices.CODE[i]= dict1[df_devices.PATIENT[i]]
    df_devices.Device_Time[i] = dict2[df_devices.PATIENT[i]]
    df_devices.UDI[i] = dict3[df_devices.PATIENT[i]]

/tmp/ipykernel_25837/3218876847.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_devices.CODE[i]= dict1[df_devices.PATIENT[i]]
/tmp/ipykernel_25837/3218876847.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_devices.Device_Time[i] = dict2[df_devices.PATIENT[i]]
/tmp/ipykernel_25837/3218876847.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_devices.UDI[i] = dict3[df_devices.PATIENT[i]]

In [98]:
df_devices

,index,PATIENT,CODE,UDI,Device_Time
0,0,d49f748f-928d-40e8-92c8-73e4c5679711,[72506001],[20.333333333333332],[20.333333333333332]
1,1,e05dd037-e45f-434a-946d-5c9076a2f596,[72506001],[11.083333333333334],[11.083333333333334]
2,2,0f5646bc-a156-4ec0-9252-5b592e3d3184,[72506001],[4.416666666666667],[4.416666666666667]
3,3,44c8b4c8-4457-4ba0-94b6-285ef327a249,[705643001],[32.833333333333336],[32.833333333333336]
4,4,89752052-a38b-45f0-a590-3950bbb67bec,[72506001],[48.333333333333336],[48.333333333333336]
...,...,...,...,...,...
69,73,9bebd912-a12b-4a83-a02c-f510587246df,[72506001],[24.833333333333332],[24.833333333333332]
70,74,9c4c1885-35af-48b9-a09f-4ea448d40d75,[706004007],[27.75],[27.75]
71,75,2f76733b-933c-4cc5-aea2-53799158c8cc,[706004007],[4.0],[4.0]
72,76,87f05059-de42-4630-a35b-edb53d880640,[705643001],[66.75],[66.75]
73,77,023a7d29-32b3-4db5-89c8-b88bd7582ec0,[706004007],[33.5],[33.5]

In [99]:
df_devices.rename(columns={'CODE':'Device_CODE','UDI':'Device_UDI'},inplace=True)

In [100]:
df_devices.drop(['index'],axis=1,inplace=True)

In [101]:
df = pd.merge(df,df_devices,how = 'outer',left_on='Id',right_on='PATIENT')

In [102]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,...,Careplan_CODE,Careplan_REASONCODE,Careplan_Time,Condition_CODE,Condition_DESCRIPTION,Condition_Time,PATIENT,Device_CODE,Device_UDI,Device_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,...,0.0,0,0,[444814009],[Viral sinusitis (disorder)],[0.08333333333333333],NaN,NaN,NaN,NaN
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,...,53950000.0,"[10509002.0, 10509002.0]","[3.0, 0.08333333333333333]",[10509002],[Acute bronchitis (disorder)],[0.08333333333333333],NaN,NaN,NaN,NaN
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,...,225358003.0,"[284551006.0, 10509002.0, 10509002.0]","[0.08333333333333333, 0.25, 0.08333333333333333]","[284551006, 10509002]","[Laceration of foot, Acute bronchitis (disorder)]","[0.08333333333333333, 0.08333333333333333]",NaN,NaN,NaN,NaN
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,...,0.0,0,0,[43878008],[Streptococcal sore throat (disorder)],[1.0],NaN,NaN,NaN,NaN
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,...,53950000.0,[10509002.0],[0.9166666666666666],[195662009],[Acute viral pharyngitis (disorder)],[1.0],NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,...,53950000.0,"[10509002.0, 55822004.0, 15777000.0]","[0.16666666666666666, 57.666666666666664, 62.5]","[15777000, 271737000, 55822004, 40055000, 4943...","[Prediabetes, Anemia (disorder), Hyperlipidemi...","[62.5, 62.5, 57.75, 48.75, 36.583333333333336,...",023a7d29-32b3-4db5-89c8-b88bd7582ec0,[706004007],[33.5],[33.5]
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,...,0.0,0,0,"[444814009, 444814009, 43878008]","[Viral sinusitis (disorder), Viral sinusitis (...","[1.0, 1.0, 1.0]",NaN,NaN,NaN,NaN
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,...,386257007.0,"[26929004.0, 233678006.0, 15777000.0, 10509002.0]","[27.083333333333332, 103.16666666666667, 62.66...","[19169002, 162864005, 79586000, 15777000, 2548...","[Miscarriage in first trimester, Body mass ind...","[76.83333333333333, 75.83333333333333, 74.3333...",NaN,NaN,NaN,NaN
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,...,736353004.0,"[0.0, 88805009.0, 263102004.0, 15777000.0, 707...","[31.666666666666668, 34.166666666666664, 0.166...","[19169002, 162864005, 40055000, 15777000, 2717...","[Miscarriage in first trimester, Body mass ind...","[86.25, 82.0, 71.5, 56.166666666666664, 55.166...",NaN,NaN,NaN,NaN
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,...,408869004.0,[239873007.0],[64.25],"[[19169002, 239873007, 64859006, 40055000, 230...","[[Miscarriage in first trimester, Osteoarthrit...","[[64.83333333333333, 64.25, 36.916666666666664...",NaN,NaN,NaN,NaN

In [103]:
df.drop(['PATIENT'],axis=1,inplace=True)
df.fillna(0,inplace=True)

In [104]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,...,Allergy_Time,Careplan_CODE,Careplan_REASONCODE,Careplan_Time,Condition_CODE,Condition_DESCRIPTION,Condition_Time,Device_CODE,Device_UDI,Device_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,...,0,0.0,0,0,[444814009],[Viral sinusitis (disorder)],[0.08333333333333333],0,0,0
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,...,0,53950000.0,"[10509002.0, 10509002.0]","[3.0, 0.08333333333333333]",[10509002],[Acute bronchitis (disorder)],[0.08333333333333333],0,0,0
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,...,0,225358003.0,"[284551006.0, 10509002.0, 10509002.0]","[0.08333333333333333, 0.25, 0.08333333333333333]","[284551006, 10509002]","[Laceration of foot, Acute bronchitis (disorder)]","[0.08333333333333333, 0.08333333333333333]",0,0,0
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,...,0,0.0,0,0,[43878008],[Streptococcal sore throat (disorder)],[1.0],0,0,0
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,...,0,53950000.0,[10509002.0],[0.9166666666666666],[195662009],[Acute viral pharyngitis (disorder)],[1.0],0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,...,0,53950000.0,"[10509002.0, 55822004.0, 15777000.0]","[0.16666666666666666, 57.666666666666664, 62.5]","[15777000, 271737000, 55822004, 40055000, 4943...","[Prediabetes, Anemia (disorder), Hyperlipidemi...","[62.5, 62.5, 57.75, 48.75, 36.583333333333336,...",[706004007],[33.5],[33.5]
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,...,0,0.0,0,0,"[444814009, 444814009, 43878008]","[Viral sinusitis (disorder), Viral sinusitis (...","[1.0, 1.0, 1.0]",0,0,0
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,...,0,386257007.0,"[26929004.0, 233678006.0, 15777000.0, 10509002.0]","[27.083333333333332, 103.16666666666667, 62.66...","[19169002, 162864005, 79586000, 15777000, 2548...","[Miscarriage in first trimester, Body mass ind...","[76.83333333333333, 75.83333333333333, 74.3333...",0,0,0
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,...,0,736353004.0,"[0.0, 88805009.0, 263102004.0, 15777000.0, 707...","[31.666666666666668, 34.166666666666664, 0.166...","[19169002, 162864005, 40055000, 15777000, 2717...","[Miscarriage in first trimester, Body mass ind...","[86.25, 82.0, 71.5, 56.166666666666664, 55.166...",0,0,0
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,...,0,408869004.0,[239873007.0],[64.25],"[[19169002, 239873007, 64859006, 40055000, 230...","[[Miscarriage in first trimester, Osteoarthrit...","[[64.83333333333333, 64.25, 36.916666666666664...",0,0,0

In [105]:
df_encounters

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,d0c40d10-8d87-447e-836e-99d26ad52ea5,2010-01-23T17:45:28Z,2010-01-23T18:10:28Z,034e9e3b-2def-4559-bb2a-7850888ae060,e002090d-4e92-300e-b41e-7d1f21dee4c6,e6283e46-fd81-3611-9459-0edb1c3da357,6e2f1a2d-27bd-3701-8d08-dae202c58632,ambulatory,185345009,Encounter for symptom,129.16,129.16,54.16,10509002.0,Acute bronchitis (disorder)
1,e88bc3a9-007c-405e-aabc-792a38f4aa2b,2012-01-23T17:45:28Z,2012-01-23T18:00:28Z,034e9e3b-2def-4559-bb2a-7850888ae060,772ee193-bb9f-30eb-9939-21e86c8e4da5,6f1d59a7-a5bd-3cf9-9671-5bad2f351c28,6e2f1a2d-27bd-3701-8d08-dae202c58632,wellness,162673000,General examination of patient (procedure),129.16,129.16,129.16,NaN,NaN
2,8f104aa7-4ca9-4473-885a-bba2437df588,2001-05-01T15:02:18Z,2001-05-01T15:17:18Z,1d604da9-9a81-4ba9-80c2-de3375d59b40,5d4b9df1-93ae-3bc9-b680-03249990e558,af01a385-31d3-3c77-8fdb-2867fe88df2f,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185345009,Encounter for symptom,129.16,129.16,0.00,36971009.0,Sinusitis (disorder)
3,b85c339a-6076-43ed-b9d0-9cf013dec49d,2011-07-28T15:02:18Z,2011-07-28T15:17:18Z,1d604da9-9a81-4ba9-80c2-de3375d59b40,3dc9bb2d-5d66-3e61-bf9a-e234c6433577,bb17e691-262b-3546-93d5-d88e7de93246,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,General examination of patient (procedure),129.16,129.16,0.00,NaN,NaN
4,dae2b7cb-1316-4b78-954f-fa610a6c6d0e,2010-07-27T12:58:08Z,2010-07-27T13:28:08Z,10339b10-3cd1-4ac3-ac13-ec26728cb592,b03dba4f-892f-365c-bfd1-bfcfa7a98d5d,7ed6b84a-b847-3744-9d42-15c42297a0c2,d47b3510-2895-3b70-9897-342d681c769d,wellness,162673000,General examination of patient (procedure),129.16,129.16,129.16,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53341,bd3bfc3c-4f52-4d9c-aa01-60a084b2ddcd,2015-06-20T17:27:52Z,2015-06-20T17:57:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,General examination of patient (procedure),129.16,129.16,129.16,NaN,NaN
53342,59727285-d30f-44e2-bcda-eac21ce07269,2016-06-25T17:27:52Z,2016-06-25T17:42:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,General examination of patient (procedure),129.16,129.16,129.16,NaN,NaN
53343,957b13d5-49fa-4518-8c25-6eaa45e6a7d1,2017-07-01T17:27:52Z,2017-07-01T17:57:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,General examination of patient (procedure),129.16,129.16,129.16,NaN,NaN
53344,5529a0d5-a24c-42b4-a32a-729e4d1f19ef,2018-07-07T17:27:52Z,2018-07-07T17:42:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,General examination of patient (procedure),129.16,129.16,129.16,NaN,NaN
53345,1306d180-d887-4286-b940-9a6a2425cf93,2019-07-13T17:27:52Z,2019-07-13T17:57:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,General examination of patient (procedure),129.16,129.16,129.16,NaN,NaN

In [106]:
df_encounters.drop(['DESCRIPTION','REASONCODE','REASONDESCRIPTION','Id'],axis=1,inplace=True)

In [107]:
df_encounters

,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE
0,2010-01-23T17:45:28Z,2010-01-23T18:10:28Z,034e9e3b-2def-4559-bb2a-7850888ae060,e002090d-4e92-300e-b41e-7d1f21dee4c6,e6283e46-fd81-3611-9459-0edb1c3da357,6e2f1a2d-27bd-3701-8d08-dae202c58632,ambulatory,185345009,129.16,129.16,54.16
1,2012-01-23T17:45:28Z,2012-01-23T18:00:28Z,034e9e3b-2def-4559-bb2a-7850888ae060,772ee193-bb9f-30eb-9939-21e86c8e4da5,6f1d59a7-a5bd-3cf9-9671-5bad2f351c28,6e2f1a2d-27bd-3701-8d08-dae202c58632,wellness,162673000,129.16,129.16,129.16
2,2001-05-01T15:02:18Z,2001-05-01T15:17:18Z,1d604da9-9a81-4ba9-80c2-de3375d59b40,5d4b9df1-93ae-3bc9-b680-03249990e558,af01a385-31d3-3c77-8fdb-2867fe88df2f,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185345009,129.16,129.16,0.00
3,2011-07-28T15:02:18Z,2011-07-28T15:17:18Z,1d604da9-9a81-4ba9-80c2-de3375d59b40,3dc9bb2d-5d66-3e61-bf9a-e234c6433577,bb17e691-262b-3546-93d5-d88e7de93246,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,129.16,129.16,0.00
4,2010-07-27T12:58:08Z,2010-07-27T13:28:08Z,10339b10-3cd1-4ac3-ac13-ec26728cb592,b03dba4f-892f-365c-bfd1-bfcfa7a98d5d,7ed6b84a-b847-3744-9d42-15c42297a0c2,d47b3510-2895-3b70-9897-342d681c769d,wellness,162673000,129.16,129.16,129.16
...,...,...,...,...,...,...,...,...,...,...,...
53341,2015-06-20T17:27:52Z,2015-06-20T17:57:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,129.16,129.16,129.16
53342,2016-06-25T17:27:52Z,2016-06-25T17:42:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,129.16,129.16,129.16
53343,2017-07-01T17:27:52Z,2017-07-01T17:57:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,129.16,129.16,129.16
53344,2018-07-07T17:27:52Z,2018-07-07T17:42:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,129.16,129.16,129.16
53345,2019-07-13T17:27:52Z,2019-07-13T17:57:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,129.16,129.16,129.16

In [108]:
df_encounters['Encounter_Time'] = 0.0

In [109]:
for i in range(len(df_encounters)):
    df_encounters.START[i] = pd.to_datetime(df_encounters.START[i],utc=True)
    df_encounters.STOP[i] = pd.to_datetime(df_encounters.STOP[i],utc=True)
    time = 0.0
    #print(start,stop)
    #print(pd.Timedelta(stop-start).seconds/3600)
    #df_encounters['Encounter_Time'] =  pd.Timedelta(stop-start).seconds
    #time = stop.year - start.year - ((stop.month,stop.day)<(start.month,start.day))
   # if stop.month>start.month and stop.day>start.day :
    #    time = time + (stop.month - start.month)/12 + (stop.day-start.day)/365
    #else :
     #   if stop.month>start.month :
      #      time = time + (stop.month - start.month-1)/12 + ()
    #time = time*365

    
df_encounters

/tmp/ipykernel_25837/3976589158.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.START[i] = pd.to_datetime(df_encounters.START[i],utc=True)
/tmp/ipykernel_25837/3976589158.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.STOP[i] = pd.to_datetime(df_encounters.STOP[i],utc=True)

,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,Encounter_Time
0,2010-01-23 17:45:28+00:00,2010-01-23 18:10:28+00:00,034e9e3b-2def-4559-bb2a-7850888ae060,e002090d-4e92-300e-b41e-7d1f21dee4c6,e6283e46-fd81-3611-9459-0edb1c3da357,6e2f1a2d-27bd-3701-8d08-dae202c58632,ambulatory,185345009,129.16,129.16,54.16,0.0
1,2012-01-23 17:45:28+00:00,2012-01-23 18:00:28+00:00,034e9e3b-2def-4559-bb2a-7850888ae060,772ee193-bb9f-30eb-9939-21e86c8e4da5,6f1d59a7-a5bd-3cf9-9671-5bad2f351c28,6e2f1a2d-27bd-3701-8d08-dae202c58632,wellness,162673000,129.16,129.16,129.16,0.0
2,2001-05-01 15:02:18+00:00,2001-05-01 15:17:18+00:00,1d604da9-9a81-4ba9-80c2-de3375d59b40,5d4b9df1-93ae-3bc9-b680-03249990e558,af01a385-31d3-3c77-8fdb-2867fe88df2f,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,ambulatory,185345009,129.16,129.16,0.00,0.0
3,2011-07-28 15:02:18+00:00,2011-07-28 15:17:18+00:00,1d604da9-9a81-4ba9-80c2-de3375d59b40,3dc9bb2d-5d66-3e61-bf9a-e234c6433577,bb17e691-262b-3546-93d5-d88e7de93246,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,162673000,129.16,129.16,0.00,0.0
4,2010-07-27 12:58:08+00:00,2010-07-27 13:28:08+00:00,10339b10-3cd1-4ac3-ac13-ec26728cb592,b03dba4f-892f-365c-bfd1-bfcfa7a98d5d,7ed6b84a-b847-3744-9d42-15c42297a0c2,d47b3510-2895-3b70-9897-342d681c769d,wellness,162673000,129.16,129.16,129.16,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
53341,2015-06-20 17:27:52+00:00,2015-06-20 17:57:52+00:00,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,129.16,129.16,129.16,0.0
53342,2016-06-25 17:27:52+00:00,2016-06-25 17:42:52+00:00,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,129.16,129.16,129.16,0.0
53343,2017-07-01 17:27:52+00:00,2017-07-01 17:57:52+00:00,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,129.16,129.16,129.16,0.0
53344,2018-07-07 17:27:52+00:00,2018-07-07 17:42:52+00:00,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,129.16,129.16,129.16,0.0
53345,2019-07-13 17:27:52+00:00,2019-07-13 17:57:52+00:00,fc817953-cc8b-45db-9c85-7c0ced8fa90d,a44b37da-aa9b-37f0-993e-26e58974e086,ff678a28-0ee8-379c-80ab-2dc790cf67dd,7caa7254-5050-3b5e-9eae-bd5ea30e809c,wellness,162673000,129.16,129.16,129.16,0.0

In [110]:
for i in range(len(df_encounters)):
    df_encounters.Encounter_Time[i] = pd.Timedelta(df_encounters.STOP[i]-df_encounters.START[i]).seconds

/tmp/ipykernel_25837/1881191394.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.Encounter_Time[i] = pd.Timedelta(df_encounters.STOP[i]-df_encounters.START[i]).seconds

In [111]:
df_encounters.drop(['START','STOP'],axis=1,inplace=True)

In [112]:
df_encounters.sort_values('PATIENT',inplace=True)

In [113]:
df_encounters.reset_index(inplace=True)

In [114]:
prev = 0 
dict1 = {}
dict2 = {}
dict3 = {}
dict4 = {}
dict5 = {}
dict6 = {}
dict7 = {}
dict8 = {}
val=0
for i in range(1,len(df_encounters)):
    if df_encounters.PATIENT[i] == df_encounters.PATIENT[prev] :
        #print(i)
        continue
    else :
        list1 = df_encounters.ORGANIZATION[prev:i].values
        list2 = df_encounters.PROVIDER[prev:i].values
        list3 = df_encounters.ENCOUNTERCLASS[prev:i].values
        list4 = df_encounters.CODE[prev:i].values
        list5 = df_encounters.BASE_ENCOUNTER_COST[prev:i].values
        list6 = df_encounters.TOTAL_CLAIM_COST[prev:i].values
        list7 = df_encounters.PAYER_COVERAGE[prev:i].values
        list8 = df_encounters.Encounter_Time[prev:i].values
        dict1[df_encounters.PATIENT[prev]] = list1
        dict2[df_encounters.PATIENT[prev]] = list2
        dict3[df_encounters.PATIENT[prev]] = list3
        dict4[df_encounters.PATIENT[prev]] = list4
        dict5[df_encounters.PATIENT[prev]] = list5
        dict6[df_encounters.PATIENT[prev]] = list6
        dict7[df_encounters.PATIENT[prev]] = list7
        dict8[df_encounters.PATIENT[prev]] = list8
        prev = i
        if i == len(df_encounters)-1 :
            val=1
if val==1:
    list1 = df_encounters.ORGANIZATION[prev]
    list2 = df_encounters.PROVIDER[prev]
    list3 = df_encounters.ENCOUNTERCLASS[prev]
    list4 = df_encounters.CODE[prev]
    list5 = df_encounters.BASE_ENCOUNTER_COST[prev]
    list6 = df_encounters.TOTAL_CLAIM_COST[prev]
    list7 = df_encounters.PAYER_COVERAGE[prev]
    list8 = df_encounters.Encounter_Time[prev]
    dict1[df_encounters.PATIENT[prev]] = list1
    dict2[df_encounters.PATIENT[prev]] = list2
    dict3[df_encounters.PATIENT[prev]] = list3
    dict4[df_encounters.PATIENT[prev]] = list4
    dict5[df_encounters.PATIENT[prev]] = list5
    dict6[df_encounters.PATIENT[prev]] = list6
    dict7[df_encounters.PATIENT[prev]] = list7
    dict8[df_encounters.PATIENT[prev]] = list8
else :
    list1 = [df_encounters.ORGANIZATION[prev:len(df_encounters)]]
    list2 = [df_encounters.PROVIDER[prev:len(df_encounters)]]
    list3 = [df_encounters.ENCOUNTERCLASS[prev:len(df_encounters)]]
    list4 = [df_encounters.CODE[prev:len(df_encounters)]]
    list5 = [df_encounters.BASE_ENCOUNTER_COST[prev:len(df_encounters)]]
    list6 = [df_encounters.TOTAL_CLAIM_COST[prev:len(df_encounters)]]
    list7 = [df_encounters.PAYER_COVERAGE[prev:len(df_encounters)]]
    list8 = [df_encounters.Encounter_Time[prev:len(df_encounters)]]
    dict1[df_encounters.PATIENT[prev]] = list1
    dict2[df_encounters.PATIENT[prev]] = list2
    dict3[df_encounters.PATIENT[prev]] = list3
    dict4[df_encounters.PATIENT[prev]] = list4
    dict5[df_encounters.PATIENT[prev]] = list5
    dict6[df_encounters.PATIENT[prev]] = list6
    dict7[df_encounters.PATIENT[prev]] = list7
    dict8[df_encounters.PATIENT[prev]] = list8

In [115]:
len(dict1)

1171

In [116]:
prev = 0
for i in range(1,len(df_encounters)):
    if df_encounters.PATIENT[i] == df_encounters.PATIENT[prev] :
        df_encounters.drop(i,axis=0,inplace=True)
    else:
        prev=i

In [117]:
df_encounters

,index,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,Encounter_Time
0,34111,00185faa-2760-4218-9bf5-db301acf8274,9d274f97-5860-3640-a985-9d831e33136e,fe3d1004-b6e9-3fd8-bab5-8ba4cf7d7d95,6e2f1a2d-27bd-3701-8d08-dae202c58632,wellness,410620009,129.16,129.16,129.16,900.0
22,29968,0042862c-9889-4a2e-b782-fac1e540ecb4,473293d9-b54a-384c-9146-05416f9bdac4,9b5ac875-6090-3946-ac59-4169c864ce7e,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,wellness,410620009,129.16,129.16,0.00,900.0
43,50113,0047123f-12e7-486c-82df-53b3a450e365,37c0de84-bcaf-3624-82bf-a89b2ac441b8,8d0c1895-f59c-388a-bc6f-757dbf201ae6,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,emergency,50849002,129.16,129.16,0.00,3600.0
64,7138,010d4a3a-2316-45ed-ae15-16f01c611674,4f3a530e-a2f7-3de0-9a09-c0a70a9ab894,3f15c687-0cfe-3bf2-9e62-34f3c85ff3cb,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,ambulatory,185345009,129.16,129.16,59.16,900.0
77,87,01207ecd-9dff-4754-8887-4652eda231e2,fa340249-2990-3217-9d24-d69a3c55b349,f8d2b3a5-9a81-3561-b2fa-7582ff69ad6f,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,wellness,410620009,129.16,129.16,129.16,900.0
...,...,...,...,...,...,...,...,...,...,...,...
53163,36047,ff02f237-fedb-453b-85b1-ebfc2609c312,043c2193-7fbd-3a5c-ad68-275230f1f3d4,71e75e56-16a2-3cea-9742-41ce32236314,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,wellness,162673000,129.16,129.16,129.16,900.0
53178,17713,ff3714ac-c7e3-4910-905e-2a321eb28144,5844ad77-f653-3c2b-b7dd-e97576ab3b03,d6e216be-acb7-3c45-84b3-fc69e7714ca5,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,ambulatory,390906007,129.16,129.16,59.16,900.0
53194,34444,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,23834663-ed53-3da9-b330-d6e1ecb8428e,af42f305-3f0c-396d-8303-9cbdb900a516,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,emergency,50849002,129.16,129.16,59.16,3600.0
53289,43915,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,4861d01f-019c-3dac-a153-8334e50919f9,b08f34d7-3c08-35b9-a2ba-b823511ebc57,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,emergency,50849002,129.16,129.16,0.00,3600.0
53328,37567,ffcfa457-00c2-4405-9837-ac2781549c7e,13146004-4c5e-31b9-a1f7-417b2ca5b56b,923baf88-6d8d-3eda-a5e7-9aa395ea082e,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,wellness,410620009,129.16,129.16,129.16,1800.0

In [118]:
df_encounters.reset_index(inplace=True)

In [119]:
df_encounters['ORGANIZATION'] = df_encounters['ORGANIZATION'].astype(object)
df_encounters['PROVIDER'] = df_encounters['PROVIDER'].astype(object)
df_encounters['ENCOUNTERCLASS'] = df_encounters['ENCOUNTERCLASS'].astype(object)
df_encounters['CODE'] = df_encounters['CODE'].astype(object)
df_encounters['BASE_ENCOUNTER_COST'] = df_encounters['BASE_ENCOUNTER_COST'].astype(object)
df_encounters['TOTAL_CLAIM_COST'] = df_encounters['TOTAL_CLAIM_COST'].astype(object)
df_encounters['PAYER_COVERAGE'] = df_encounters['PAYER_COVERAGE'].astype(object) 
df_encounters['Encounter_Time'] = df_encounters['Encounter_Time'].astype(object)

In [120]:
for i in range(len(df_encounters)):
    df_encounters.ORGANIZATION[i] = dict1[df_encounters.PATIENT[i]]
    df_encounters.PROVIDER[i] = dict2[df_encounters.PATIENT[i]]
    df_encounters.ENCOUNTERCLASS[i] = dict3[df_encounters.PATIENT[i]]
    df_encounters.CODE[i] = dict4[df_encounters.PATIENT[i]]
    df_encounters.BASE_ENCOUNTER_COST[i] = dict5[df_encounters.PATIENT[i]]
    df_encounters.TOTAL_CLAIM_COST[i] = dict6[df_encounters.PATIENT[i]]
    df_encounters.PAYER_COVERAGE[i] = dict7[df_encounters.PATIENT[i]]
    df_encounters.Encounter_Time[i] =  dict8[df_encounters.PATIENT[i]]

/tmp/ipykernel_25837/2421601807.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.ORGANIZATION[i] = dict1[df_encounters.PATIENT[i]]
/tmp/ipykernel_25837/2421601807.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.PROVIDER[i] = dict2[df_encounters.PATIENT[i]]
/tmp/ipykernel_25837/2421601807.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.ENCOUNTERCLASS[i] = dict3[df_encounters.PATIENT[i]]
/tmp/ipykernel_25837/2421601807.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.CODE[i] = dict4[df_encounters.PATIENT[i]]
/tmp/ipykernel_25837/2421601807.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.BASE_ENCOUNTER_COST[i] = dict5[df_encounters.PATIENT[i]]
/tmp/ipykernel_25837/2421601807.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.TOTAL_CLAIM_COST[i] = dict6[df_encounters.PATIENT[i]]
/tmp/ipykernel_25837/2421601807.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.PAYER_COVERAGE[i] = dict7[df_encounters.PATIENT[i]]
/tmp/ipykernel_25837/2421601807.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_encounters.Encounter_Time[i] =  dict8[df_encounters.PATIENT[i]]

In [121]:
df_encounters.drop(['level_0','index'],axis=1,inplace=True)

In [122]:
df_encounters

,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,Encounter_Time
0,00185faa-2760-4218-9bf5-db301acf8274,"[9d274f97-5860-3640-a985-9d831e33136e, 4861d01...","[fe3d1004-b6e9-3fd8-bab5-8ba4cf7d7d95, b08f34d...",6e2f1a2d-27bd-3701-8d08-dae202c58632,"[wellness, inpatient, inpatient, inpatient, we...","[410620009, 183452005, 183452005, 183452005, 4...","[129.16, 77.49, 77.49, 77.49, 129.16, 77.49, 7...","[129.16, 77.49, 77.49, 77.49, 129.16, 77.49, 7...","[129.16, 2.49, 2.49, 2.49, 129.16, 2.49, 2.49,...","[900.0, 900.0, 0.0, 900.0, 900.0, 900.0, 0.0, ..."
1,0042862c-9889-4a2e-b782-fac1e540ecb4,"[473293d9-b54a-384c-9146-05416f9bdac4, 473293d...","[9b5ac875-6090-3946-ac59-4169c864ce7e, 9b5ac87...",b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,"[wellness, wellness, wellness, wellness, welln...","[410620009, 410620009, 410620009, 410620009, 4...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[0.0, 129.16, 129.16, 0.0, 0.0, 0.0, 0.0, 0.0,...","[900.0, 900.0, 1800.0, 900.0, 900.0, 900.0, 90..."
2,0047123f-12e7-486c-82df-53b3a450e365,"[37c0de84-bcaf-3624-82bf-a89b2ac441b8, 37c0de8...","[8d0c1895-f59c-388a-bc6f-757dbf201ae6, 8d0c189...",7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,"[emergency, inpatient, wellness, wellness, amb...","[50849002, 183452005, 162673000, 162673000, 18...","[129.16, 77.49, 129.16, 129.16, 129.16, 129.16...","[129.16, 77.49, 129.16, 129.16, 129.16, 129.16...","[0.0, 17.49, 129.16, 129.16, 69.16, 0.0, 129.1...","[3600.0, 3600.0, 1800.0, 900.0, 900.0, 900.0, ..."
3,010d4a3a-2316-45ed-ae15-16f01c611674,"[4f3a530e-a2f7-3de0-9a09-c0a70a9ab894, 973e738...","[3f15c687-0cfe-3bf2-9e62-34f3c85ff3cb, 48950b1...",5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,"[ambulatory, wellness, wellness, ambulatory, w...","[185345009, 162673000, 162673000, 390906007, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[59.16, 129.16, 129.16, 59.16, 129.16, 129.16,...","[900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 180..."
4,01207ecd-9dff-4754-8887-4652eda231e2,"[fa340249-2990-3217-9d24-d69a3c55b349, fa34024...","[f8d2b3a5-9a81-3561-b2fa-7582ff69ad6f, f8d2b3a...",42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,"[wellness, wellness, wellness, wellness, welln...","[410620009, 410620009, 410620009, 410620009, 4...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[900.0, 1800.0, 1800.0, 1800.0, 1800.0, 900.0]"
...,...,...,...,...,...,...,...,...,...,...
1166,ff02f237-fedb-453b-85b1-ebfc2609c312,"[043c2193-7fbd-3a5c-ad68-275230f1f3d4, 043c219...","[71e75e56-16a2-3cea-9742-41ce32236314, 71e75e5...",42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,"[wellness, wellness, emergency, wellness, well...","[162673000, 410620009, 50849002, 410620009, 41...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 0.0, 129.16, 129.16, 0.0, 129...","[900.0, 900.0, 4320.0, 900.0, 900.0, 900.0, 90..."
1167,ff3714ac-c7e3-4910-905e-2a321eb28144,"[5844ad77-f653-3c2b-b7dd-e97576ab3b03, da79973...","[d6e216be-acb7-3c45-84b3-fc69e7714ca5, e3b34b6...",5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,"[ambulatory, wellness, wellness, wellness, amb...","[390906007, 410620009, 410620009, 410620009, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[59.16, 129.16, 129.16, 129.16, 59.16, 129.16,...","[900.0, 900.0, 1800.0, 1800.0, 900.0, 900.0, 9..."
1168,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,"[23834663-ed53-3da9-b330-d6e1ecb8428e, 2383466...","[af42f305-3f0c-396d-8303-9cbdb900a516, af42f30...",5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,"[emergency, ambulatory, ambulatory, ambulatory...","[50849002, 185345009, 424441002, 424619006, 56...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[59.16, 49.16, 49.16, 49.16, 49.16, 49.16, 49....","[3600.0, 900.0, 18900.0, 3600.0, 0.0, 4500.0, ..."
1169,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,"[4861d01f-019c-3dac-a153-8334e50919f9, 4861d01...","[b08f34d7-3c08-35b9-a2ba-b823511ebc57, b08f34d...",7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,"[emergency, outpatient, inpatient, wellness, o...","[50849002, 308335008, 183452005, 410620009, 69...","[129.16, 129.16, 77.49, 129.16, 129.16, 129.16...","[129.16, 129.16, 77.49, 129.16, 129.16, 129.16...","[0.0, 69.16, 17.49, 69.16, 69.16, 69.16, 0.0, ...","[3600.0, 4800.0, 3780.0, 1800.0, 900.0, 18900...."
1170,ffcfa457-00c2-4405-9837-ac2781549c7e,"[[13146004-4c5e-31b9-a1f7-417b2ca5b56b, 131460...","[[923baf88-6d8d-3eda-a5e7-9aa395ea082e, 923baf...",5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,"[[wellness, wellness, wellness, ambulatory, ou...","[[410620009, 410620009, 410620009, 185345009, ...","[[129.16, 129.16, 129.16, 129.16, 129.16, 129....","[[129.16, 129.16, 129.16, 129.16, 129.16, 129....","[[129.16, 129.16, 129.16, 59.16, 0.0, 59.16, 1...","[[1800.0, 1800.0, 1800.0, 900.0, 900.0, 3600.0..."

In [123]:
df_encounters.rename(columns = {'CODE':'ENCOUNTERCODE','TOTAL_CLAIM_COST':'ENCOUNTER_TOTAL_CLAIM_COST','PAYER_COVERAGE':'ENCOUNTER_PAYER_COVERAGE'},inplace=True)

In [124]:
df_encounters

,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,ENCOUNTERCODE,BASE_ENCOUNTER_COST,ENCOUNTER_TOTAL_CLAIM_COST,ENCOUNTER_PAYER_COVERAGE,Encounter_Time
0,00185faa-2760-4218-9bf5-db301acf8274,"[9d274f97-5860-3640-a985-9d831e33136e, 4861d01...","[fe3d1004-b6e9-3fd8-bab5-8ba4cf7d7d95, b08f34d...",6e2f1a2d-27bd-3701-8d08-dae202c58632,"[wellness, inpatient, inpatient, inpatient, we...","[410620009, 183452005, 183452005, 183452005, 4...","[129.16, 77.49, 77.49, 77.49, 129.16, 77.49, 7...","[129.16, 77.49, 77.49, 77.49, 129.16, 77.49, 7...","[129.16, 2.49, 2.49, 2.49, 129.16, 2.49, 2.49,...","[900.0, 900.0, 0.0, 900.0, 900.0, 900.0, 0.0, ..."
1,0042862c-9889-4a2e-b782-fac1e540ecb4,"[473293d9-b54a-384c-9146-05416f9bdac4, 473293d...","[9b5ac875-6090-3946-ac59-4169c864ce7e, 9b5ac87...",b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,"[wellness, wellness, wellness, wellness, welln...","[410620009, 410620009, 410620009, 410620009, 4...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[0.0, 129.16, 129.16, 0.0, 0.0, 0.0, 0.0, 0.0,...","[900.0, 900.0, 1800.0, 900.0, 900.0, 900.0, 90..."
2,0047123f-12e7-486c-82df-53b3a450e365,"[37c0de84-bcaf-3624-82bf-a89b2ac441b8, 37c0de8...","[8d0c1895-f59c-388a-bc6f-757dbf201ae6, 8d0c189...",7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,"[emergency, inpatient, wellness, wellness, amb...","[50849002, 183452005, 162673000, 162673000, 18...","[129.16, 77.49, 129.16, 129.16, 129.16, 129.16...","[129.16, 77.49, 129.16, 129.16, 129.16, 129.16...","[0.0, 17.49, 129.16, 129.16, 69.16, 0.0, 129.1...","[3600.0, 3600.0, 1800.0, 900.0, 900.0, 900.0, ..."
3,010d4a3a-2316-45ed-ae15-16f01c611674,"[4f3a530e-a2f7-3de0-9a09-c0a70a9ab894, 973e738...","[3f15c687-0cfe-3bf2-9e62-34f3c85ff3cb, 48950b1...",5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,"[ambulatory, wellness, wellness, ambulatory, w...","[185345009, 162673000, 162673000, 390906007, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[59.16, 129.16, 129.16, 59.16, 129.16, 129.16,...","[900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 180..."
4,01207ecd-9dff-4754-8887-4652eda231e2,"[fa340249-2990-3217-9d24-d69a3c55b349, fa34024...","[f8d2b3a5-9a81-3561-b2fa-7582ff69ad6f, f8d2b3a...",42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,"[wellness, wellness, wellness, wellness, welln...","[410620009, 410620009, 410620009, 410620009, 4...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[900.0, 1800.0, 1800.0, 1800.0, 1800.0, 900.0]"
...,...,...,...,...,...,...,...,...,...,...
1166,ff02f237-fedb-453b-85b1-ebfc2609c312,"[043c2193-7fbd-3a5c-ad68-275230f1f3d4, 043c219...","[71e75e56-16a2-3cea-9742-41ce32236314, 71e75e5...",42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,"[wellness, wellness, emergency, wellness, well...","[162673000, 410620009, 50849002, 410620009, 41...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 0.0, 129.16, 129.16, 0.0, 129...","[900.0, 900.0, 4320.0, 900.0, 900.0, 900.0, 90..."
1167,ff3714ac-c7e3-4910-905e-2a321eb28144,"[5844ad77-f653-3c2b-b7dd-e97576ab3b03, da79973...","[d6e216be-acb7-3c45-84b3-fc69e7714ca5, e3b34b6...",5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,"[ambulatory, wellness, wellness, wellness, amb...","[390906007, 410620009, 410620009, 410620009, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[59.16, 129.16, 129.16, 129.16, 59.16, 129.16,...","[900.0, 900.0, 1800.0, 1800.0, 900.0, 900.0, 9..."
1168,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,"[23834663-ed53-3da9-b330-d6e1ecb8428e, 2383466...","[af42f305-3f0c-396d-8303-9cbdb900a516, af42f30...",5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,"[emergency, ambulatory, ambulatory, ambulatory...","[50849002, 185345009, 424441002, 424619006, 56...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[59.16, 49.16, 49.16, 49.16, 49.16, 49.16, 49....","[3600.0, 900.0, 18900.0, 3600.0, 0.0, 4500.0, ..."
1169,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,"[4861d01f-019c-3dac-a153-8334e50919f9, 4861d01...","[b08f34d7-3c08-35b9-a2ba-b823511ebc57, b08f34d...",7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,"[emergency, outpatient, inpatient, wellness, o...","[50849002, 308335008, 183452005, 410620009, 69...","[129.16, 129.16, 77.49, 129.16, 129.16, 129.16...","[129.16, 129.16, 77.49, 129.16, 129.16, 129.16...","[0.0, 69.16, 17.49, 69.16, 69.16, 69.16, 0.0, ...","[3600.0, 4800.0, 3780.0, 1800.0, 900.0, 18900...."
1170,ffcfa457-00c2-4405-9837-ac2781549c7e,"[[13146004-4c5e-31b9-a1f7-417b2ca5b56b, 131460...","[[923baf88-6d8d-3eda-a5e7-9aa395ea082e, 923baf...",5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,"[[wellness, wellness, wellness, ambulatory, ou...","[[410620009, 410620009, 410620009, 185345009, ...","[[129.16, 129.16, 129.16, 129.16, 129.16, 129....","[[129.16, 129.16, 129.16, 129.16, 129.16, 129....","[[129.16, 129.16, 129.16, 59.16, 0.0, 59.16, 1...","[[1800.0, 1800.0, 1800.0, 900.0, 900.0, 3600.0..."

In [125]:
df = pd.merge(df,df_encounters,how = 'outer',left_on='Id',right_on='PATIENT')

In [126]:
df.drop(['PATIENT'],axis=1,inplace=True)

In [127]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,...,Device_Time,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,ENCOUNTERCODE,BASE_ENCOUNTER_COST,ENCOUNTER_TOTAL_CLAIM_COST,ENCOUNTER_PAYER_COVERAGE,Encounter_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,...,0,"[5d4b9df1-93ae-3bc9-b680-03249990e558, 5d4b9df...","[af01a385-31d3-3c77-8fdb-2867fe88df2f, af01a38...",b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,"[ambulatory, ambulatory, wellness, wellness, a...","[185345009, 185345009, 162673000, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]","[900.0, 900.0, 900.0, 1800.0, 900.0, 900.0]"
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,...,0,"[e002090d-4e92-300e-b41e-7d1f21dee4c6, 772ee19...","[e6283e46-fd81-3611-9459-0edb1c3da357, 6f1d59a...",6e2f1a2d-27bd-3701-8d08-dae202c58632,"[ambulatory, wellness, wellness, ambulatory, o...","[185345009, 162673000, 162673000, 185345009, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[54.16, 129.16, 129.16, 54.16, 54.16, 129.16]","[1500.0, 900.0, 1800.0, 900.0, 900.0, 900.0]"
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,...,0,"[5d4b9df1-93ae-3bc9-b680-03249990e558, 5d4b9df...","[af01a385-31d3-3c77-8fdb-2867fe88df2f, af01a38...",b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,"[outpatient, ambulatory, wellness, ambulatory,...","[185349003, 185345009, 162673000, 185345009, 7...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[0.0, 49.16, 129.16, 49.16, 0.0, 129.16, 129.1...","[900.0, 900.0, 1800.0, 900.0, 900.0, 900.0, 90..."
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,...,0,"[b0e04623-b02c-3f8b-92ea-943fc4db60da, d32bd7b...","[58b66cc1-2b86-377f-ad77-ad8164388e50, 163f7da...",4d71f845-a6a9-3c39-b242-14d25ef86a8d,"[ambulatory, wellness, outpatient, outpatient,...","[185345009, 162673000, 698314001, 308335008, 6...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[64.16, 129.16, 0.0, 0.0, 0.0, 129.16, 0.0, 0....","[900.0, 1800.0, 900.0, 3960.0, 900.0, 900.0, 2..."
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,...,0,"[58b8fe10-e28a-313e-93b0-486d1246c364, 58b8fe1...","[e755f853-29a9-3772-b889-589c1c172021, e755f85...",047f6ec3-6215-35eb-9608-f9dda363a44c,"[wellness, wellness, ambulatory, ambulatory, w...","[162673000, 410620009, 185345009, 185345009, 4...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 69.16, 69.16, 129.16, 69.16, ...","[900.0, 1800.0, 1800.0, 1800.0, 1800.0, 900.0,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1166,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,...,[33.5],"[127d0b28-580b-3171-b52a-7dd93083d1de, e002090...","[2357cbd0-4421-366e-ad63-4e50977f6ee9, e6283e4...",7caa7254-5050-3b5e-9eae-bd5ea30e809c,"[wellness, ambulatory, ambulatory, wellness, a...","[162673000, 390906007, 390906007, 162673000, 3...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[89.16, 89.16, 89.16, 89.16, 89.16, 89.16, 89....","[1800.0, 900.0, 900.0, 2700.0, 900.0, 1800.0, ..."
1167,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,...,0,"[37c0de84-bcaf-3624-82bf-a89b2ac441b8, 37c0de8...","[8d0c1895-f59c-388a-bc6f-757dbf201ae6, 8d0c189...",b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,"[outpatient, ambulatory, wellness, wellness, w...","[185349003, 185345009, 162673000, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[0.0, 59.16, 129.16, 129.16, 129.16, 59.16, 12...","[900.0, 900.0, 1800.0, 1800.0, 900.0, 900.0, 9..."
1168,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,...,0,"[cc648e4d-ae3a-3933-930e-f1f34189eb97, cc648e4...","[5bee674e-0d19-3b32-a207-7bd7d46e6da2, 5bee674...",6e2f1a2d-27bd-3701-8d08-dae202c58632,"[wellness, wellness, wellness, outpatient, wel...","[162673000, 162673000, 162673000, 185349003, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[54.16, 54.16, 54.16, 54.16, 69.16, 69.16, 54....","[900.0, 900.0, 1800.0, 900.0, 1800.0, 18900.0,..."
1169,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,...,0,"[3bd5eda0-16da-3ba5-8500-4dfd6ae118b8, b6164b1...","[40d7ff6c-5040-39aa-a876-19f1ccc6740c, c8f460b...",4d71f845-a6a9-3c39-b242-14d25ef86a8d,"[ambulatory, wellness, ambulatory, wellness, e...","[185347001, 162673000, 185347001, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[64.16, 89.16, 89.16, 89.16, 89.16, 0.0, 89.16...","[5700.0, 900.0, 2700.0, 900.0, 5400.0, 0.0, 54..."
1170,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,...,0,"[7fb56531-86bd-3e4a-8619-4df9942da309, a44b37d...","[1b75d7a2-3964-340e-b025-c5e2d3506244, ff678a2...",7caa7254-5050-3b5e-9eae-bd5ea30e809c,"[ambulatory, wellness, wellness, wellness, wel...","[185345009, 162673000, 162673000, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[89.16, 129.16, 129.16, 129.16, 129.16, 129.16...","[900.0, 900.0, 1800.0, 900.0, 1800.0, 900.0, 1..."

In [128]:
df_imaging

,Id,DATE,PATIENT,ENCOUNTER,BODYSITE_CODE,BODYSITE_DESCRIPTION,MODALITY_CODE,MODALITY_DESCRIPTION,SOP_CODE,SOP_DESCRIPTION
0,d3e49b38-7634-4416-879d-7bc68bf3e7df,2014-07-08T15:35:36Z,b58731cc-2d8b-4c2d-b327-4cab771af3ef,3a36836d-da25-4e73-808b-972b669b7e4e,40983000,Arm,DX,Digital Radiography,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage
1,46baf530-4941-40ab-8219-685a08fd9086,2014-01-22T18:58:37Z,2ffe9369-24e4-414b-8973-258fad09313a,33b71e4b-0690-4fe9-897a-dc3b2ff9215c,40983000,Arm,DX,Digital Radiography,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage
2,b8fb8a6e-a2f5-46c9-8b3f-a35aa982efcd,2001-12-01T02:08:27Z,86b97fc7-ae8f-4e0d-8e66-db68f36e7a76,e42d1046-568d-46c2-b0a5-d910b2f3bd1d,8205005,Wrist,DX,Digital Radiography,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage
3,10c8a016-4504-4653-bddf-2dd3610886c8,2004-07-03T20:46:46Z,71ba0469-f0cc-4177-ac70-ea07cb01c8b8,323fca87-817f-4d58-8486-ba92ea739399,51299004,Clavicle,DX,Digital Radiography,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage
4,4221534c-d379-4c6b-a22e-d7eae3fa2609,2017-02-08T08:42:44Z,d49f748f-928d-40e8-92c8-73e4c5679711,cfef48b3-b769-4794-a3e7-f57f7ba8d387,344001,Ankle,DX,Digital Radiography,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage
...,...,...,...,...,...,...,...,...,...,...
850,9148d80c-9ba5-4bcd-8c31-8eebb32d33d0,1988-03-25T17:27:52Z,fca3178e-fb68-41c3-8598-702d3ca68b96,fcadea12-7962-442d-b65b-8c28e16ab971,51185008,Thoracic structure (body structure),CR,Computed Radiography,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage â€“ for Presentation
851,904779de-bcc8-411e-88ec-92bacecfe43a,1989-03-20T17:27:52Z,fca3178e-fb68-41c3-8598-702d3ca68b96,c791e651-ee32-4be5-b74b-c873f38b2551,261179002,thoracic,US,Ultrasound,1.2.840.10008.5.1.4.1.1.3.1,Ultrasound Multiframe Image Storage
852,cb3552e4-4959-4c4d-b8ba-36d71608e32e,1990-03-15T17:27:52Z,fca3178e-fb68-41c3-8598-702d3ca68b96,bc5ea274-ad81-495a-adcb-276b69a7a120,51185008,Thoracic structure (body structure),CR,Computed Radiography,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage â€“ for Presentation
853,d5203a3f-75da-48a6-b750-8c5fa59ed657,1990-03-15T17:27:52Z,fca3178e-fb68-41c3-8598-702d3ca68b96,aaee3543-3edb-40af-a276-3bb027cac0dc,261179002,Thoracic,US,Ultrasound,1.2.840.10008.5.1.4.1.1.3.1,Ultrasound Multiframe Image Storage
854,23337364-87f9-4c98-812d-eabd9abd8502,1990-03-15T17:27:52Z,fca3178e-fb68-41c3-8598-702d3ca68b96,aaee3543-3edb-40af-a276-3bb027cac0dc,51185008,Thoracic structure,DX,Digital Radiography,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage â€“ for Presentation

In [129]:
df_imaging.drop(['DATE','Id','ENCOUNTER','BODYSITE_DESCRIPTION','MODALITY_DESCRIPTION','SOP_DESCRIPTION'],axis=1,inplace=True)

In [130]:
df_imaging

,PATIENT,BODYSITE_CODE,MODALITY_CODE,SOP_CODE
0,b58731cc-2d8b-4c2d-b327-4cab771af3ef,40983000,DX,1.2.840.10008.5.1.4.1.1.1.1
1,2ffe9369-24e4-414b-8973-258fad09313a,40983000,DX,1.2.840.10008.5.1.4.1.1.1.1
2,86b97fc7-ae8f-4e0d-8e66-db68f36e7a76,8205005,DX,1.2.840.10008.5.1.4.1.1.1.1
3,71ba0469-f0cc-4177-ac70-ea07cb01c8b8,51299004,DX,1.2.840.10008.5.1.4.1.1.1.1
4,d49f748f-928d-40e8-92c8-73e4c5679711,344001,DX,1.2.840.10008.5.1.4.1.1.1.1
...,...,...,...,...
850,fca3178e-fb68-41c3-8598-702d3ca68b96,51185008,CR,1.2.840.10008.5.1.4.1.1.1.1
851,fca3178e-fb68-41c3-8598-702d3ca68b96,261179002,US,1.2.840.10008.5.1.4.1.1.3.1
852,fca3178e-fb68-41c3-8598-702d3ca68b96,51185008,CR,1.2.840.10008.5.1.4.1.1.1.1
853,fca3178e-fb68-41c3-8598-702d3ca68b96,261179002,US,1.2.840.10008.5.1.4.1.1.3.1
854,fca3178e-fb68-41c3-8598-702d3ca68b96,51185008,DX,1.2.840.10008.5.1.4.1.1.1.1

In [131]:
prev = 0 
dict1 = {}
dict2 = {}
dict3 = {}
for i in range(1,len(df_imaging)):
    if df_imaging.PATIENT[i] == df_imaging.PATIENT[prev] :
        #print(i)
        continue
    else :
        list1 = df_imaging.BODYSITE_CODE[prev:i].values
        list2 = df_imaging.MODALITY_CODE[prev:i].values
        list3 = df_imaging.SOP_CODE[prev:i].values
        dict1[df_imaging.PATIENT[prev]] = list1
        dict2[df_imaging.PATIENT[prev]] = list2
        dict3[df_imaging.PATIENT[prev]] = list3
       
        prev = i
        if i == len(df_imaging)-1 :
            val=1
if val==1:
    list1 = df_imaging.BODYSITE_CODE[prev]
    list2 = df_imaging.MODALITY_CODE[prev]
    list3 = df_imaging.SOP_CODE[prev]
  
    dict1[df_imaging.PATIENT[prev]] = list1
    dict2[df_imaging.PATIENT[prev]] = list2
    dict3[df_imaging.PATIENT[prev]] = list3
   
else :
    list1 = [df_imaging.BODYSITE_CODE[prev:len(df_imaging)]]
    list2 = [df_imaging.MODALITY_CODE[prev:len(df_imaging)]]
    list3 = [df_imaging.SOP_CODE[prev:len(df_imaging)]]
   
    dict1[df_imaging.PATIENT[prev]] = list1
    dict2[df_imaging.PATIENT[prev]] = list2
    dict3[df_imaging.PATIENT[prev]] = list3

In [132]:
len(dict1)

247

In [133]:
df_imaging.PATIENT.nunique()

247

In [134]:
df_imaging.sort_values('PATIENT',inplace=True)

In [135]:
prev = 0
for i in range(1,len(df_imaging)):
    if df_imaging.PATIENT[i] == df_imaging.PATIENT[prev] :
        df_imaging.drop(i,axis=0,inplace=True)
    else:
        prev=i

In [136]:
df_imaging

,PATIENT,BODYSITE_CODE,MODALITY_CODE,SOP_CODE
257,02f9aadd-72de-4b20-b381-f4c3b1cf7aa3,50519007,US,1.2.840.10008.5.1.4.1.1.6.1
90,03172f6e-fb21-4770-8eef-513730174ab7,40983000,DX,1.2.840.10008.5.1.4.1.1.1.1
797,0325261f-61eb-46f8-acc6-89d15053fecd,261179002,US,1.2.840.10008.5.1.4.1.1.3.1
804,03612a7e-6460-4ef6-9528-59d60f970b93,261179002,US,1.2.840.10008.5.1.4.1.1.3.1
776,03c5e223-c016-4477-947f-22c691d6a62c,51299004,DX,1.2.840.10008.5.1.4.1.1.1.1
...,...,...,...,...
14,f71bb059-3634-47a6-b689-04320a5c4387,51299004,DX,1.2.840.10008.5.1.4.1.1.1.1
84,f7d7b580-e670-4921-bc67-550ec468d506,344001,DX,1.2.840.10008.5.1.4.1.1.1.1
724,fb91570f-6f79-4d03-bf4f-d3d58138328e,40983000,DX,1.2.840.10008.5.1.4.1.1.1.1
848,fca3178e-fb68-41c3-8598-702d3ca68b96,8205005,DX,1.2.840.10008.5.1.4.1.1.1.1
411,fd3acd35-add1-4634-8c90-68ed0f638fde,261179002,US,1.2.840.10008.5.1.4.1.1.3.1

In [137]:
df_imaging.reset_index(inplace=True)

In [138]:
df_imaging['BODYSITE_CODE'] = df_imaging['BODYSITE_CODE'].astype(object)
df_imaging['MODALITY_CODE'] = df_imaging['MODALITY_CODE'].astype(object)
df_imaging['SOP_CODE'] = df_imaging['SOP_CODE'].astype(object)

In [139]:
for i in range(len(df_imaging)):
    df_imaging.BODYSITE_CODE[i] = dict1[df_imaging.PATIENT[i]]
    df_imaging.MODALITY_CODE[i] = dict2[df_imaging.PATIENT[i]]
    df_imaging.SOP_CODE[i] = dict3[df_imaging.PATIENT[i]]

/tmp/ipykernel_25837/1233921523.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_imaging.BODYSITE_CODE[i] = dict1[df_imaging.PATIENT[i]]
/tmp/ipykernel_25837/1233921523.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_imaging.MODALITY_CODE[i] = dict2[df_imaging.PATIENT[i]]
/tmp/ipykernel_25837/1233921523.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_imaging.SOP_CODE[i] = dict3[df_imaging.PATIENT[i]]

In [140]:
df_imaging

,index,PATIENT,BODYSITE_CODE,MODALITY_CODE,SOP_CODE
0,257,02f9aadd-72de-4b20-b381-f4c3b1cf7aa3,[50519007],[US],[1.2.840.10008.5.1.4.1.1.6.1]
1,90,03172f6e-fb21-4770-8eef-513730174ab7,[40983000],[DX],[1.2.840.10008.5.1.4.1.1.1.1]
2,797,0325261f-61eb-46f8-acc6-89d15053fecd,"[261179002, 51185008, 261179002, 51185008]","[US, CR, US, DX]","[1.2.840.10008.5.1.4.1.1.3.1, 1.2.840.10008.5...."
3,804,03612a7e-6460-4ef6-9528-59d60f970b93,"[261179002, 261179002, 261179002, 51185008, 26...","[US, US, US, CR, US, DX]","[1.2.840.10008.5.1.4.1.1.3.1, 1.2.840.10008.5...."
4,776,03c5e223-c016-4477-947f-22c691d6a62c,[51299004],[DX],[1.2.840.10008.5.1.4.1.1.1.1]
...,...,...,...,...,...
243,14,f71bb059-3634-47a6-b689-04320a5c4387,[51299004],[DX],[1.2.840.10008.5.1.4.1.1.1.1]
244,84,f7d7b580-e670-4921-bc67-550ec468d506,[344001],[DX],[1.2.840.10008.5.1.4.1.1.1.1]
245,724,fb91570f-6f79-4d03-bf4f-d3d58138328e,"[40983000, 261179002, 51185008, 261179002, 511...","[DX, US, CR, US, DX, US, CR, US, DX]","[1.2.840.10008.5.1.4.1.1.1.1, 1.2.840.10008.5...."
246,848,fca3178e-fb68-41c3-8598-702d3ca68b96,"[[8205005, 261179002, 51185008, 261179002, 511...","[[DX, US, CR, US, CR, US, DX]]","[[1.2.840.10008.5.1.4.1.1.1.1, 1.2.840.10008.5..."
247,411,fd3acd35-add1-4634-8c90-68ed0f638fde,"[261179002, 261179002, 51185008, 261179002, 51...","[US, US, CR, US, DX, US, CR, US, DX]","[1.2.840.10008.5.1.4.1.1.3.1, 1.2.840.10008.5...."

In [141]:
df_imaging.drop(['index'],axis=1,inplace = True)

In [142]:
df_imaging.rename(columns = {'BODYSITE_CODE':'IMAGING_BODYSITE_CODE','MODALITY_CODE':'IMAGING_MODALITY_CODE','SOP_CODE':'IMAGING_SOP_CODE'},inplace = True)

In [143]:
df = pd.merge(df,df_imaging,how = 'outer',left_on='Id',right_on='PATIENT')

In [144]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,...,ENCOUNTERCLASS,ENCOUNTERCODE,BASE_ENCOUNTER_COST,ENCOUNTER_TOTAL_CLAIM_COST,ENCOUNTER_PAYER_COVERAGE,Encounter_Time,PATIENT,IMAGING_BODYSITE_CODE,IMAGING_MODALITY_CODE,IMAGING_SOP_CODE
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,...,"[ambulatory, ambulatory, wellness, wellness, a...","[185345009, 185345009, 162673000, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]","[900.0, 900.0, 900.0, 1800.0, 900.0, 900.0]",NaN,NaN,NaN,NaN
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,...,"[ambulatory, wellness, wellness, ambulatory, o...","[185345009, 162673000, 162673000, 185345009, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[54.16, 129.16, 129.16, 54.16, 54.16, 129.16]","[1500.0, 900.0, 1800.0, 900.0, 900.0, 900.0]",NaN,NaN,NaN,NaN
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,...,"[outpatient, ambulatory, wellness, ambulatory,...","[185349003, 185345009, 162673000, 185345009, 7...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[0.0, 49.16, 129.16, 49.16, 0.0, 129.16, 129.1...","[900.0, 900.0, 1800.0, 900.0, 900.0, 900.0, 90...",NaN,NaN,NaN,NaN
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,...,"[ambulatory, wellness, outpatient, outpatient,...","[185345009, 162673000, 698314001, 308335008, 6...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[64.16, 129.16, 0.0, 0.0, 0.0, 129.16, 0.0, 0....","[900.0, 1800.0, 900.0, 3960.0, 900.0, 900.0, 2...",NaN,NaN,NaN,NaN
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,...,"[wellness, wellness, ambulatory, ambulatory, w...","[162673000, 410620009, 185345009, 185345009, 4...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 69.16, 69.16, 129.16, 69.16, ...","[900.0, 1800.0, 1800.0, 1800.0, 1800.0, 900.0,...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,...,"[wellness, ambulatory, ambulatory, wellness, a...","[162673000, 390906007, 390906007, 162673000, 3...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[89.16, 89.16, 89.16, 89.16, 89.16, 89.16, 89....","[1800.0, 900.0, 900.0, 2700.0, 900.0, 1800.0, ...",NaN,NaN,NaN,NaN
1168,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,...,"[outpatient, ambulatory, wellness, wellness, w...","[185349003, 185345009, 162673000, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[0.0, 59.16, 129.16, 129.16, 129.16, 59.16, 12...","[900.0, 900.0, 1800.0, 1800.0, 900.0, 900.0, 9...",NaN,NaN,NaN,NaN
1169,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,...,"[wellness, wellness, wellness, outpatient, wel...","[162673000, 162673000, 162673000, 185349003, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[54.16, 54.16, 54.16, 54.16, 69.16, 69.16, 54....","[900.0, 900.0, 1800.0, 900.0, 1800.0, 18900.0,...",NaN,NaN,NaN,NaN
1170,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,...,"[ambulatory, wellness, ambulatory, wellness, e...","[185347001, 162673000, 185347001, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[64.16, 89.16, 89.16, 89.16, 89.16, 0.0, 89.16...","[5700.0, 900.0, 2700.0, 900.0, 5400.0, 0.0, 54...",fca3178e-fb68-41c3-8598-702d3ca68b96,"[[8205005, 261179002, 51185008, 261179002, 511...","[[DX, US, CR, US, CR, US, DX]]","[[1.2.840.10008.5.1.4.1.1.1.1, 1.2.840.10008.5..."
1171,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,...,"[ambulatory, wellness, wellness, wellness, wel...","[185345009, 162673000, 162673000, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[89.16, 129.16, 129.16, 129.16, 129.16, 129.16...","[900.0, 900.0, 1800.0, 900.0, 1800.0, 900.0, 1...",NaN,NaN,NaN,NaN

In [145]:
df.drop(['PATIENT'],axis=1,inplace=True)
df.fillna(0,inplace=True)

In [146]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,...,PAYER,ENCOUNTERCLASS,ENCOUNTERCODE,BASE_ENCOUNTER_COST,ENCOUNTER_TOTAL_CLAIM_COST,ENCOUNTER_PAYER_COVERAGE,Encounter_Time,IMAGING_BODYSITE_CODE,IMAGING_MODALITY_CODE,IMAGING_SOP_CODE
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,...,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,"[ambulatory, ambulatory, wellness, wellness, a...","[185345009, 185345009, 162673000, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]","[900.0, 900.0, 900.0, 1800.0, 900.0, 900.0]",0,0,0
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,...,6e2f1a2d-27bd-3701-8d08-dae202c58632,"[ambulatory, wellness, wellness, ambulatory, o...","[185345009, 162673000, 162673000, 185345009, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[129.16, 129.16, 129.16, 129.16, 129.16, 129.16]","[54.16, 129.16, 129.16, 54.16, 54.16, 129.16]","[1500.0, 900.0, 1800.0, 900.0, 900.0, 900.0]",0,0,0
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,...,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,"[outpatient, ambulatory, wellness, ambulatory,...","[185349003, 185345009, 162673000, 185345009, 7...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[0.0, 49.16, 129.16, 49.16, 0.0, 129.16, 129.1...","[900.0, 900.0, 1800.0, 900.0, 900.0, 900.0, 90...",0,0,0
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,...,4d71f845-a6a9-3c39-b242-14d25ef86a8d,"[ambulatory, wellness, outpatient, outpatient,...","[185345009, 162673000, 698314001, 308335008, 6...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[64.16, 129.16, 0.0, 0.0, 0.0, 129.16, 0.0, 0....","[900.0, 1800.0, 900.0, 3960.0, 900.0, 900.0, 2...",0,0,0
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,...,047f6ec3-6215-35eb-9608-f9dda363a44c,"[wellness, wellness, ambulatory, ambulatory, w...","[162673000, 410620009, 185345009, 185345009, 4...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 69.16, 69.16, 129.16, 69.16, ...","[900.0, 1800.0, 1800.0, 1800.0, 1800.0, 900.0,...",0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,...,7caa7254-5050-3b5e-9eae-bd5ea30e809c,"[wellness, ambulatory, ambulatory, wellness, a...","[162673000, 390906007, 390906007, 162673000, 3...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[89.16, 89.16, 89.16, 89.16, 89.16, 89.16, 89....","[1800.0, 900.0, 900.0, 2700.0, 900.0, 1800.0, ...",0,0,0
1168,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,...,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,"[outpatient, ambulatory, wellness, wellness, w...","[185349003, 185345009, 162673000, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[0.0, 59.16, 129.16, 129.16, 129.16, 59.16, 12...","[900.0, 900.0, 1800.0, 1800.0, 900.0, 900.0, 9...",0,0,0
1169,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,...,6e2f1a2d-27bd-3701-8d08-dae202c58632,"[wellness, wellness, wellness, outpatient, wel...","[162673000, 162673000, 162673000, 185349003, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[54.16, 54.16, 54.16, 54.16, 69.16, 69.16, 54....","[900.0, 900.0, 1800.0, 900.0, 1800.0, 18900.0,...",0,0,0
1170,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,...,4d71f845-a6a9-3c39-b242-14d25ef86a8d,"[ambulatory, wellness, ambulatory, wellness, e...","[185347001, 162673000, 185347001, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[64.16, 89.16, 89.16, 89.16, 89.16, 0.0, 89.16...","[5700.0, 900.0, 2700.0, 900.0, 5400.0, 0.0, 54...","[[8205005, 261179002, 51185008, 261179002, 511...","[[DX, US, CR, US, CR, US, DX]]","[[1.2.840.10008.5.1.4.1.1.1.1, 1.2.840.10008.5..."
1171,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,...,7caa7254-5050-3b5e-9eae-bd5ea30e809c,"[ambulatory, wellness, wellness, wellness, wel...","[185345009, 162673000, 162673000, 162673000, 1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[129.16, 129.16, 129.16, 129.16, 129.16, 129.1...","[89.16, 129.16, 129.16, 129.16, 129.16, 129.16...","[900.0, 900.0, 1800.0, 900.0, 1800.0, 900.0, 1...",0,0,0

In [147]:
df_immunizations

,DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST
0,2010-07-27T12:58:08Z,10339b10-3cd1-4ac3-ac13-ec26728cb592,dae2b7cb-1316-4b78-954f-fa610a6c6d0e,140,Influenza seasonal injectable preservative ...,140.52
1,2010-11-20T03:04:34Z,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,7ff86631-0378-4bfc-92ce-1edd697eb18e,140,Influenza seasonal injectable preservative ...,140.52
2,2012-01-23T17:45:28Z,034e9e3b-2def-4559-bb2a-7850888ae060,e88bc3a9-007c-405e-aabc-792a38f4aa2b,140,Influenza seasonal injectable preservative ...,140.52
3,2011-11-26T03:04:34Z,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,1923c698-accd-4d70-ba09-e1938f6e96d1,140,Influenza seasonal injectable preservative ...,140.52
4,2011-07-28T15:02:18Z,1d604da9-9a81-4ba9-80c2-de3375d59b40,b85c339a-6076-43ed-b9d0-9cf013dec49d,140,Influenza seasonal injectable preservative ...,140.52
...,...,...,...,...,...,...
15473,2011-05-28T17:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,9159cac1-2310-4e53-81eb-aa08d6e3537d,140,Influenza seasonal injectable preservative ...,140.52
15474,2012-06-02T17:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,d015ae93-6fb8-4a19-9109-543f527a6878,140,Influenza seasonal injectable preservative ...,140.52
15475,2013-06-08T17:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,f4d4f19e-6377-4627-8a6f-760beba1fc6b,140,Influenza seasonal injectable preservative ...,140.52
15476,2014-06-14T17:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,e9dfe071-cf14-4d7f-8c8a-879497541f2d,140,Influenza seasonal injectable preservative ...,140.52
15477,2015-06-20T17:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,bd3bfc3c-4f52-4d9c-aa01-60a084b2ddcd,140,Influenza seasonal injectable preservative ...,140.52

In [148]:
df_immunizations.PATIENT.nunique()

1169

In [149]:
df_immunizations.drop(['DATE','ENCOUNTER','DESCRIPTION'],axis=1,inplace=True)

In [150]:
df_immunizations

                                    PATIENT  CODE  BASE_COST
0      10339b10-3cd1-4ac3-ac13-ec26728cb592   140     140.52
1      f5dcd418-09fe-4a2f-baa0-3da800bd8c3a   140     140.52
2      034e9e3b-2def-4559-bb2a-7850888ae060   140     140.52
3      f5dcd418-09fe-4a2f-baa0-3da800bd8c3a   140     140.52
4      1d604da9-9a81-4ba9-80c2-de3375d59b40   140     140.52
...                                     ...   ...        ...
15473  fc817953-cc8b-45db-9c85-7c0ced8fa90d   140     140.52
15474  fc817953-cc8b-45db-9c85-7c0ced8fa90d   140     140.52
15475  fc817953-cc8b-45db-9c85-7c0ced8fa90d   140     140.52
15476  fc817953-cc8b-45db-9c85-7c0ced8fa90d   140     140.52
15477  fc817953-cc8b-45db-9c85-7c0ced8fa90d   140     140.52

[15478 rows x 3 columns]

In [151]:
df_immunizations.sort_values('PATIENT',inplace=True)

In [152]:
df_immunizations

                                    PATIENT  CODE  BASE_COST
10412  00185faa-2760-4218-9bf5-db301acf8274    62     140.52
10417  00185faa-2760-4218-9bf5-db301acf8274   140     140.52
10416  00185faa-2760-4218-9bf5-db301acf8274   140     140.52
10415  00185faa-2760-4218-9bf5-db301acf8274   140     140.52
10414  00185faa-2760-4218-9bf5-db301acf8274    62     140.52
...                                     ...   ...        ...
11428  ffcfa457-00c2-4405-9837-ac2781549c7e   133     140.52
11427  ffcfa457-00c2-4405-9837-ac2781549c7e    20     140.52
11426  ffcfa457-00c2-4405-9837-ac2781549c7e    10     140.52
11424  ffcfa457-00c2-4405-9837-ac2781549c7e    49     140.52
11443  ffcfa457-00c2-4405-9837-ac2781549c7e    83     140.52

[15478 rows x 3 columns]

In [153]:
df_immunizations.reset_index(inplace=True)

In [154]:
prev = 0 
dict1 = {}
dict2 = {}

for i in range(1,len(df_immunizations)):
    if df_immunizations.PATIENT[i] == df_immunizations.PATIENT[prev] :
        #print(i)
        continue
    else :
        list1 = df_immunizations.CODE[prev:i].values
        list2 = df_immunizations.BASE_COST[prev:i].values
        
        dict1[df_immunizations.PATIENT[prev]] = list1
        dict2[df_immunizations.PATIENT[prev]] = list2
        
       
        prev = i
        if i == len(df_immunizations)-1 :
            val=1
if val==1:
    list1 = df_immunizations.CODE[prev]
    list2 = df_immunizations.BASE_COST[prev]
    
  
    dict1[df_immunizations.PATIENT[prev]] = list1
    dict2[df_immunizations.PATIENT[prev]] = list2
    
   
else :
    list1 = [df_immunizations.CODE[prev:len(df_immunizations)]]
    list2 = [df_immunizations.BASE_COST[prev:len(df_immunizations)]]
    
   
    dict1[df_immunizations.PATIENT[prev]] = list1
    dict2[df_immunizations.PATIENT[prev]] = list2

In [155]:
len(dict1)

1169

In [156]:
prev = 0
for i in range(1,len(df_immunizations)):
    if df_immunizations.PATIENT[i] == df_immunizations.PATIENT[prev] :
        df_immunizations.drop(i,axis=0,inplace=True)
    else:
        prev=i

In [157]:
df_immunizations

       index                               PATIENT  CODE  BASE_COST
0      10412  00185faa-2760-4218-9bf5-db301acf8274    62     140.52
16      9799  0042862c-9889-4a2e-b782-fac1e540ecb4    20     140.52
46     14558  0047123f-12e7-486c-82df-53b3a450e365   140     140.52
59      2478  010d4a3a-2316-45ed-ae15-16f01c611674    62     140.52
76        92  01207ecd-9dff-4754-8887-4652eda231e2     8     140.52
...      ...                                   ...   ...        ...
15405  10904  ff02f237-fedb-453b-85b1-ebfc2609c312   114     140.52
15422   5648  ff3714ac-c7e3-4910-905e-2a321eb28144   140     140.52
15439  10503  ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be   140     140.52
15448  13058  ffa37e71-fa14-4e84-ba9d-aece8d1d99f9   140     140.52
15452  11444  ffcfa457-00c2-4405-9837-ac2781549c7e    20     140.52

[1169 rows x 4 columns]

In [158]:
df_immunizations.reset_index(inplace=True)

In [159]:
df_immunizations['CODE'] = df_immunizations['CODE'].astype(object)
df_immunizations['BASE_COST'] = df_immunizations['BASE_COST'].astype(object)

In [160]:
for i in range(len(df_immunizations)):
    df_immunizations.CODE[i] = dict1[df_immunizations.PATIENT[i]]
    df_immunizations.BASE_COST[i] = dict2[df_immunizations.PATIENT[i]]

/tmp/ipykernel_25837/1840525592.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_immunizations.CODE[i] = dict1[df_immunizations.PATIENT[i]]
/tmp/ipykernel_25837/1840525592.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_immunizations.BASE_COST[i] = dict2[df_immunizations.PATIENT[i]]

In [161]:
df_immunizations

,level_0,index,PATIENT,CODE,BASE_COST
0,0,10412,00185faa-2760-4218-9bf5-db301acf8274,"[62, 140, 140, 140, 62, 140, 140, 114, 62, 140...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
1,16,9799,0042862c-9889-4a2e-b782-fac1e540ecb4,"[20, 83, 133, 3, 21, 140, 49, 8, 133, 20, 140,...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
2,46,14558,0047123f-12e7-486c-82df-53b3a450e365,"[140, 140, 140, 140, 140, 140, 140, 113, 140, ...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
3,59,2478,010d4a3a-2316-45ed-ae15-16f01c611674,"[62, 140, 140, 140, 62, 140, 140, 140, 114, 11...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
4,76,92,01207ecd-9dff-4754-8887-4652eda231e2,"[8, 133, 20, 140, 10, 133, 20, 10, 49, 133, 20...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
...,...,...,...,...,...
1164,15405,10904,ff02f237-fedb-453b-85b1-ebfc2609c312,"[114, 140, 115, 140, 62, 114, 140, 62, 43, 140...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
1165,15422,5648,ff3714ac-c7e3-4910-905e-2a321eb28144,"[140, 113, 62, 140, 114, 140, 140, 140, 140, 1...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
1166,15439,10503,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,"[140, 140, 140, 52, 140, 52, 140, 113, 140]","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
1167,15448,13058,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,"[140, 140, 113, 140]","[140.52, 140.52, 140.52, 140.52]"
1168,15452,11444,ffcfa457-00c2-4405-9837-ac2781549c7e,"[[20, 8, 8, 49, 119, 83, 133, 3, 21, 49, 8, 13...","[[140.52, 140.52, 140.52, 140.52, 140.52, 140...."

In [162]:
df_immunizations.drop(['index','level_0'],axis=1,inplace=True)
df_immunizations.rename(columns = {'CODE':'Immunization_Code','BASE_COST':'Immunization_BASE_COST'},inplace=True)

In [163]:
df_immunizations

,PATIENT,Immunization_Code,Immunization_BASE_COST
0,00185faa-2760-4218-9bf5-db301acf8274,"[62, 140, 140, 140, 62, 140, 140, 114, 62, 140...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
1,0042862c-9889-4a2e-b782-fac1e540ecb4,"[20, 83, 133, 3, 21, 140, 49, 8, 133, 20, 140,...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
2,0047123f-12e7-486c-82df-53b3a450e365,"[140, 140, 140, 140, 140, 140, 140, 113, 140, ...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
3,010d4a3a-2316-45ed-ae15-16f01c611674,"[62, 140, 140, 140, 62, 140, 140, 140, 114, 11...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
4,01207ecd-9dff-4754-8887-4652eda231e2,"[8, 133, 20, 140, 10, 133, 20, 10, 49, 133, 20...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
...,...,...,...
1164,ff02f237-fedb-453b-85b1-ebfc2609c312,"[114, 140, 115, 140, 62, 114, 140, 62, 43, 140...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
1165,ff3714ac-c7e3-4910-905e-2a321eb28144,"[140, 113, 62, 140, 114, 140, 140, 140, 140, 1...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
1166,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,"[140, 140, 140, 52, 140, 52, 140, 113, 140]","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5..."
1167,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,"[140, 140, 113, 140]","[140.52, 140.52, 140.52, 140.52]"
1168,ffcfa457-00c2-4405-9837-ac2781549c7e,"[[20, 8, 8, 49, 119, 83, 133, 3, 21, 49, 8, 13...","[[140.52, 140.52, 140.52, 140.52, 140.52, 140...."

In [164]:
df = pd.merge(df,df_immunizations,how = 'outer',left_on='Id',right_on='PATIENT')

In [165]:
df.drop(['PATIENT'],axis=1,inplace=True)

In [166]:
df_medications.fillna(0,inplace=True)

In [167]:
df_medications

,START,STOP,PATIENT,PAYER,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,REASONDESCRIPTION
0,2010-05-05T00:26:23Z,2011-04-30T00:26:23Z,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,1e0d6b0e-1711-4a25-99f9-b1c700c9b260,389221,Etonogestrel 68 MG Drug Implant,677.08,0.0,12,8124.96,0.0,0
1,2011-04-30T00:26:23Z,2012-04-24T00:26:23Z,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,6aa37300-d1b4-48e7-a2f8-5e0f70f48f38,389221,Etonogestrel 68 MG Drug Implant,624.09,0.0,12,7489.08,0.0,0
2,2012-04-24T00:26:23Z,2013-04-19T00:26:23Z,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,7253a9f9-6f6d-429a-926a-7b1d424eae3f,748856,Yaz 28 Day Pack,43.32,0.0,12,519.84,0.0,0
3,2011-05-13T12:58:08Z,2011-05-27T12:58:08Z,10339b10-3cd1-4ac3-ac13-ec26728cb592,d47b3510-2895-3b70-9897-342d681c769d,e1ab4933-07a1-49f0-b4bd-05500919061d,313782,Acetaminophen 325 MG Oral Tablet,8.14,0.0,1,8.14,10509002.0,Acute bronchitis (disorder)
4,2011-12-08T15:02:18Z,2011-12-22T15:02:18Z,1d604da9-9a81-4ba9-80c2-de3375d59b40,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,792fae81-a007-44b0-8221-46953737b089,562251,Amoxicillin 250 MG / Clavulanate 125 MG Oral T...,11.91,0.0,1,11.91,444814009.0,Viral sinusitis (disorder)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42984,1983-09-08T17:27:52Z,1983-09-29T17:27:52Z,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,9e9670e5-da7f-4111-98a6-21d5e0aadd86,243670,Aspirin 81 MG Oral Tablet,7.35,0.0,1,7.35,0.0,0
42985,1984-09-23T17:27:52Z,1984-11-22T17:27:52Z,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,8d7d70be-467d-430f-8497-25aa2c1276b8,313782,Acetaminophen 325 MG Oral Tablet,5.26,0.0,2,10.52,0.0,0
42986,1987-09-27T17:27:52Z,0,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,48ea35a8-37cd-41d2-86c1-7785b514c453,866414,24 HR metoprolol succinate 100 MG Extended Rel...,263.49,0.0,30,7904.70,88805009.0,Chronic congestive heart failure (disorder)
42987,1987-09-27T17:27:52Z,0,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,48ea35a8-37cd-41d2-86c1-7785b514c453,313988,Furosemide 40 MG Oral Tablet,263.49,0.0,30,7904.70,88805009.0,Chronic congestive heart failure (disorder)
42988,1990-03-15T17:27:52Z,0,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,aaee3543-3edb-40af-a276-3bb027cac0dc,1719286,10 ML Furosemide 10 MG/ML Injection,263.49,0.0,1,263.49,88805009.0,Chronic congestive heart failure (disorder)

In [168]:
df_medications.drop(['REASONDESCRIPTION','ENCOUNTER'],axis=1,inplace=True)

In [169]:
df_medications['Medication_Time'] = 0.0

In [170]:
date = datetime.date.today()
for i in range(len(df_medications)):
    if df_medications.STOP[i] == date:
        df_medications.STOP[i] = pd.Timestamp.utcnow()

In [171]:
df_medications

,START,STOP,PATIENT,PAYER,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,Medication_Time
0,2010-05-05T00:26:23Z,2011-04-30T00:26:23Z,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,389221,Etonogestrel 68 MG Drug Implant,677.08,0.0,12,8124.96,0.0,0.0
1,2011-04-30T00:26:23Z,2012-04-24T00:26:23Z,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,389221,Etonogestrel 68 MG Drug Implant,624.09,0.0,12,7489.08,0.0,0.0
2,2012-04-24T00:26:23Z,2013-04-19T00:26:23Z,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,748856,Yaz 28 Day Pack,43.32,0.0,12,519.84,0.0,0.0
3,2011-05-13T12:58:08Z,2011-05-27T12:58:08Z,10339b10-3cd1-4ac3-ac13-ec26728cb592,d47b3510-2895-3b70-9897-342d681c769d,313782,Acetaminophen 325 MG Oral Tablet,8.14,0.0,1,8.14,10509002.0,0.0
4,2011-12-08T15:02:18Z,2011-12-22T15:02:18Z,1d604da9-9a81-4ba9-80c2-de3375d59b40,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,562251,Amoxicillin 250 MG / Clavulanate 125 MG Oral T...,11.91,0.0,1,11.91,444814009.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
42984,1983-09-08T17:27:52Z,1983-09-29T17:27:52Z,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,243670,Aspirin 81 MG Oral Tablet,7.35,0.0,1,7.35,0.0,0.0
42985,1984-09-23T17:27:52Z,1984-11-22T17:27:52Z,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,313782,Acetaminophen 325 MG Oral Tablet,5.26,0.0,2,10.52,0.0,0.0
42986,1987-09-27T17:27:52Z,0,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,866414,24 HR metoprolol succinate 100 MG Extended Rel...,263.49,0.0,30,7904.70,88805009.0,0.0
42987,1987-09-27T17:27:52Z,0,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,313988,Furosemide 40 MG Oral Tablet,263.49,0.0,30,7904.70,88805009.0,0.0
42988,1990-03-15T17:27:52Z,0,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,1719286,10 ML Furosemide 10 MG/ML Injection,263.49,0.0,1,263.49,88805009.0,0.0

In [172]:
for i in range(len(df_medications)):
    df_medications.START[i] = pd.to_datetime(df_medications.START[i],utc=True)
    df_medications.STOP[i] = pd.to_datetime(df_medications.STOP[i],utc=True)

/tmp/ipykernel_25837/2025909897.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.START[i] = pd.to_datetime(df_medications.START[i],utc=True)
/tmp/ipykernel_25837/2025909897.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.STOP[i] = pd.to_datetime(df_medications.STOP[i],utc=True)

In [173]:
df_medications

,START,STOP,PATIENT,PAYER,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,Medication_Time
0,2010-05-05 00:26:23+00:00,2011-04-30 00:26:23+00:00,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,389221,Etonogestrel 68 MG Drug Implant,677.08,0.0,12,8124.96,0.0,0.0
1,2011-04-30 00:26:23+00:00,2012-04-24 00:26:23+00:00,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,389221,Etonogestrel 68 MG Drug Implant,624.09,0.0,12,7489.08,0.0,0.0
2,2012-04-24 00:26:23+00:00,2013-04-19 00:26:23+00:00,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,748856,Yaz 28 Day Pack,43.32,0.0,12,519.84,0.0,0.0
3,2011-05-13 12:58:08+00:00,2011-05-27 12:58:08+00:00,10339b10-3cd1-4ac3-ac13-ec26728cb592,d47b3510-2895-3b70-9897-342d681c769d,313782,Acetaminophen 325 MG Oral Tablet,8.14,0.0,1,8.14,10509002.0,0.0
4,2011-12-08 15:02:18+00:00,2011-12-22 15:02:18+00:00,1d604da9-9a81-4ba9-80c2-de3375d59b40,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,562251,Amoxicillin 250 MG / Clavulanate 125 MG Oral T...,11.91,0.0,1,11.91,444814009.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
42984,1983-09-08 17:27:52+00:00,1983-09-29 17:27:52+00:00,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,243670,Aspirin 81 MG Oral Tablet,7.35,0.0,1,7.35,0.0,0.0
42985,1984-09-23 17:27:52+00:00,1984-11-22 17:27:52+00:00,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,313782,Acetaminophen 325 MG Oral Tablet,5.26,0.0,2,10.52,0.0,0.0
42986,1987-09-27 17:27:52+00:00,1970-01-01 00:00:00+00:00,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,866414,24 HR metoprolol succinate 100 MG Extended Rel...,263.49,0.0,30,7904.70,88805009.0,0.0
42987,1987-09-27 17:27:52+00:00,1970-01-01 00:00:00+00:00,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,313988,Furosemide 40 MG Oral Tablet,263.49,0.0,30,7904.70,88805009.0,0.0
42988,1990-03-15 17:27:52+00:00,1970-01-01 00:00:00+00:00,fca3178e-fb68-41c3-8598-702d3ca68b96,7caa7254-5050-3b5e-9eae-bd5ea30e809c,1719286,10 ML Furosemide 10 MG/ML Injection,263.49,0.0,1,263.49,88805009.0,0.0

In [174]:
for i in range(len(df_medications)):
    df_medications.Medication_Time[i] = pd.Timedelta(df_medications.STOP[i]-df_medications.START[i]).seconds

/tmp/ipykernel_25837/3513677055.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.Medication_Time[i] = pd.Timedelta(df_medications.STOP[i]-df_medications.START[i]).seconds

In [175]:
for i in range(len(df_medications)):

    start = df_medications.START[i]
    stop = df_medications.STOP[i]
    age = stop.year - start.year - ((stop.month,stop.day)<(start.month,start.day))
    if stop.month>start.month :
        age = age + (stop.month - start.month)/12
    else :
        age = age + (12 + stop.month - start.month)/12 
    df_medications.Medication_Time[i] += age*365*24*60*60

/tmp/ipykernel_25837/1381831848.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.Medication_Time[i] += age*365*24*60*60

In [176]:
df_medications['Medication_Time'] /= 3600*24

In [177]:
df_medications.drop(['START','STOP','PAYER'],axis=1,inplace=True)

In [178]:
df_medications

,PATIENT,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,Medication_Time
0,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,389221,Etonogestrel 68 MG Drug Implant,677.08,0.0,12,8124.96,0.0,334.583333
1,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,389221,Etonogestrel 68 MG Drug Implant,624.09,0.0,12,7489.08,0.0,365.000000
2,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,748856,Yaz 28 Day Pack,43.32,0.0,12,519.84,0.0,365.000000
3,10339b10-3cd1-4ac3-ac13-ec26728cb592,313782,Acetaminophen 325 MG Oral Tablet,8.14,0.0,1,8.14,10509002.0,365.000000
4,1d604da9-9a81-4ba9-80c2-de3375d59b40,562251,Amoxicillin 250 MG / Clavulanate 125 MG Oral T...,11.91,0.0,1,11.91,444814009.0,365.000000
...,...,...,...,...,...,...,...,...,...
42984,fca3178e-fb68-41c3-8598-702d3ca68b96,243670,Aspirin 81 MG Oral Tablet,7.35,0.0,1,7.35,0.0,365.000000
42985,fca3178e-fb68-41c3-8598-702d3ca68b96,313782,Acetaminophen 325 MG Oral Tablet,5.26,0.0,2,10.52,0.0,60.833333
42986,fca3178e-fb68-41c3-8598-702d3ca68b96,866414,24 HR metoprolol succinate 100 MG Extended Rel...,263.49,0.0,30,7904.70,88805009.0,-6448.061019
42987,fca3178e-fb68-41c3-8598-702d3ca68b96,313988,Furosemide 40 MG Oral Tablet,263.49,0.0,30,7904.70,88805009.0,-6448.061019
42988,fca3178e-fb68-41c3-8598-702d3ca68b96,1719286,10 ML Furosemide 10 MG/ML Injection,263.49,0.0,1,263.49,88805009.0,-7360.561019

In [187]:
prev = 0 
dict1 = {}
dict2 = {}
dict3 = {}
dict4 = {}
dict5 = {}
dict6 = {}
dict7 = {}
dict8 = {}
val=0
for i in range(1,len(df_medications)):
    if df_medications.PATIENT[i] == df_medications.PATIENT[prev] :
        #print(i)
        continue
    else :
        list1 = df_medications.CODE[prev:i].values
        list2 = df_medications.BASE_COST[prev:i].values
        list3 = df_medications.PAYER_COVERAGE[prev:i].values
        list4 = df_medications.DISPENSES[prev:i].values
        list5 = df_medications.TOTALCOST[prev:i].values
        list6 = df_medications.REASONCODE[prev:i].values
        list7 = df_medications.Medication_Time[prev:i].values
        list8 = df_medications.DESCRIPTION[prev:i].values
        dict1[df_medications.PATIENT[prev]] = list1
        dict2[df_medications.PATIENT[prev]] = list2
        dict3[df_medications.PATIENT[prev]] = list3
        dict4[df_medications.PATIENT[prev]] = list4
        dict5[df_medications.PATIENT[prev]] = list5
        dict6[df_medications.PATIENT[prev]] = list6
        dict7[df_medications.PATIENT[prev]] = list7
        dict8[df_medications.PATIENT[prev]] = list8
        prev = i
        if i == len(df_medications)-1 :
            val=1
if val==1:
    list1 = df_medications.CODE[prev]
    list2 = df_medications.BASE_COST[prev]
    list3 = df_medications.PAYER_COVERAGE[prev]
    list4 = df_medications.DISPENSES[prev]
    list5 = df_medications.TOTALCOST[prev]
    list6 = df_medications.REASONCODE[prev]
    list7 = df_medications.Medication_Time[prev]
    list8 = df_medications.DESCRIPTION[prev]
    dict1[df_medications.PATIENT[prev]] = list1
    dict2[df_medications.PATIENT[prev]] = list2
    dict3[df_medications.PATIENT[prev]] = list3
    dict4[df_medications.PATIENT[prev]] = list4
    dict5[df_medications.PATIENT[prev]] = list5
    dict6[df_medications.PATIENT[prev]] = list6
    dict7[df_medications.PATIENT[prev]] = list7
    dict8[df_medications.PATIENT[prev]] = list8
else :
    list1 = [df_medications.CODE[prev:len(df_medications)]]
    list2 = [df_medications.BASE_COST[prev:len(df_medications)]]
    list3 = [df_medications.PAYER_COVERAGE[prev:len(df_medications)]]
    list4 = [df_medications.DISPENSES[prev:len(df_medications)]]
    list5 = [df_medications.TOTALCOST[prev:len(df_medications)]]
    list6 = [df_medications.REASONCODE[prev:len(df_medications)]]
    list7 = [df_medications.Medication_Time[prev:len(df_medications)]]
    list8 = [df_medications.DESCRIPTION[prev:len(df_medications)]]
    
    dict1[df_medications.PATIENT[prev]] = list1
    dict2[df_medications.PATIENT[prev]] = list2
    dict3[df_medications.PATIENT[prev]] = list3
    dict4[df_medications.PATIENT[prev]] = list4
    dict5[df_medications.PATIENT[prev]] = list5
    dict6[df_medications.PATIENT[prev]] = list6
    dict7[df_medications.PATIENT[prev]] = list7
    dict8[df_medications.PATIENT[prev]] = list8

In [188]:
len(dict1)

1107

In [189]:
df_medications.sort_values('PATIENT',inplace=True)

In [190]:
prev = 0
for i in range(1,len(df_medications)):
    if df_medications.PATIENT[i] == df_medications.PATIENT[prev] :
        df_medications.drop(i,axis=0,inplace=True)
    else:
        prev=i

In [191]:
df_medications

,index,PATIENT,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,Medication_Time
0,25147,00185faa-2760-4218-9bf5-db301acf8274,834061,Penicillin V Potassium 250 MG Oral Tablet,20.48,0.0,1,20.48,43878008.0,365.000000
1,22123,0042862c-9889-4a2e-b782-fac1e540ecb4,308182,Amoxicillin 250 MG Oral Capsule,14.82,0.0,1,14.82,0.0,365.000000
2,40316,0047123f-12e7-486c-82df-53b3a450e365,562251,Amoxicillin 250 MG / Clavulanate 125 MG Oral T...,55.53,0.0,1,55.53,444814009.0,30.416667
4,5471,010d4a3a-2316-45ed-ae15-16f01c611674,310798,Hydrochlorothiazide 25 MG Oral Tablet,263.49,0.0,12,3161.88,59621000.0,730.000000
5,9000,0149d553-f571-4e99-867e-fcb9625d07c2,831533,Errin 28 Day Pack,37.06,0.0,12,444.72,0.0,334.583333
...,...,...,...,...,...,...,...,...,...,...
2021,26992,ff02f237-fedb-453b-85b1-ebfc2609c312,849574,Naproxen sodium 220 MG Oral Tablet,11.72,0.0,1,11.72,0.0,30.416667
2023,14201,ff3714ac-c7e3-4910-905e-2a321eb28144,562251,Amoxicillin 250 MG / Clavulanate 125 MG Oral T...,115.11,0.0,1,115.11,444814009.0,365.000000
2024,25291,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,807283,Mirena 52 MG Intrauterine System,1132.83,0.0,12,13593.96,0.0,365.000000
2025,35366,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,749785,Ortho Tri-Cyclen 28 Day Pack,35.34,0.0,12,424.08,0.0,365.000000
2026,28317,ffcfa457-00c2-4405-9837-ac2781549c7e,313782,Acetaminophen 325 MG Oral Tablet,5.63,0.0,1,5.63,10509002.0,365.000000

In [192]:
df_medications.reset_index(inplace=True)

In [193]:
df_medications['CODE'] = df_medications['CODE'].astype(object)
df_medications['BASE_COST'] = df_medications['BASE_COST'].astype(object)
df_medications['PAYER_COVERAGE'] = df_medications['PAYER_COVERAGE'].astype(object)
df_medications['DISPENSES'] = df_medications['DISPENSES'].astype(object)
df_medications['TOTALCOST'] = df_medications['TOTALCOST'].astype(object)
df_medications['REASONCODE'] = df_medications['REASONCODE'].astype(object)
df_medications['Medication_Time'] = df_medications['Medication_Time'].astype(object)
df_medications['DESCRIPTION'] = df_medications['DESCRIPTION'].astype(object)

In [194]:
for i in range(len(df_medications)):
    df_medications.CODE[i] = dict1[df_medications.PATIENT[i]]
    df_medications.BASE_COST[i] = dict2[df_medications.PATIENT[i]]
    df_medications.PAYER_COVERAGE[i] = dict3[df_medications.PATIENT[i]]
    df_medications.DISPENSES[i] = dict4[df_medications.PATIENT[i]]
    df_medications.TOTALCOST[i] = dict5[df_medications.PATIENT[i]]
    df_medications.REASONCODE[i] = dict6[df_medications.PATIENT[i]]
    df_medications.Medication_Time[i] = dict7[df_medications.PATIENT[i]]
    df_medications.DESCRIPTION[i] = dict8[df_medications.PATIENT[i]]

/tmp/ipykernel_25837/3980608651.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.CODE[i] = dict1[df_medications.PATIENT[i]]
/tmp/ipykernel_25837/3980608651.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.BASE_COST[i] = dict2[df_medications.PATIENT[i]]
/tmp/ipykernel_25837/3980608651.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.PAYER_COVERAGE[i] = dict3[df_medications.PATIENT[i]]
/tmp/ipykernel_25837/3980608651.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.DISPENSES[i] = dict4[df_medications.PATIENT[i]]
/tmp/ipykernel_25837/3980608651.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.TOTALCOST[i] = dict5[df_medications.PATIENT[i]]
/tmp/ipykernel_25837/3980608651.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.REASONCODE[i] = dict6[df_medications.PATIENT[i]]
/tmp/ipykernel_25837/3980608651.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.Medication_Time[i] = dict7[df_medications.PATIENT[i]]
/tmp/ipykernel_25837/3980608651.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_medications.DESCRIPTION[i] = dict8[df_medications.PATIENT[i]]

In [195]:
df_medications

,level_0,index,PATIENT,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,Medication_Time
0,0,25147,00185faa-2760-4218-9bf5-db301acf8274,[834061],[Penicillin V Potassium 250 MG Oral Tablet],[20.48],[0.0],[1],[20.48],[43878008.0],[365.0]
1,1,22123,0042862c-9889-4a2e-b782-fac1e540ecb4,[308182],[Amoxicillin 250 MG Oral Capsule],[14.82],[0.0],[1],[14.82],[0.0],[365.0]
2,2,40316,0047123f-12e7-486c-82df-53b3a450e365,"[562251, 1043400]",[Amoxicillin 250 MG / Clavulanate 125 MG Oral ...,"[55.53, 8.29]","[0.0, 0.0]","[1, 1]","[55.53, 8.29]","[444814009.0, 10509002.0]","[30.416666666666668, 365.0]"
3,4,5471,010d4a3a-2316-45ed-ae15-16f01c611674,[310798],[Hydrochlorothiazide 25 MG Oral Tablet],[263.49],[0.0],[12],[3161.88],[59621000.0],[730.0]
4,5,9000,0149d553-f571-4e99-867e-fcb9625d07c2,[831533],[Errin 28 Day Pack],[37.06],[0.0],[12],[444.72],[0.0],[334.5833333333333]
...,...,...,...,...,...,...,...,...,...,...,...
1102,2021,26992,ff02f237-fedb-453b-85b1-ebfc2609c312,"[849574, 562251]","[Naproxen sodium 220 MG Oral Tablet, Amoxicill...","[11.72, 16.52]","[0.0, 0.0]","[1, 1]","[11.72, 16.52]","[0.0, 444814009.0]","[30.416666666666668, 30.416666666666668]"
1103,2023,14201,ff3714ac-c7e3-4910-905e-2a321eb28144,[562251],[Amoxicillin 250 MG / Clavulanate 125 MG Oral ...,[115.11],[0.0],[1],[115.11],[444814009.0],[365.0]
1104,2024,25291,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,[807283],[Mirena 52 MG Intrauterine System],[1132.83],[0.0],[12],[13593.96],[0.0],[365.0]
1105,2025,35366,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,[749785],[Ortho Tri-Cyclen 28 Day Pack],[35.34],[0.0],[12],[424.08],[0.0],[365.0]
1106,2026,28317,ffcfa457-00c2-4405-9837-ac2781549c7e,313782,Acetaminophen 325 MG Oral Tablet,5.63,0.0,1,5.63,10509002.0,365.0

In [196]:
prev = 0
for i in range(1,len(df_medications)):
    if df_medications.PATIENT[i] == df_medications.PATIENT[prev] :
        df_medications.drop(i,axis=0,inplace=True)
    else:
        prev=i

In [197]:
df_medications

,level_0,index,PATIENT,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,Medication_Time
0,0,25147,00185faa-2760-4218-9bf5-db301acf8274,[834061],[Penicillin V Potassium 250 MG Oral Tablet],[20.48],[0.0],[1],[20.48],[43878008.0],[365.0]
1,1,22123,0042862c-9889-4a2e-b782-fac1e540ecb4,[308182],[Amoxicillin 250 MG Oral Capsule],[14.82],[0.0],[1],[14.82],[0.0],[365.0]
2,2,40316,0047123f-12e7-486c-82df-53b3a450e365,"[562251, 1043400]",[Amoxicillin 250 MG / Clavulanate 125 MG Oral ...,"[55.53, 8.29]","[0.0, 0.0]","[1, 1]","[55.53, 8.29]","[444814009.0, 10509002.0]","[30.416666666666668, 365.0]"
3,4,5471,010d4a3a-2316-45ed-ae15-16f01c611674,[310798],[Hydrochlorothiazide 25 MG Oral Tablet],[263.49],[0.0],[12],[3161.88],[59621000.0],[730.0]
4,5,9000,0149d553-f571-4e99-867e-fcb9625d07c2,[831533],[Errin 28 Day Pack],[37.06],[0.0],[12],[444.72],[0.0],[334.5833333333333]
...,...,...,...,...,...,...,...,...,...,...,...
1102,2021,26992,ff02f237-fedb-453b-85b1-ebfc2609c312,"[849574, 562251]","[Naproxen sodium 220 MG Oral Tablet, Amoxicill...","[11.72, 16.52]","[0.0, 0.0]","[1, 1]","[11.72, 16.52]","[0.0, 444814009.0]","[30.416666666666668, 30.416666666666668]"
1103,2023,14201,ff3714ac-c7e3-4910-905e-2a321eb28144,[562251],[Amoxicillin 250 MG / Clavulanate 125 MG Oral ...,[115.11],[0.0],[1],[115.11],[444814009.0],[365.0]
1104,2024,25291,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,[807283],[Mirena 52 MG Intrauterine System],[1132.83],[0.0],[12],[13593.96],[0.0],[365.0]
1105,2025,35366,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,[749785],[Ortho Tri-Cyclen 28 Day Pack],[35.34],[0.0],[12],[424.08],[0.0],[365.0]
1106,2026,28317,ffcfa457-00c2-4405-9837-ac2781549c7e,313782,Acetaminophen 325 MG Oral Tablet,5.63,0.0,1,5.63,10509002.0,365.0

In [199]:
df = pd.merge(df,df_medications,how = 'outer',left_on='Id',right_on='PATIENT')

In [200]:
df.drop(['PATIENT','index','level_0'],axis=1,inplace=True)

In [201]:
df.rename(columns= {'CODE':'MEDICATION_CODE','BASE_COST':'MEDICATION_BASE_COST','PAYER_COVERAGE':'MEDICATION_PAYER_COVERAGE','DISPENSES':'MEDICATION_DISPENSES','TOTALCOST':'MEDICATION_TOTALCOST','REASONCODE':'MEDICATION_REASONCODE','DESCRIPTION':'Medicine_DESCRIPTION'},inplace=True)

In [202]:
df.fillna(0,inplace=True)

In [203]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,...,Immunization_Code,Immunization_BASE_COST,MEDICATION_CODE,Medicine_DESCRIPTION,MEDICATION_BASE_COST,MEDICATION_PAYER_COVERAGE,MEDICATION_DISPENSES,MEDICATION_TOTALCOST,MEDICATION_REASONCODE,Medication_Time
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,...,"[114, 113, 140, 140, 140, 43]","[140.52, 140.52, 140.52, 140.52, 140.52, 140.52]","[562251, 562251]",[Amoxicillin 250 MG / Clavulanate 125 MG Oral ...,"[11.91, 29.89]","[0.0, 0.0]","[1, 1]","[11.91, 29.89]","[444814009.0, 444814009.0]","[365.0, 30.416666666666668]"
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,...,"[140, 140, 113, 140, 140]","[140.52, 140.52, 140.52, 140.52, 140.52]",[313782],[Acetaminophen 325 MG Oral Tablet],[6.41],[0.0],[1],[6.41],[10509002.0],[30.416666666666668]
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,...,"[140, 140, 140, 140, 114, 113, 140, 43, 140]","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5...","[849574, 313782]","[Naproxen sodium 220 MG Oral Tablet, Acetamino...","[5.73, 8.14]","[0.0, 0.0]","[1, 1]","[5.73, 8.14]","[0.0, 10509002.0]","[30.416666666666668, 365.0]"
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,...,"[52, 140, 140, 140]","[140.52, 140.52, 140.52, 140.52]","[389221, 389221, 1534809]","[Etonogestrel 68 MG Drug Implant, Etonogestrel...","[677.08, 624.08, 39.2]","[0.0, 0.0, 0.0]","[12, 12, 12]","[8124.96, 7488.96, 470.4]","[0.0, 0.0, 0.0]","[334.5833333333333, 365.0, 365.0]"
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,...,"[140, 113, 140, 140, 114, 43, 140, 114, 140, 1...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5...",[313782],[Acetaminophen 325 MG Oral Tablet],[6.52],[0.0],[1],[6.52],[10509002.0],[365.0]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,...,"[140, 140, 140, 140, 113, 140, 140, 140, 140, ...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5...",[314231],[Simvastatin 10 MG Oral Tablet],[263.49],[203.49],[681],[179436.69],[55822004.0],[20440.0]
1168,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,...,"[140, 140, 52, 113, 140, 52, 140, 140]","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5...",[834102],[Penicillin V Potassium 500 MG Oral Tablet],[23.01],[0.0],[1],[23.01],[43878008.0],[365.0]
1169,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,...,"[113, 140, 140, 140, 140, 140, 140, 140, 140, ...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5...",[895994],[120 ACTUAT Fluticasone propionate 0.044 MG/AC...,[20.3],[0.0],[11],[223.3],[233678006.0],[334.5833333333333]
1170,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,...,"[140, 140, 140, 33, 140, 140, 140, 140, 140, 1...","[140.52, 140.52, 140.52, 140.52, 140.52, 140.5...",[2001499],[Vitamin B 12 5 MG/ML Injectable Solution],[263.49],[0.0],[286],[75358.14],[0.0],[1216.9389814814815]
1171,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,...,"[140, 140, 140, 140, 140, 140]","[140.52, 140.52, 140.52, 140.52, 140.52, 140.52]",0,0,0,0,0,0,0,0

In [204]:
df_observations

,DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,VALUE,UNITS,TYPE
0,2012-01-23T17:45:28Z,034e9e3b-2def-4559-bb2a-7850888ae060,e88bc3a9-007c-405e-aabc-792a38f4aa2b,8302-2,Body Height,193.3,cm,numeric
1,2012-01-23T17:45:28Z,034e9e3b-2def-4559-bb2a-7850888ae060,e88bc3a9-007c-405e-aabc-792a38f4aa2b,72514-3,Pain severity - 0-10 verbal numeric rating [Sc...,2.0,{score},numeric
2,2012-01-23T17:45:28Z,034e9e3b-2def-4559-bb2a-7850888ae060,e88bc3a9-007c-405e-aabc-792a38f4aa2b,29463-7,Body Weight,87.8,kg,numeric
3,2012-01-23T17:45:28Z,034e9e3b-2def-4559-bb2a-7850888ae060,e88bc3a9-007c-405e-aabc-792a38f4aa2b,39156-5,Body Mass Index,23.5,kg/m2,numeric
4,2012-01-23T17:45:28Z,034e9e3b-2def-4559-bb2a-7850888ae060,e88bc3a9-007c-405e-aabc-792a38f4aa2b,8462-4,Diastolic Blood Pressure,82.0,mm[Hg],numeric
...,...,...,...,...,...,...,...,...
299692,2015-09-05T16:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,NaN,QOLS,QOLS,1.0,{score},numeric
299693,2016-09-05T16:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,NaN,QOLS,QOLS,1.0,{score},numeric
299694,2017-09-05T16:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,NaN,QOLS,QOLS,1.0,{score},numeric
299695,2018-09-05T16:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,NaN,QOLS,QOLS,1.0,{score},numeric
299696,2019-09-05T16:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,NaN,QOLS,QOLS,1.0,{score},numeric

In [205]:
df_observations.drop(['DATE','ENCOUNTER','DESCRIPTION','TYPE'],axis=1,inplace=True)

In [206]:
df_observations

                                     PATIENT     CODE  VALUE    UNITS
0       034e9e3b-2def-4559-bb2a-7850888ae060   8302-2  193.3       cm
1       034e9e3b-2def-4559-bb2a-7850888ae060  72514-3    2.0  {score}
2       034e9e3b-2def-4559-bb2a-7850888ae060  29463-7   87.8       kg
3       034e9e3b-2def-4559-bb2a-7850888ae060  39156-5   23.5    kg/m2
4       034e9e3b-2def-4559-bb2a-7850888ae060   8462-4   82.0   mm[Hg]
...                                      ...      ...    ...      ...
299692  fc817953-cc8b-45db-9c85-7c0ced8fa90d     QOLS    1.0  {score}
299693  fc817953-cc8b-45db-9c85-7c0ced8fa90d     QOLS    1.0  {score}
299694  fc817953-cc8b-45db-9c85-7c0ced8fa90d     QOLS    1.0  {score}
299695  fc817953-cc8b-45db-9c85-7c0ced8fa90d     QOLS    1.0  {score}
299696  fc817953-cc8b-45db-9c85-7c0ced8fa90d     QOLS    1.0  {score}

[299697 rows x 4 columns]

In [207]:
prev = 0 
dict1 = {}
dict2 = {}
dict3 = {}
val=0
for i in range(1,len(df_observations)):
    if df_observations.PATIENT[i] == df_observations.PATIENT[prev] :
        #print(i)
        continue
    else :
        list1 = df_observations.CODE[prev:i].values
        list2 = df_observations.VALUE[prev:i].values
        list3 = df_observations.UNITS[prev:i].values
        dict1[df_observations.PATIENT[prev]] = list1
        dict2[df_observations.PATIENT[prev]] = list2
        dict3[df_observations.PATIENT[prev]] = list3
        prev = i
        if i == len(df_observations)-1 :
            val=1
if val==1:
    list1 = df_observations.CODE[prev]
    list2 = df_observations.VALUE[prev]
    list3 = df_observations.UNITS[prev]
    dict1[df_observations.PATIENT[prev]] = list1
    dict2[df_observations.PATIENT[prev]] = list2
    dict3[df_observations.PATIENT[prev]] = list3
else :
    list1 = [df_observations.CODE[prev:len(df_observations)]]
    list2 = [df_observations.VALUE[prev:len(df_observations)]]
    list3 = [df_observations.UNITS[prev:len(df_observations)]]    
    dict1[df_observations.PATIENT[prev]] = list1
    dict2[df_observations.PATIENT[prev]] = list2
    dict3[df_observations.PATIENT[prev]] = list3

In [208]:
len(dict1)

1171

In [209]:
df_observations.sort_values('PATIENT',inplace=True)

In [210]:
df_observations.drop_duplicates(subset = 'PATIENT',keep = 'first',inplace=True)

In [211]:
df_observations.reset_index(inplace=True)

In [212]:
df_observations['CODE'] = df_observations['CODE'].astype(object)
df_observations['VALUE'] = df_observations['VALUE'].astype(object)
df_observations['UNITS'] = df_observations['UNITS'].astype(object)

In [213]:
for i in range(len(df_observations)):
    df_observations.CODE[i] = dict1[df_observations.PATIENT[i]]
    df_observations.VALUE[i] = dict2[df_observations.PATIENT[i]]
    df_observations.UNITS[i] = dict3[df_observations.PATIENT[i]]

/tmp/ipykernel_25837/2958595767.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_observations.CODE[i] = dict1[df_observations.PATIENT[i]]
/tmp/ipykernel_25837/2958595767.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_observations.VALUE[i] = dict2[df_observations.PATIENT[i]]
/tmp/ipykernel_25837/2958595767.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_observations.UNITS[i] = dict3[df_observations.PATIENT[i]]

In [214]:
df_observations

,index,PATIENT,CODE,VALUE,UNITS
0,191135,00185faa-2760-4218-9bf5-db301acf8274,"[8302-2, 72514-3, 29463-7, 39156-5, 59576-9, 8...","[124.3, 1.0, 26.8, 17.3, 84.7, 86.0, 124.0, 98...","[cm, {score}, kg, kg/m2, %, mm[Hg], mm[Hg], /m..."
1,169056,0042862c-9889-4a2e-b782-fac1e540ecb4,"[8302-2, 72514-3, 29463-7, 77606-2, 9843-4, 84...","[61.7, 3.0, 5.8, 6.0, 40.8, 88.0, 117.0, 73.0,...","[cm, {score}, kg, %, cm, mm[Hg], mm[Hg], /min,..."
2,282520,0047123f-12e7-486c-82df-53b3a450e365,[QOLS],[0.8],[{score}]
3,41655,010d4a3a-2316-45ed-ae15-16f01c611674,"[8302-2, 72514-3, 29463-7, 39156-5, 59576-9, 8...","[143.1, 3.0, 45.2, 22.1, 89.7, 85.0, 109.0, 81...","[cm, {score}, kg, kg/m2, %, mm[Hg], mm[Hg], /m..."
4,812,01207ecd-9dff-4754-8887-4652eda231e2,"[8302-2, 72514-3, 29463-7, 77606-2, 9843-4, 84...","[49.9, 2.0, 3.8, 79.9, 33.5, 79.0, 112.0, 69.0...","[cm, {score}, kg, %, cm, mm[Hg], mm[Hg], /min,..."
...,...,...,...,...,...
1166,202308,ff02f237-fedb-453b-85b1-ebfc2609c312,[QOLS],[1.0],[{score}]
1167,97661,ff3714ac-c7e3-4910-905e-2a321eb28144,"[8302-2, 72514-3, 29463-7, 39156-5, 59576-9, 8...","[147.2, 1.0, 37.4, 17.3, 29.0, 73.0, 110.0, 80...","[cm, {score}, kg, kg/m2, %, mm[Hg], mm[Hg], /m..."
1168,192631,ff6948b7-3d62-4bfc-bc7d-dbb6748ed0be,"[8302-2, 72514-3, 29463-7, 39156-5, 8462-4, 84...","[170.6, 0.0, 83.8, 28.8, 76.0, 136.0, 98.0, 15...","[cm, {score}, kg, kg/m2, mm[Hg], mm[Hg], /min,..."
1169,247516,ffa37e71-fa14-4e84-ba9d-aece8d1d99f9,"[8302-2, 72514-3, 29463-7, 39156-5, 8462-4, 84...","[159.0, 2.0, 76.8, 30.4, 73.0, 139.0, 86.0, 15...","[cm, {score}, kg, kg/m2, mm[Hg], mm[Hg], /min,..."
1170,212234,ffcfa457-00c2-4405-9837-ac2781549c7e,"[8302-2, 72514-3, 29463-7, 77606-2, 9843-4, 84...","[47.6, 2.0, 1.8, 0.0, 31.0, 81.0, 113.0, 67.0,...","[cm, {score}, kg, %, cm, mm[Hg], mm[Hg], /min,..."

In [215]:
df = pd.merge(df,df_observations,how = 'outer',left_on='Id',right_on='PATIENT')

In [216]:
df.drop(['PATIENT','index'],axis=1,inplace=True)

In [217]:
df.rename(columns = {'CODE':'OBSERVATION_CODE','VALUE':'OBSERVATION_VALUE','UNITS':'OBSERVATION_UNITS'},inplace=True)

In [218]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,...,Medicine_DESCRIPTION,MEDICATION_BASE_COST,MEDICATION_PAYER_COVERAGE,MEDICATION_DISPENSES,MEDICATION_TOTALCOST,MEDICATION_REASONCODE,Medication_Time,OBSERVATION_CODE,OBSERVATION_VALUE,OBSERVATION_UNITS
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,...,[Amoxicillin 250 MG / Clavulanate 125 MG Oral ...,"[11.91, 29.89]","[0.0, 0.0]","[1, 1]","[11.91, 29.89]","[444814009.0, 444814009.0]","[365.0, 30.416666666666668]",[QOLS],[1.0],[{score}]
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,...,[Acetaminophen 325 MG Oral Tablet],[6.41],[0.0],[1],[6.41],[10509002.0],[30.416666666666668],[QOLS],[1.0],[{score}]
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,...,"[Naproxen sodium 220 MG Oral Tablet, Acetamino...","[5.73, 8.14]","[0.0, 0.0]","[1, 1]","[5.73, 8.14]","[0.0, 10509002.0]","[30.416666666666668, 365.0]",[QOLS],[1.0],[{score}]
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,...,"[Etonogestrel 68 MG Drug Implant, Etonogestrel...","[677.08, 624.08, 39.2]","[0.0, 0.0, 0.0]","[12, 12, 12]","[8124.96, 7488.96, 470.4]","[0.0, 0.0, 0.0]","[334.5833333333333, 365.0, 365.0]",[QOLS],[1.0],[{score}]
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,...,[Acetaminophen 325 MG Oral Tablet],[6.52],[0.0],[1],[6.52],[10509002.0],[365.0],"[DALY, DALY, DALY, DALY, DALY, DALY, DALY, QOL...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, ...","[a, a, a, a, a, a, a, {score}, {score}, {score..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,...,[Simvastatin 10 MG Oral Tablet],[263.49],[203.49],[681],[179436.69],[55822004.0],[20440.0],"[8302-2, 72514-3, 29463-7, 39156-5, 8462-4, 84...","[168.5, 3.0, 85.7, 30.2, 88.0, 110.0, 67.0, 13...","[cm, {score}, kg, kg/m2, mm[Hg], mm[Hg], /min,..."
1168,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,...,[Penicillin V Potassium 500 MG Oral Tablet],[23.01],[0.0],[1],[23.01],[43878008.0],[365.0],"[8302-2, 72514-3, 29463-7, 39156-5, 8462-4, 84...","[191.4, 1.0, 91.9, 25.1, 76.0, 119.0, 75.0, 14...","[cm, {score}, kg, kg/m2, mm[Hg], mm[Hg], /min,..."
1169,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,...,[120 ACTUAT Fluticasone propionate 0.044 MG/AC...,[20.3],[0.0],[11],[223.3],[233678006.0],[334.5833333333333],"[72106-8, 8302-2, 72514-3, 29463-7, 39156-5, 8...","[17.2, 153.8, 0.0, 72.2, 30.5, 86.0, 139.0, 91...","[(score), cm, {score}, kg, kg/m2, mm[Hg], mm[H..."
1170,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,...,[Vitamin B 12 5 MG/ML Injectable Solution],[263.49],[0.0],[286],[75358.14],[0.0],[1216.9389814814815],"[8302-2, 72514-3, 29463-7, 39156-5, 8462-4, 84...","[162.8, 3.0, 74.4, 28.1, 86.0, 131.0, 95.0, 12...","[cm, {score}, kg, kg/m2, mm[Hg], mm[Hg], /min,..."
1171,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,...,0,0,0,0,0,0,0,"[[8302-2, 72514-3, 29463-7, 39156-5, 8462-4, 8...","[[165.7, 0.0, 76.6, 27.9, 82.0, 123.0, 64.0, 1...","[[cm, {score}, kg, kg/m2, mm[Hg], mm[Hg], /min..."

In [219]:
df_procedures

,DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION
0,2011-04-30T00:26:23Z,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,6aa37300-d1b4-48e7-a2f8-5e0f70f48f38,169553002,Insertion of subcutaneous contraceptive,14896.56,NaN,NaN
1,2010-07-27T12:58:08Z,10339b10-3cd1-4ac3-ac13-ec26728cb592,dae2b7cb-1316-4b78-954f-fa610a6c6d0e,430193006,Medication Reconciliation (procedure),726.51,NaN,NaN
2,2010-11-20T03:04:34Z,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,7ff86631-0378-4bfc-92ce-1edd697eb18e,430193006,Medication Reconciliation (procedure),788.50,NaN,NaN
3,2011-02-07T03:04:34Z,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,b8f76eba-7795-4dcd-a544-f27ac2ef3d46,117015009,Throat culture (procedure),2070.44,195662009.0,Acute viral pharyngitis (disorder)
4,2011-04-19T03:04:34Z,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,640837d9-845a-433c-9fad-47426664a69d,117015009,Throat culture (procedure),2479.39,195662009.0,Acute viral pharyngitis (disorder)
...,...,...,...,...,...,...,...,...
34976,2010-05-22T17:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,4718c69a-f0d3-4973-be8b-6d65c900451f,430193006,Medication Reconciliation (procedure),581.88,NaN,NaN
34977,2013-06-08T17:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,f4d4f19e-6377-4627-8a6f-760beba1fc6b,430193006,Medication Reconciliation (procedure),427.71,NaN,NaN
34978,2015-06-20T17:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,bd3bfc3c-4f52-4d9c-aa01-60a084b2ddcd,430193006,Medication Reconciliation (procedure),397.80,NaN,NaN
34979,2017-07-01T17:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,957b13d5-49fa-4518-8c25-6eaa45e6a7d1,430193006,Medication Reconciliation (procedure),346.55,NaN,NaN
34980,2019-07-13T17:27:52Z,fc817953-cc8b-45db-9c85-7c0ced8fa90d,1306d180-d887-4286-b940-9a6a2425cf93,430193006,Medication Reconciliation (procedure),615.19,NaN,NaN

In [220]:
df_procedures.drop(['DATE','ENCOUNTER','REASONDESCRIPTION'],axis=1,inplace=True)

In [221]:
df_procedures.fillna(0,inplace=True)

In [222]:
df_procedures

,PATIENT,CODE,DESCRIPTION,BASE_COST,REASONCODE
0,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,169553002,Insertion of subcutaneous contraceptive,14896.56,0.0
1,10339b10-3cd1-4ac3-ac13-ec26728cb592,430193006,Medication Reconciliation (procedure),726.51,0.0
2,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,430193006,Medication Reconciliation (procedure),788.50,0.0
3,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,117015009,Throat culture (procedure),2070.44,195662009.0
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,117015009,Throat culture (procedure),2479.39,195662009.0
...,...,...,...,...,...
34976,fc817953-cc8b-45db-9c85-7c0ced8fa90d,430193006,Medication Reconciliation (procedure),581.88,0.0
34977,fc817953-cc8b-45db-9c85-7c0ced8fa90d,430193006,Medication Reconciliation (procedure),427.71,0.0
34978,fc817953-cc8b-45db-9c85-7c0ced8fa90d,430193006,Medication Reconciliation (procedure),397.80,0.0
34979,fc817953-cc8b-45db-9c85-7c0ced8fa90d,430193006,Medication Reconciliation (procedure),346.55,0.0
34980,fc817953-cc8b-45db-9c85-7c0ced8fa90d,430193006,Medication Reconciliation (procedure),615.19,0.0

In [223]:
prev = 0 
dict1 = {}
dict2 = {}
dict3 = {}
val=0
for i in range(1,len(df_procedures)):
    if df_procedures.PATIENT[i] == df_procedures.PATIENT[prev] :
        #print(i)
        continue
    else :
        list1 = df_procedures.CODE[prev:i].values
        list2 = df_procedures.BASE_COST[prev:i].values
        list3 = df_procedures.REASONCODE[prev:i].values
        list4 = df_procedures.DESCRIPTION[prev:i].values
        dict1[df_procedures.PATIENT[prev]] = list1
        dict2[df_procedures.PATIENT[prev]] = list2
        dict3[df_procedures.PATIENT[prev]] = list3
        dict4[df_procedures.PATIENT[prev]] = list4
        prev = i
        if i == len(df_procedures)-1 :
            val=1
if val==1:
    list1 = df_procedures.CODE[prev]
    list2 = df_procedures.BASE_COST[prev]
    list3 = df_procedures.REASONCODE[prev]
    list4 = df_procedures.DESCRIPTION[prev]
    dict1[df_procedures.PATIENT[prev]] = list1
    dict2[df_procedures.PATIENT[prev]] = list2
    dict3[df_procedures.PATIENT[prev]] = list3
    dict4[df_procedures.PATIENT[prev]] = list4
else :
    list1 = [df_procedures.CODE[prev:len(df_procedures)]]
    list2 = [df_procedures.BASE_COST[prev:len(df_procedures)]]
    list3 = [df_procedures.REASONCODE[prev:len(df_procedures)]]   
    list4 = [df_procedures.DESCRIPTION[prev:len(df_procedures)]]    
    dict1[df_procedures.PATIENT[prev]] = list1
    dict2[df_procedures.PATIENT[prev]] = list2
    dict3[df_procedures.PATIENT[prev]] = list3
    dict4[df_procedures.PATIENT[prev]] = list4

In [224]:
len(dict1)

1165

In [225]:
df_procedures.drop_duplicates(subset = 'PATIENT',keep = 'first',inplace=True)

In [226]:
df_procedures

,PATIENT,CODE,DESCRIPTION,BASE_COST,REASONCODE
0,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,169553002,Insertion of subcutaneous contraceptive,14896.56,0.0
1,10339b10-3cd1-4ac3-ac13-ec26728cb592,430193006,Medication Reconciliation (procedure),726.51,0.0
2,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,430193006,Medication Reconciliation (procedure),788.50,0.0
8,034e9e3b-2def-4559-bb2a-7850888ae060,430193006,Medication Reconciliation (procedure),551.78,0.0
13,1d604da9-9a81-4ba9-80c2-de3375d59b40,430193006,Medication Reconciliation (procedure),416.69,0.0
...,...,...,...,...,...
34904,023a7d29-32b3-4db5-89c8-b88bd7582ec0,180325003,Electrical cardioversion,27817.23,49436004.0
34917,1fc8dafd-90e5-44d6-9179-81156c0ea083,430193006,Medication Reconciliation (procedure),418.86,0.0
34919,6d048a56-edb8-4f29-891d-7a84d75a8e78,430193006,Medication Reconciliation (procedure),523.41,0.0
34959,fca3178e-fb68-41c3-8598-702d3ca68b96,40701008,Echocardiography (procedure),1046.36,230690007.0
34976,fc817953-cc8b-45db-9c85-7c0ced8fa90d,430193006,Medication Reconciliation (procedure),581.88,0.0

In [227]:
df_procedures.reset_index(inplace=True)

In [230]:
df_procedures['CODE'] = df_procedures['CODE'].astype(object)
df_procedures['BASE_COST'] = df_procedures['BASE_COST'].astype(object)
df_procedures['REASONCODE'] = df_procedures['REASONCODE'].astype(object)
df_procedures['DESCRIPTION'] = df_procedures['DESCRIPTION'].astype(object)

In [231]:
for i in range(len(df_procedures)):
    df_procedures.CODE[i] = dict1[df_procedures.PATIENT[i]]
    df_procedures.BASE_COST[i] = dict2[df_procedures.PATIENT[i]]
    df_procedures.REASONCODE[i] = dict3[df_procedures.PATIENT[i]]
    df_procedures.DESCRIPTION[i] = dict4[df_procedures.PATIENT[i]]

/tmp/ipykernel_25837/213394400.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_procedures.CODE[i] = dict1[df_procedures.PATIENT[i]]
/tmp/ipykernel_25837/213394400.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_procedures.BASE_COST[i] = dict2[df_procedures.PATIENT[i]]
/tmp/ipykernel_25837/213394400.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_procedures.REASONCODE[i] = dict3[df_procedures.PATIENT[i]]
/tmp/ipykernel_25837/213394400.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_procedures.DESCRIPTION[i] = dict4[df_procedures.PATIENT[i]]

In [232]:
df = pd.merge(df,df_procedures,how = 'outer',left_on='Id',right_on='PATIENT')

In [233]:
df.drop(['index','PATIENT'],axis=1,inplace=True)

In [234]:
df.fillna(0,inplace=True)

In [235]:
df.rename(columns = {'CODE':'PROCEDURE_CODE','BASE_COST':'PROCEDURE_BASE_COST','REASONCODE':'PROCEDURE_REASONCODE','DESCRIPTION':'Procedure_DESCRIPTION'},inplace=True)

In [236]:
df

,Id,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,Age,Alive,...,MEDICATION_TOTALCOST,MEDICATION_REASONCODE,Medication_Time,OBSERVATION_CODE,OBSERVATION_VALUE,OBSERVATION_UNITS,PROCEDURE_CODE,Procedure_DESCRIPTION,PROCEDURE_BASE_COST,PROCEDURE_REASONCODE
0,1d604da9-9a81-4ba9-80c2-de3375d59b40,M,white,hispanic,M,Marigot Saint Andrew Parish DM,271227.08,1334.88,32,1,...,"[11.91, 29.89]","[444814009.0, 444814009.0]","[365.0, 30.416666666666668]",[QOLS],[1.0],[{score}],[430193006],[Medication Reconciliation (procedure)],[416.69],[0.0]
1,034e9e3b-2def-4559-bb2a-7850888ae060,M,white,nonhispanic,M,Danvers Massachusetts US,793946.01,3204.49,37,1,...,[6.41],[10509002.0],[30.416666666666668],[QOLS],[1.0],[{score}],[430193006],[Medication Reconciliation (procedure)],[585.69],[0.0]
2,10339b10-3cd1-4ac3-ac13-ec26728cb592,M,white,nonhispanic,M,Springfield Massachusetts US,574111.90,2606.40,29,1,...,"[5.73, 8.14]","[0.0, 10509002.0]","[30.416666666666668, 365.0]",[QOLS],[1.0],[{score}],"[430193006, 269911007, 430193006]","[Medication Reconciliation (procedure), Sputum...","[610.08, 6805.0, 706.32]","[0.0, 10509002.0, 0.0]"
3,8d4c4326-e9de-4f45-9a4c-f8c36bff89ae,M,white,nonhispanic,F,Yarmouth Massachusetts US,935630.30,8756.19,43,1,...,"[8124.96, 7488.96, 470.4]","[0.0, 0.0, 0.0]","[334.5833333333333, 365.0, 365.0]",[QOLS],[1.0],[{score}],"[430193006, 76601001]","[Medication Reconciliation (procedure), Intram...","[620.16, 3001.57]","[0.0, 0.0]"
4,f5dcd418-09fe-4a2f-baa0-3da800bd8c3a,0,white,nonhispanic,M,Patras Achaea GR,598763.07,3772.20,25,1,...,[6.52],[10509002.0],[365.0],"[DALY, DALY, DALY, DALY, DALY, DALY, DALY, QOL...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, ...","[a, a, a, a, a, a, a, {score}, {score}, {score...",[430193006],[Medication Reconciliation (procedure)],[568.06],[0.0]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,023a7d29-32b3-4db5-89c8-b88bd7582ec0,M,asian,hispanic,F,Juarez Chihuahua MX,1622314.87,32086.31,99,1,...,[179436.69],[55822004.0],[20440.0],"[8302-2, 72514-3, 29463-7, 39156-5, 8462-4, 84...","[168.5, 3.0, 85.7, 30.2, 88.0, 110.0, 67.0, 13...","[cm, {score}, kg, kg/m2, mm[Hg], mm[Hg], /min,...","[180325003, 180325003, 180325003, 180325003, 1...","[Electrical cardioversion, Electrical cardiove...","[27817.23, 33481.44, 37212.77, 29806.28, 40947...","[49436004.0, 49436004.0, 49436004.0, 49436004...."
1168,1fc8dafd-90e5-44d6-9179-81156c0ea083,S,white,nonhispanic,M,Upton Massachusetts US,979724.25,3130.52,44,1,...,[23.01],[43878008.0],[365.0],"[8302-2, 72514-3, 29463-7, 39156-5, 8462-4, 84...","[191.4, 1.0, 91.9, 25.1, 76.0, 119.0, 75.0, 14...","[cm, {score}, kg, kg/m2, mm[Hg], mm[Hg], /min,...","[430193006, 430193006]","[Medication Reconciliation (procedure), Medica...","[418.86, 578.97]","[0.0, 0.0]"
1169,6d048a56-edb8-4f29-891d-7a84d75a8e78,S,white,nonhispanic,F,Fall River Massachusetts US,1560540.35,52391.24,107,0,...,[223.3],[233678006.0],[334.5833333333333],"[72106-8, 8302-2, 72514-3, 29463-7, 39156-5, 8...","[17.2, 153.8, 0.0, 72.2, 30.5, 86.0, 139.0, 91...","[(score), cm, {score}, kg, kg/m2, mm[Hg], mm[H...","[430193006, 71651007, 35025007, 90226004, 7165...","[Medication Reconciliation (procedure), Mammog...","[523.41, 516.65, 516.65, 1783.78, 516.65, 516....","[0.0, 254837009.0, 254837009.0, 254837009.0, 2..."
1170,fca3178e-fb68-41c3-8598-702d3ca68b96,M,white,nonhispanic,F,Springfield Massachusetts US,1375833.47,13157.00,107,0,...,[75358.14],[0.0],[1216.9389814814815],"[8302-2, 72514-3, 29463-7, 39156-5, 8462-4, 84...","[162.8, 3.0, 74.4, 28.1, 86.0, 131.0, 95.0, 12...","[cm, {score}, kg, kg/m2, mm[Hg], mm[Hg], /min,...","[40701008, 433112001, 73761001, 430193006, 430...","[Echocardiography (procedure), Percutaneous me...","[1046.36, 32887.07, 13866.55, 355.65, 682.22, ...","[230690007.0, 230690007.0, 0.0, 0.0, 0.0, 0.0,..."
1171,fc817953-cc8b-45db-9c85-7c0ced8fa90d,M,white,nonhispanic,F,Worcester Massachusetts US,1510158.34,26565.65,107,1,...,0,0,0,"[[8302-2, 72514-3, 29463-7, 39156-5, 8462-4, 8...","[[165.7, 0.0, 76.6, 27.9, 82.0, 123.0, 64.0, 1...","[[cm, {score}, kg, kg/m2, mm[Hg], mm[Hg], /min...","[[430193006, 430193006, 430193006, 430193006, ...","[[Medication Reconciliation (procedure), Medic...","[[581.88, 427.71, 397.8, 346.55, 615.19]]","[[0.0, 0.0, 0.0, 0.0, 0.0]]"

In [237]:
df.to_csv('final.csv')